<template>
  <AppLayout>
    <div class="mx-auto max-w-7xl space-y-6">
      <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm font-medium text-primary-600">客服工作台</p><h1 class="mt-1 text-2xl font-bold text-gray-900 dark:text-white">工单管理</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">集中查看用户问题、回复工单并更新处理状态。</p></div><div class="rounded-xl border border-gray-200 bg-white px-4 py-3 text-sm shadow-sm dark:border-dark-700 dark:bg-dark-900"><span class="text-gray-500">待处理</span><strong class="ml-2 text-amber-600">{{ pendingCount }}</strong></div></header>
      <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</div>
      <div class="grid items-start gap-6 lg:grid-cols-[22rem_minmax(0,1fr)]">
        <section class="rounded-2xl border border-gray-200/80 bg-white/80 p-3 shadow-sm dark:border-dark-700 dark:bg-dark-900/80"><div class="mb-3 flex items-center justify-between px-2"><h2 class="font-semibold">全部工单</h2><button class="btn btn-ghost btn-sm" :disabled="loading" @click="load()"><Icon name="refresh" size="sm" /></button></div><div class="space-y-2"><button v-for="ticket in tickets" :key="ticket.id" class="w-full rounded-xl border p-3 text-left" :class="selected?.id === ticket.id ? 'border-primary-400 bg-primary-50 dark:bg-primary-950/40' : 'border-transparent bg-gray-50 dark:bg-dark-800/70'" @click="select(ticket.id)"><div class="flex items-start justify-between gap-2"><span class="truncate font-medium">{{ ticket.title }}</span><span class="rounded-full px-2 py-0.5 text-[10px] font-semibold" :class="statusClass(ticket.status)">{{ statusLabel(ticket.status) }}</span></div><div class="mt-2 truncate text-xs text-gray-500">#{{ ticket.id }} · {{ ticket.user_email || ticket.user_name }}</div><div class="mt-1 text-xs text-gray-400">{{ formatDate(ticket.updated_at) }}</div></button><div v-if="!tickets.length" class="rounded-xl border border-dashed p-10 text-center text-sm text-gray-500">暂无工单</div></div></section>
        <section v-if="selected" class="rounded-2xl border border-gray-200/80 bg-white/80 shadow-sm dark:border-dark-700 dark:bg-dark-900/80"><div class="flex items-start justify-between gap-4 border-b border-gray-100 p-5 dark:border-dark-700"><div><div class="flex flex-wrap items-center gap-3"><h2 class="text-xl font-bold">{{ selected.title }}</h2><span class="rounded-full px-2 py-0.5 text-[10px] font-semibold" :class="statusClass(selected.status)">{{ statusLabel(selected.status) }}</span></div><p class="mt-1 text-xs text-gray-500">工单 #{{ selected.id }} · {{ selected.user_name || '用户' }} · {{ selected.user_email }}</p></div><button v-if="selected.status !== 'closed'" class="btn btn-secondary text-red-600" :disabled="loading" @click="closeTicket"><Icon name="close" size="sm" class="mr-1" />关闭工单</button></div><div class="space-y-4 p-5" @scroll="handleMessageScroll"><div v-for="message in selected.messages" :key="message.id" class="rounded-2xl p-4" :class="message.sender_type === 'admin' ? 'ml-8 bg-primary-50 dark:bg-primary-950/30' : 'mr-8 bg-gray-50 dark:bg-dark-800'"><div class="mb-2 text-xs text-gray-500">{{ message.sender_type === 'admin' ? '管理员' : (selected.user_name || '用户') }} · {{ formatDate(message.created_at) }}</div><div class="whitespace-pre-wrap text-sm">{{ message.content }}</div><TicketImageAttachments class="mt-3" :images="message.images || []" @preview="previewImage" /></div></div><button v-if="newMessageCount" class="fixed bottom-6 left-1/2 z-30 -translate-x-1/2 rounded-full bg-primary-600 px-4 py-2 text-sm font-medium text-white shadow-lg" @click="scrollMessagesToBottom">有 {{ newMessageCount }} 条新消息，点击查看</button><form v-if="selected.status !== 'closed'" class="border-t border-gray-100 p-5 dark:border-dark-700" @submit.prevent="reply"><textarea v-model="replyText" class="input min-h-32 w-full resize-y" placeholder="回复用户，首次回复会将工单标记为处理中…" required maxlength="10000" @paste="handlePaste" /><div class="mt-3 flex flex-wrap items-center justify-between gap-3"><div class="flex items-center gap-2"><label class="btn btn-secondary btn-sm cursor-pointer"><input type="file" accept="image/*" multiple class="hidden" @change="pickFiles" /><Icon name="upload" size="sm" class="mr-1.5" />添加图片</label><span class="text-xs text-gray-500">{{ replyImages.length }}/9</span></div><button class="btn btn-primary" :disabled="loading || !replyText.trim()">发送回复并通知用户</button></div><TicketImageAttachments class="mt-3" :images="replyImages" removable @preview="previewImage" @remove="replyImages.splice($event, 1)" /></form><div v-else class="border-t border-gray-100 px-5 py-4 text-sm text-gray-500">此工单已关闭。</div></section>
        <section v-else class="flex min-h-[28rem] items-center justify-center rounded-2xl border border-dashed border-gray-300 text-center"><div><Icon name="message" size="xl" class="mx-auto text-gray-400" /><h2 class="mt-4 font-semibold">选择工单开始处理</h2><p class="mt-1 text-sm text-gray-500">用户回复后，符合通知间隔规则时会发送邮件。</p></div></section>
      </div>
      <TicketImageLightbox v-model="lightboxImage" />
    </div>
  </AppLayout>
</template>
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref } from 'vue'; import AppLayout from '@/components/layout/AppLayout.vue'; import Icon from '@/components/icons/Icon.vue'; import TicketImageAttachments from '@/components/common/TicketImageAttachments.vue'; import TicketImageLightbox from '@/components/common/TicketImageLightbox.vue'; import { adminTicketsAPI, type Ticket } from '@/api/tickets'
const tickets = ref<Ticket[]>([]); const selected = ref<Ticket | null>(null); const replyText = ref(''); const replyImages = ref<string[]>([]); const loading = ref(false); const error = ref(''); const lightboxImage = ref(''); const newMessageCount = ref(0); const pendingCount = computed(() => tickets.value.filter(t => t.status === 'pending').length); const formatDate = (v: string) => new Date(v).toLocaleString(); const statusLabel = (s: string) => s === 'closed' ? '已关闭' : s === 'processing' ? '处理中' : '待处理'; const statusClass = (s: string) => s === 'closed' ? 'bg-gray-100 text-gray-500' : s === 'processing' ? 'bg-blue-100 text-blue-700' : 'bg-amber-100 text-amber-700'; const previewImage = (image: string) => { lightboxImage.value = image }
const messageList = () => document.querySelector<HTMLElement>('section > div.space-y-4'); const isAtMessageBottom = () => { const element = messageList(); return !element || element.scrollHeight - element.scrollTop - element.clientHeight < 24 }; async function scrollMessagesToBottom() { await nextTick(); const element = messageList(); if (element) element.scrollTop = element.scrollHeight; newMessageCount.value = 0 } function handleMessageScroll() { if (isAtMessageBottom()) newMessageCount.value = 0 }
async function readFiles(files: File[]) { return Promise.all(files.filter(f => f.type.startsWith('image/')).map(file => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file) }))) }
async function pickFiles(event: Event) { const input = event.target as HTMLInputElement; replyImages.value.push(...await readFiles(Array.from(input.files || []).slice(0, 9 - replyImages.value.length))); input.value = '' }
async function handlePaste(event: ClipboardEvent) { const files = Array.from(event.clipboardData?.items || []).filter(item => item.type.startsWith('image/')).map(item => item.getAsFile()).filter((f): f is File => !!f); if (files.length) { event.preventDefault(); replyImages.value.push(...await readFiles(files.slice(0, 9 - replyImages.value.length))) } }
async function load(silent: boolean | PointerEvent = false) { const isSilent = typeof silent === 'boolean' ? silent : false; if (!isSilent) loading.value = true; try { tickets.value = await adminTicketsAPI.list(); if (selected.value && tickets.value.some(t => t.id === selected.value?.id)) await select(selected.value.id, true); else if (!selected.value && tickets.value.length) await select(tickets.value[0].id) } catch (e) { if (!isSilent) error.value = String(e) } finally { if (!isSilent) loading.value = false } }
async function select(id: number, preserveScroll = false) { const previous = selected.value?.id === id ? selected.value.messages?.at(-1)?.id : undefined; const wasAtBottom = isAtMessageBottom(); try { selected.value = await adminTicketsAPI.get(id); const latest = selected.value.messages?.at(-1)?.id; if (preserveScroll && previous && latest && previous !== latest && !wasAtBottom) newMessageCount.value += 1; else { newMessageCount.value = 0; await scrollMessagesToBottom() } } catch (e) { error.value = String(e) } }
async function reply() { if (!selected.value || !replyText.value.trim()) return; loading.value = true; try { await adminTicketsAPI.reply(selected.value.id, { content: replyText.value, images: replyImages.value }); replyText.value = ''; replyImages.value = []; await select(selected.value.id); await scrollMessagesToBottom(); await load(true) } catch (e) { error.value = String(e) } finally { loading.value = false } }
async function closeTicket() { if (!selected.value) return; loading.value = true; try { await adminTicketsAPI.close(selected.value.id); await load() } catch (e) { error.value = String(e) } finally { loading.value = false } }
let refreshTimer: ReturnType<typeof setInterval> | undefined; onMounted(() => { void load(); refreshTimer = setInterval(() => { if (!loading.value) void load(true) }, 15000) }); onBeforeUnmount(() => { if (refreshTimer) clearInterval(refreshTimer) })
</script>
<style scoped>
section > div.space-y-4 { max-height: min(24rem, calc(100vh - 16rem)); overflow-y: auto; overscroll-behavior: contain; }
</style>
