// Code generated by ent, DO NOT EDIT.

package securitysecret

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldID, id))
REDACTED

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldID, id))
REDACTED

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNEQ(FieldID, id))
REDACTED

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldIn(FieldID, ids...))
REDACTED

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNotIn(FieldID, ids...))
REDACTED

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGT(FieldID, id))
REDACTED

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGTE(FieldID, id))
REDACTED

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLT(FieldID, id))
REDACTED

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLTE(FieldID, id))
REDACTED

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldCreatedAt, v))
REDACTED

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldUpdatedAt, v))
REDACTED

// Key applies equality check predicate on the "key" field. It's identical to KeyEQ.
func Key(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldKey, v))
REDACTED

// Value applies equality check predicate on the "value" field. It's identical to ValueEQ.
func Value(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldValue, v))
REDACTED

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldCreatedAt, v))
REDACTED

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNEQ(FieldCreatedAt, v))
REDACTED

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldIn(FieldCreatedAt, vs...))
REDACTED

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNotIn(FieldCreatedAt, vs...))
REDACTED

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGT(FieldCreatedAt, v))
REDACTED

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGTE(FieldCreatedAt, v))
REDACTED

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLT(FieldCreatedAt, v))
REDACTED

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLTE(FieldCreatedAt, v))
REDACTED

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldUpdatedAt, v))
REDACTED

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNEQ(FieldUpdatedAt, v))
REDACTED

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldIn(FieldUpdatedAt, vs...))
REDACTED

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNotIn(FieldUpdatedAt, vs...))
REDACTED

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGT(FieldUpdatedAt, v))
REDACTED

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGTE(FieldUpdatedAt, v))
REDACTED

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLT(FieldUpdatedAt, v))
REDACTED

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLTE(FieldUpdatedAt, v))
REDACTED

// KeyEQ applies the EQ predicate on the "key" field.
func KeyEQ(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldKey, v))
REDACTED

// KeyNEQ applies the NEQ predicate on the "key" field.
func KeyNEQ(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNEQ(FieldKey, v))
REDACTED

// KeyIn applies the In predicate on the "key" field.
func KeyIn(vs ...string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldIn(FieldKey, vs...))
REDACTED

// KeyNotIn applies the NotIn predicate on the "key" field.
func KeyNotIn(vs ...string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNotIn(FieldKey, vs...))
REDACTED

// KeyGT applies the GT predicate on the "key" field.
func KeyGT(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGT(FieldKey, v))
REDACTED

// KeyGTE applies the GTE predicate on the "key" field.
func KeyGTE(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGTE(FieldKey, v))
REDACTED

// KeyLT applies the LT predicate on the "key" field.
func KeyLT(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLT(FieldKey, v))
REDACTED

// KeyLTE applies the LTE predicate on the "key" field.
func KeyLTE(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLTE(FieldKey, v))
REDACTED

// KeyContains applies the Contains predicate on the "key" field.
func KeyContains(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldContains(FieldKey, v))
REDACTED

// KeyHasPrefix applies the HasPrefix predicate on the "key" field.
func KeyHasPrefix(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldHasPrefix(FieldKey, v))
REDACTED

// KeyHasSuffix applies the HasSuffix predicate on the "key" field.
func KeyHasSuffix(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldHasSuffix(FieldKey, v))
REDACTED

// KeyEqualFold applies the EqualFold predicate on the "key" field.
func KeyEqualFold(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEqualFold(FieldKey, v))
REDACTED

// KeyContainsFold applies the ContainsFold predicate on the "key" field.
func KeyContainsFold(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldContainsFold(FieldKey, v))
REDACTED

// ValueEQ applies the EQ predicate on the "value" field.
func ValueEQ(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEQ(FieldValue, v))
REDACTED

// ValueNEQ applies the NEQ predicate on the "value" field.
func ValueNEQ(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNEQ(FieldValue, v))
REDACTED

// ValueIn applies the In predicate on the "value" field.
func ValueIn(vs ...string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldIn(FieldValue, vs...))
REDACTED

// ValueNotIn applies the NotIn predicate on the "value" field.
func ValueNotIn(vs ...string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldNotIn(FieldValue, vs...))
REDACTED

// ValueGT applies the GT predicate on the "value" field.
func ValueGT(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGT(FieldValue, v))
REDACTED

// ValueGTE applies the GTE predicate on the "value" field.
func ValueGTE(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldGTE(FieldValue, v))
REDACTED

// ValueLT applies the LT predicate on the "value" field.
func ValueLT(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLT(FieldValue, v))
REDACTED

// ValueLTE applies the LTE predicate on the "value" field.
func ValueLTE(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldLTE(FieldValue, v))
REDACTED

// ValueContains applies the Contains predicate on the "value" field.
func ValueContains(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldContains(FieldValue, v))
REDACTED

// ValueHasPrefix applies the HasPrefix predicate on the "value" field.
func ValueHasPrefix(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldHasPrefix(FieldValue, v))
REDACTED

// ValueHasSuffix applies the HasSuffix predicate on the "value" field.
func ValueHasSuffix(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldHasSuffix(FieldValue, v))
REDACTED

// ValueEqualFold applies the EqualFold predicate on the "value" field.
func ValueEqualFold(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldEqualFold(FieldValue, v))
REDACTED

// ValueContainsFold applies the ContainsFold predicate on the "value" field.
func ValueContainsFold(v string) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.FieldContainsFold(FieldValue, v))
REDACTED

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SecuritySecret) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.AndPredicates(predicates...))
REDACTED

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SecuritySecret) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.OrPredicates(predicates...))
REDACTED

// Not applies the not operator on the given predicate.
func Not(p predicate.SecuritySecret) predicate.SecuritySecret {
	return predicate.SecuritySecret(sql.NotPredicates(p))
REDACTED
