// Code generated by ent, DO NOT EDIT.

package accountcodexdeviceslot

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldID, id))
}

// AccountID applies equality check predicate on the "account_id" field. It's identical to AccountIDEQ.
func AccountID(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldAccountID, v))
}

// ProfileID applies equality check predicate on the "profile_id" field. It's identical to ProfileIDEQ.
func ProfileID(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldProfileID, v))
}

// SlotIndex applies equality check predicate on the "slot_index" field. It's identical to SlotIndexEQ.
func SlotIndex(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldSlotIndex, v))
}

// ProxyID applies equality check predicate on the "proxy_id" field. It's identical to ProxyIDEQ.
func ProxyID(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldProxyID, v))
}

// Epoch applies equality check predicate on the "epoch" field. It's identical to EpochEQ.
func Epoch(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldEpoch, v))
}

// State applies equality check predicate on the "state" field. It's identical to StateEQ.
func State(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldState, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldUpdatedAt, v))
}

// AccountIDEQ applies the EQ predicate on the "account_id" field.
func AccountIDEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldAccountID, v))
}

// AccountIDNEQ applies the NEQ predicate on the "account_id" field.
func AccountIDNEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldAccountID, v))
}

// AccountIDIn applies the In predicate on the "account_id" field.
func AccountIDIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldAccountID, vs...))
}

// AccountIDNotIn applies the NotIn predicate on the "account_id" field.
func AccountIDNotIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldAccountID, vs...))
}

// AccountIDGT applies the GT predicate on the "account_id" field.
func AccountIDGT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldAccountID, v))
}

// AccountIDGTE applies the GTE predicate on the "account_id" field.
func AccountIDGTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldAccountID, v))
}

// AccountIDLT applies the LT predicate on the "account_id" field.
func AccountIDLT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldAccountID, v))
}

// AccountIDLTE applies the LTE predicate on the "account_id" field.
func AccountIDLTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldAccountID, v))
}

// ProfileIDEQ applies the EQ predicate on the "profile_id" field.
func ProfileIDEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldProfileID, v))
}

// ProfileIDNEQ applies the NEQ predicate on the "profile_id" field.
func ProfileIDNEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldProfileID, v))
}

// ProfileIDIn applies the In predicate on the "profile_id" field.
func ProfileIDIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldProfileID, vs...))
}

// ProfileIDNotIn applies the NotIn predicate on the "profile_id" field.
func ProfileIDNotIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldProfileID, vs...))
}

// ProfileIDGT applies the GT predicate on the "profile_id" field.
func ProfileIDGT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldProfileID, v))
}

// ProfileIDGTE applies the GTE predicate on the "profile_id" field.
func ProfileIDGTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldProfileID, v))
}

// ProfileIDLT applies the LT predicate on the "profile_id" field.
func ProfileIDLT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldProfileID, v))
}

// ProfileIDLTE applies the LTE predicate on the "profile_id" field.
func ProfileIDLTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldProfileID, v))
}

// SlotIndexEQ applies the EQ predicate on the "slot_index" field.
func SlotIndexEQ(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldSlotIndex, v))
}

// SlotIndexNEQ applies the NEQ predicate on the "slot_index" field.
func SlotIndexNEQ(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldSlotIndex, v))
}

// SlotIndexIn applies the In predicate on the "slot_index" field.
func SlotIndexIn(vs ...int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldSlotIndex, vs...))
}

// SlotIndexNotIn applies the NotIn predicate on the "slot_index" field.
func SlotIndexNotIn(vs ...int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldSlotIndex, vs...))
}

// SlotIndexGT applies the GT predicate on the "slot_index" field.
func SlotIndexGT(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldSlotIndex, v))
}

// SlotIndexGTE applies the GTE predicate on the "slot_index" field.
func SlotIndexGTE(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldSlotIndex, v))
}

// SlotIndexLT applies the LT predicate on the "slot_index" field.
func SlotIndexLT(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldSlotIndex, v))
}

// SlotIndexLTE applies the LTE predicate on the "slot_index" field.
func SlotIndexLTE(v int) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldSlotIndex, v))
}

// ProxyIDEQ applies the EQ predicate on the "proxy_id" field.
func ProxyIDEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldProxyID, v))
}

// ProxyIDNEQ applies the NEQ predicate on the "proxy_id" field.
func ProxyIDNEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldProxyID, v))
}

// ProxyIDIn applies the In predicate on the "proxy_id" field.
func ProxyIDIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldProxyID, vs...))
}

// ProxyIDNotIn applies the NotIn predicate on the "proxy_id" field.
func ProxyIDNotIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldProxyID, vs...))
}

// ProxyIDGT applies the GT predicate on the "proxy_id" field.
func ProxyIDGT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldProxyID, v))
}

// ProxyIDGTE applies the GTE predicate on the "proxy_id" field.
func ProxyIDGTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldProxyID, v))
}

// ProxyIDLT applies the LT predicate on the "proxy_id" field.
func ProxyIDLT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldProxyID, v))
}

// ProxyIDLTE applies the LTE predicate on the "proxy_id" field.
func ProxyIDLTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldProxyID, v))
}

// ProxyIDIsNil applies the IsNil predicate on the "proxy_id" field.
func ProxyIDIsNil() predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIsNull(FieldProxyID))
}

// ProxyIDNotNil applies the NotNil predicate on the "proxy_id" field.
func ProxyIDNotNil() predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotNull(FieldProxyID))
}

// EpochEQ applies the EQ predicate on the "epoch" field.
func EpochEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldEpoch, v))
}

// EpochNEQ applies the NEQ predicate on the "epoch" field.
func EpochNEQ(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldEpoch, v))
}

// EpochIn applies the In predicate on the "epoch" field.
func EpochIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldEpoch, vs...))
}

// EpochNotIn applies the NotIn predicate on the "epoch" field.
func EpochNotIn(vs ...int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldEpoch, vs...))
}

// EpochGT applies the GT predicate on the "epoch" field.
func EpochGT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldEpoch, v))
}

// EpochGTE applies the GTE predicate on the "epoch" field.
func EpochGTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldEpoch, v))
}

// EpochLT applies the LT predicate on the "epoch" field.
func EpochLT(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldEpoch, v))
}

// EpochLTE applies the LTE predicate on the "epoch" field.
func EpochLTE(v int64) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldEpoch, v))
}

// StateEQ applies the EQ predicate on the "state" field.
func StateEQ(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldState, v))
}

// StateNEQ applies the NEQ predicate on the "state" field.
func StateNEQ(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldState, v))
}

// StateIn applies the In predicate on the "state" field.
func StateIn(vs ...string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldState, vs...))
}

// StateNotIn applies the NotIn predicate on the "state" field.
func StateNotIn(vs ...string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldState, vs...))
}

// StateGT applies the GT predicate on the "state" field.
func StateGT(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldState, v))
}

// StateGTE applies the GTE predicate on the "state" field.
func StateGTE(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldState, v))
}

// StateLT applies the LT predicate on the "state" field.
func StateLT(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldState, v))
}

// StateLTE applies the LTE predicate on the "state" field.
func StateLTE(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldState, v))
}

// StateContains applies the Contains predicate on the "state" field.
func StateContains(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldContains(FieldState, v))
}

// StateHasPrefix applies the HasPrefix predicate on the "state" field.
func StateHasPrefix(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldHasPrefix(FieldState, v))
}

// StateHasSuffix applies the HasSuffix predicate on the "state" field.
func StateHasSuffix(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldHasSuffix(FieldState, v))
}

// StateEqualFold applies the EqualFold predicate on the "state" field.
func StateEqualFold(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEqualFold(FieldState, v))
}

// StateContainsFold applies the ContainsFold predicate on the "state" field.
func StateContainsFold(v string) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldContainsFold(FieldState, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AccountCodexDeviceSlot) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AccountCodexDeviceSlot) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AccountCodexDeviceSlot) predicate.AccountCodexDeviceSlot {
	return predicate.AccountCodexDeviceSlot(sql.NotPredicates(p))
}
