param(
    [switch]$ForceDownload,
    [int]$Port = 8080,
    [int]$BackendPort = 18081,
    [string]$DatabaseHost = $(if ($env:SUB2API_DB_HOST) { $env:SUB2API_DB_HOST } else { "127.0.0.1" }),
    [int]$DatabasePort = $(if ($env:SUB2API_DB_PORT) { [int]$env:SUB2API_DB_PORT } else { 5432 }),
    [string]$DatabaseUser = $(if ($env:SUB2API_DB_USER) { $env:SUB2API_DB_USER } else { "postgres" }),
    [string]$DatabasePassword = $(if ($env:SUB2API_DB_PASSWORD) { $env:SUB2API_DB_PASSWORD } else { "" }),
    [string]$DatabaseName = $(if ($env:SUB2API_DB_NAME) { $env:SUB2API_DB_NAME } else { "sub2api" }),
    [string]$AdminEmail = $(if ($env:SUB2API_ADMIN_EMAIL) { $env:SUB2API_ADMIN_EMAIL } else { "admin@sub2api.local" }),
    [string]$AdminPassword = $(if ($env:SUB2API_ADMIN_PASSWORD) { $env:SUB2API_ADMIN_PASSWORD } else { "" })
)

$ErrorActionPreference = "Stop"

$Root = Split-Path -Parent $MyInvocation.MyCommand.Path
$Runtime = Join-Path $Root "runtime"
$Downloads = Join-Path $Runtime "downloads"
$Data = Join-Path $Runtime "data"
$SecretsFile = Join-Path $Data "local.secrets.env"
$RedisDir = Join-Path $Runtime "mini-redis"
$RedisScript = Join-Path $RedisDir "mini_redis.py"
$RedisPid = Join-Path $RedisDir "mini_redis.pid"
$AppPid = Join-Path $Runtime "sub2api.pid"
$FrontendPid = Join-Path $Runtime "admin_frontend.pid"
$FrontendServer = Join-Path $Root "admin_frontend_server.py"
$FrontendDir = Join-Path $Runtime "admin_frontend"
$Exe = Join-Path $Runtime "sub2api.exe"
$LogDir = Join-Path $Runtime "logs"
$AppOutLog = Join-Path $LogDir "sub2api.out.log"
$AppErrLog = Join-Path $LogDir "sub2api.err.log"
$FrontendOutLog = Join-Path $LogDir "admin_frontend.out.log"
$FrontendErrLog = Join-Path $LogDir "admin_frontend.err.log"
$RedisOutLog = Join-Path $LogDir "mini-redis.out.log"
$RedisErrLog = Join-Path $LogDir "mini-redis.err.log"
$script:ResolvedDatabaseName = $DatabaseName
$script:GeneratedAdminPassword = $null

function Write-Step($Message) {
    Write-Host "[Sub2API] $Message" -ForegroundColor Cyan
}

function Test-PESignature($Path) {
    if (-not (Test-Path $Path)) { return $false }

    try {
        $bytes = Get-Content $Path -Encoding Byte -TotalCount 2
        return ($bytes.Length -ge 2 -and $bytes[0] -eq 0x4D -and $bytes[1] -eq 0x5A)
    }
    catch {
        return $false
    }
}

function Get-HealthyBinaryCandidates {
    $candidates = @(
        $Exe,
        "$Exe.backup",
        (Join-Path $Downloads "extract\\sub2api.exe")
    )

    return $candidates | Where-Object { $_ -and (Test-PESignature $_) }
}

function New-RandomSecret([int]$Bytes = 32) {
    $buffer = New-Object byte[] $Bytes
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($buffer)
    }
    finally {
        $rng.Dispose()
    }
    return ([System.BitConverter]::ToString($buffer) -replace "-", "").ToLowerInvariant()
}

function Import-SecretsFile {
    if (-not (Test-Path $SecretsFile)) { return }

    Get-Content $SecretsFile | ForEach-Object {
        $line = $_.Trim()
        if (-not $line -or $line.StartsWith("#") -or -not $line.Contains("=")) { return }
        $parts = $line.Split("=", 2)
        $name = $parts[0].Trim()
        $value = $parts[1]
        if ($name -and -not [string]::IsNullOrWhiteSpace([Environment]::GetEnvironmentVariable($name, "Process"))) {
            return
        }
        if ($name) {
            [Environment]::SetEnvironmentVariable($name, $value, "Process")
        }
    }
}

function Save-SecretsFile {
    param(
        [string]$JwtSecret,
        [string]$TotpKey,
        [string]$AdminPasswordValue
    )

    $content = @(
        "# Generated by deploy/windows-lite/start.ps1 for local use only.",
        "# Do not commit this file.",
        "JWT_SECRET=$JwtSecret",
        "TOTP_ENCRYPTION_KEY=$TotpKey",
        "SUB2API_ADMIN_PASSWORD=$AdminPasswordValue"
    ) -join [Environment]::NewLine

    Set-Content -Path $SecretsFile -Value $content -Encoding UTF8
}

function Repair-ProcessPathEnvironment {
    $pathValue = [System.Environment]::GetEnvironmentVariable("Path", "Process")
    if (-not $pathValue) {
        $pathValue = [System.Environment]::GetEnvironmentVariable("PATH", "Process")
    }

    if ($pathValue) {
        [System.Environment]::SetEnvironmentVariable("PATH", $null, "Process")
        [System.Environment]::SetEnvironmentVariable("Path", $pathValue, "Process")
    }
}

function Hide-ProcessWindow($ProcessId) {
    if (-not $ProcessId) { return }

    if (-not ("NativeMethods" -as [type])) {
        Add-Type @"
using System;
using System.Runtime.InteropServices;

public static class NativeMethods {
    [DllImport("user32.dll")]
    public static extern bool ShowWindow(IntPtr hWnd, int nCmdShow);
}
"@
    }

    Start-Sleep -Milliseconds 300
    $proc = Get-Process -Id ([int]$ProcessId) -ErrorAction SilentlyContinue
    if ($proc -and $proc.MainWindowHandle -ne 0) {
        [NativeMethods]::ShowWindow($proc.MainWindowHandle, 0) | Out-Null
    }
}

function Hide-ExistingRuntimeWindows {
    Get-Process -Name "sub2api" -ErrorAction SilentlyContinue |
        ForEach-Object { Hide-ProcessWindow $_.Id }

    Get-CimInstance Win32_Process -Filter "Name = 'python.exe' OR Name = 'pythonw.exe'" -ErrorAction SilentlyContinue |
        Where-Object { $_.CommandLine -and ($_.CommandLine -like "*mini_redis.py*" -or $_.CommandLine -like "*$RedisScript*") } |
        ForEach-Object { Hide-ProcessWindow $_.ProcessId }
}

function Test-Port($HostName, $PortNumber) {
    $result = Test-NetConnection -ComputerName $HostName -Port $PortNumber -WarningAction SilentlyContinue
    return [bool]$result.TcpTestSucceeded
}

function Wait-Port($HostName, $PortNumber, $Seconds) {
    $deadline = (Get-Date).AddSeconds($Seconds)
    while ((Get-Date) -lt $deadline) {
        if (Test-Port $HostName $PortNumber) { return $true }
        Start-Sleep -Milliseconds 500
    }
    return $false
}

function Find-Python {
    $python = Get-Command python -ErrorAction SilentlyContinue
    if ($python) { return [pscustomobject]@{ File = $python.Source; Args = @() } }

    $python3 = Get-Command python3 -ErrorAction SilentlyContinue
    if ($python3) { return [pscustomobject]@{ File = $python3.Source; Args = @() } }

    $py = Get-Command py -ErrorAction SilentlyContinue
    if ($py) { return [pscustomobject]@{ File = $py.Source; Args = @("-3") } }

    return $null
}

function Download-LatestReleaseViaPython {
    $python = Find-Python
    if (-not $python) {
        throw "Python 3 was not found, so Python fallback download is unavailable."
    }

    $script = @"
import json
import os
import sys
import urllib.request

out_dir = sys.argv[1]
api = "https://api.github.com/repos/Wei-Shaw/sub2api/releases/latest"
headers = {"User-Agent": "Sub2API-windows-lite-start"}
req = urllib.request.Request(api, headers=headers)
with urllib.request.urlopen(req, timeout=20) as r:
    data = json.load(r)

asset = None
for item in data.get("assets", []):
    if item.get("name", "").endswith("windows_amd64.zip"):
        asset = item
        break

if asset is None:
    raise RuntimeError("No windows_amd64.zip release asset was found.")

zip_path = os.path.join(out_dir, asset["name"])
req = urllib.request.Request(asset["browser_download_url"], headers=headers)
with urllib.request.urlopen(req, timeout=120) as r, open(zip_path, "wb") as f:
    while True:
        chunk = r.read(1024 * 1024)
        if not chunk:
            break
        f.write(chunk)

print(zip_path)
"@

    $tempScript = Join-Path $Downloads "download_latest_release.py"
    Set-Content -Path $tempScript -Value $script -Encoding UTF8
    try {
        $args = @($python.Args) + @($tempScript, $Downloads)
        $zipPath = (& $python.File @args | Select-Object -Last 1).Trim()
        if (-not $zipPath -or -not (Test-Path $zipPath)) {
            throw "Python download did not produce a valid zip file."
        }
        return $zipPath
    }
    finally {
        Remove-Item $tempScript -Force -ErrorAction SilentlyContinue
    }
}

function Find-Psql {
    $cmd = Get-Command psql -ErrorAction SilentlyContinue
    if ($cmd) { return $cmd.Source }

    $candidates = @(
        "C:\Program Files\PostgreSQL\18\bin\psql.exe",
        "C:\Program Files\PostgreSQL\17\bin\psql.exe",
        "C:\Program Files\PostgreSQL\16\bin\psql.exe",
        "C:\Program Files\PostgreSQL\15\bin\psql.exe",
        "C:\Program Files\PostgreSQL\14\bin\psql.exe"
    )

    foreach ($candidate in $candidates) {
        if (Test-Path $candidate) { return $candidate }
    }

    return $null
}

function Stop-OldRuntime {
    if (Test-Path $AppPid) {
        $oldAppPid = Get-Content $AppPid -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($oldAppPid) {
            $oldApp = Get-Process -Id ([int]$oldAppPid) -ErrorAction SilentlyContinue
            if ($oldApp) {
                Write-Step "Stopping old Sub2API process: $oldAppPid"
                Stop-Process -Id ([int]$oldAppPid) -Force -ErrorAction SilentlyContinue
            }
        }
        Remove-Item $AppPid -Force -ErrorAction SilentlyContinue
    }

    if (Test-Path $FrontendPid) {
        $oldFrontendPid = Get-Content $FrontendPid -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($oldFrontendPid) {
            $oldFrontend = Get-Process -Id ([int]$oldFrontendPid) -ErrorAction SilentlyContinue
            if ($oldFrontend) {
                Write-Step "Stopping old admin frontend process: $oldFrontendPid"
                Stop-Process -Id ([int]$oldFrontendPid) -Force -ErrorAction SilentlyContinue
            }
        }
        Remove-Item $FrontendPid -Force -ErrorAction SilentlyContinue
    }

    if (Test-Path $RedisPid) {
        $oldRedisPid = Get-Content $RedisPid -ErrorAction SilentlyContinue | Select-Object -First 1
        if ($oldRedisPid) {
            $oldRedis = Get-Process -Id ([int]$oldRedisPid) -ErrorAction SilentlyContinue
            if ($oldRedis) {
                Write-Step "Stopping old mini Redis process: $oldRedisPid"
                Stop-Process -Id ([int]$oldRedisPid) -Force -ErrorAction SilentlyContinue
            }
        }
        Remove-Item $RedisPid -Force -ErrorAction SilentlyContinue
    }

    Get-Process -Name "sub2api" -ErrorAction SilentlyContinue |
        Where-Object { -not $_.Path -or $_.Path -eq $Exe } |
        Stop-Process -Force -ErrorAction SilentlyContinue

    Get-CimInstance Win32_Process -Filter "Name = 'python.exe' OR Name = 'pythonw.exe'" -ErrorAction SilentlyContinue |
        Where-Object { $_.CommandLine -and ($_.CommandLine -like "*mini_redis.py*" -or $_.CommandLine -like "*$RedisScript*" -or $_.CommandLine -like "*admin_frontend_server.py*" -or $_.CommandLine -like "*$FrontendServer*") } |
        ForEach-Object { Stop-Process -Id $_.ProcessId -Force -ErrorAction SilentlyContinue }
}

function Ensure-Dirs {
    New-Item -ItemType Directory -Force -Path $Runtime, $Downloads, $Data, $RedisDir, $LogDir | Out-Null
    if (-not (Test-Path $RedisScript)) {
        $bundledRedis = Join-Path $Root "mini-redis\mini_redis.py"
        if (Test-Path $bundledRedis) {
            Copy-Item -Force $bundledRedis $RedisScript
        }
    }
    if (-not (Test-Path $FrontendServer)) {
        throw "Missing admin frontend server: $FrontendServer"
    }
}

function Ensure-LocalSecrets {
    Import-SecretsFile

    if (-not $DatabasePassword) {
        if ($env:DATABASE_PASSWORD) {
            $script:DatabasePassword = $env:DATABASE_PASSWORD
        }
        else {
            throw "PostgreSQL password is required. Set SUB2API_DB_PASSWORD or pass -DatabasePassword."
        }
    }

    if (-not $AdminPassword) {
        if ($env:SUB2API_ADMIN_PASSWORD) {
            $script:AdminPassword = $env:SUB2API_ADMIN_PASSWORD
        }
        else {
            $script:AdminPassword = New-RandomSecret 12
            $script:GeneratedAdminPassword = $script:AdminPassword
        }
    }

    if (-not $env:JWT_SECRET) {
        $env:JWT_SECRET = New-RandomSecret 32
    }
    if (-not $env:TOTP_ENCRYPTION_KEY) {
        $env:TOTP_ENCRYPTION_KEY = New-RandomSecret 32
    }

    Save-SecretsFile -JwtSecret $env:JWT_SECRET -TotpKey $env:TOTP_ENCRYPTION_KEY -AdminPasswordValue $script:AdminPassword
}

function Ensure-Sub2API {
    if ((Test-Path $Exe) -and (Test-PESignature $Exe) -and -not $ForceDownload) {
        Write-Step "Using existing binary: $Exe"
        return
    }

    if ((Test-Path $Exe) -and -not (Test-PESignature $Exe)) {
        Write-Step "Detected invalid binary at $Exe. It looks like a ZIP file or corrupted download."
    }

    $healthyCandidates = Get-HealthyBinaryCandidates
    if ($healthyCandidates.Count -gt 0 -and -not $ForceDownload) {
        $source = $healthyCandidates | Select-Object -First 1
        if ($source -ne $Exe) {
            Write-Step "Restoring working binary from: $source"
            Copy-Item -Force $source $Exe
        }
        Write-Step "Binary ready: $Exe"
        return
    }

    Write-Step "Downloading latest Windows release..."
    try {
        $zip = $null
        try {
            $release = Invoke-RestMethod -Uri "https://api.github.com/repos/Wei-Shaw/sub2api/releases/latest" -Headers @{ "User-Agent" = "Sub2API-windows-lite-start" }
            $asset = $release.assets | Where-Object { $_.name -match "windows_amd64\.zip$" } | Select-Object -First 1
            if (-not $asset) {
                throw "No windows_amd64.zip release asset was found."
            }
            $zip = Join-Path $Downloads $asset.name
            Invoke-WebRequest -Uri $asset.browser_download_url -OutFile $zip -Headers @{ "User-Agent" = "Sub2API-windows-lite-start" }
        }
        catch {
            Write-Warning "PowerShell download failed, retrying with Python. Reason: $($_.Exception.Message)"
            $zip = Download-LatestReleaseViaPython
        }

        $extractDir = Join-Path $Downloads "extract"
        if (Test-Path $extractDir) { Remove-Item -Recurse -Force $extractDir }
        New-Item -ItemType Directory -Force -Path $extractDir | Out-Null
        Expand-Archive -Path $zip -DestinationPath $extractDir -Force

        $found = Get-ChildItem -Path $extractDir -Recurse -Filter "sub2api.exe" |
            Where-Object { Test-PESignature $_.FullName } |
            Select-Object -First 1
        if (-not $found) {
            throw "sub2api.exe was not found in the release zip."
        }

        Copy-Item -Force $found.FullName $Exe
        Copy-Item -Force $found.FullName "$Exe.backup"
        Write-Step "Binary ready: $Exe"
        return
    }
    catch {
        $healthyCandidates = Get-HealthyBinaryCandidates
        if ($healthyCandidates.Count -gt 0) {
            $source = $healthyCandidates | Select-Object -First 1
            Write-Warning "Latest release download failed: $($_.Exception.Message)"
            if ($source -ne $Exe) {
                Write-Step "Falling back to local working binary: $source"
                Copy-Item -Force $source $Exe
            }
            Write-Step "Binary ready: $Exe"
            return
        }

        throw
    }
}

function Ensure-Postgres {
    if (-not (Test-Port $DatabaseHost $DatabasePort)) {
        throw "PostgreSQL is not running on ${DatabaseHost}:$DatabasePort. Install/start PostgreSQL first. This package does not use Docker."
    }

    Write-Step "PostgreSQL reachable: ${DatabaseHost}:$DatabasePort"

    $psql = Find-Psql
    if (-not $psql) {
        Write-Warning "psql was not found. The app will use database '$DatabaseName' as configured."
        $script:ResolvedDatabaseName = $DatabaseName
        return
    }

    $env:PGPASSWORD = $DatabasePassword
    try {
        $exists = & $psql -h $DatabaseHost -p $DatabasePort -U $DatabaseUser -d postgres -tAc "SELECT 1 FROM pg_database WHERE datname='$DatabaseName';"
        if (($exists | Out-String).Trim() -ne "1") {
            Write-Step "Creating database: $DatabaseName"
            & $psql -h $DatabaseHost -p $DatabasePort -U $DatabaseUser -d postgres -c "CREATE DATABASE $DatabaseName;" | Out-Null
        }
        $script:ResolvedDatabaseName = $DatabaseName
    }
    catch {
        Write-Warning "Could not create/use database '$DatabaseName'. Falling back to database 'postgres'. Reason: $($_.Exception.Message)"
        $script:ResolvedDatabaseName = "postgres"
    }
    finally {
        Remove-Item Env:\PGPASSWORD -ErrorAction SilentlyContinue
    }
}

function Clear-StaleLeaderLocks {
    # After hard process kills, mini-redis may still hold leader locks from a
    # previous instance. Clear only lock keys so the new process can become leader.
    try {
        $python = Find-Python
        if (-not $python) { return }

        $script = @"
import socket
import sys

def cmd(*parts):
    buf = ('*%d\r\n' % len(parts)).encode()
    for p in parts:
        b = p if isinstance(p, bytes) else str(p).encode()
        buf += ('$%d\r\n' % len(b)).encode() + b + b'\r\n'
    s = socket.create_connection(('127.0.0.1', 6379), 1.5)
    s.sendall(buf)
    s.settimeout(1.0)
    data = b''
    try:
        while True:
            chunk = s.recv(65536)
            if not chunk:
                break
            data += chunk
            if len(data) > 200000:
                break
    except Exception:
        pass
    s.close()
    return data

def parse_keys(raw):
    if not raw.startswith(b'*'):
        return []
    parts = raw.split(b'\r\n')
    keys = []
    i = 1
    while i < len(parts):
        line = parts[i]
        if line.startswith(b'$'):
            i += 1
            if i < len(parts) and parts[i]:
                keys.append(parts[i].decode(errors='ignore'))
        i += 1
    return keys

try:
    raw = cmd('KEYS', '*')
except Exception as exc:
    print('skip: %s' % exc)
    sys.exit(0)

keys = parse_keys(raw)
targets = [k for k in keys if (
    k.startswith('leader:lock:') or
    k.endswith(':leader') or
    (':leader' in k and k.startswith('ops:'))
)]
if not targets:
    print('no-stale-locks')
    sys.exit(0)
cmd('DEL', *targets)
print('cleared=%d' % len(targets))
"@
        $tempScript = Join-Path $LogDir "clear_stale_leader_locks.py"
        Set-Content -Path $tempScript -Value $script -Encoding UTF8
        try {
            $args = @($python.Args) + @($tempScript)
            $result = (& $python.File @args 2>&1 | Select-Object -Last 1)
            if ($result -and ($result -like "cleared=*")) {
                Write-Step "Cleared stale Redis leader locks: $result"
            }
        }
        finally {
            Remove-Item $tempScript -Force -ErrorAction SilentlyContinue
        }
    }
    catch {
        Write-Warning "Could not clear stale Redis leader locks: $($_.Exception.Message)"
    }
}

function Start-MiniRedis {
    Repair-ProcessPathEnvironment

    if (Test-Port "127.0.0.1" 6379) {
        Write-Step "Redis-compatible service reachable: 127.0.0.1:6379"
        Clear-StaleLeaderLocks
        Hide-ExistingRuntimeWindows
        return
    }

    if (-not (Test-Path $RedisScript)) {
        throw "Missing mini Redis script: $RedisScript"
    }

    $python = Find-Python
    if (-not $python) {
        throw "Python 3 was not found. Install Python 3 or start any Redis-compatible service on 127.0.0.1:6379."
    }

    Write-Step "Starting lightweight Python Redis-compatible service..."
    $redisArgs = @($python.Args) + @($RedisScript)
    $proc = Start-Process -FilePath $python.File -ArgumentList $redisArgs -WorkingDirectory $RedisDir -PassThru -WindowStyle Hidden -RedirectStandardOutput $RedisOutLog -RedirectStandardError $RedisErrLog
    Hide-ProcessWindow $proc.Id
    Set-Content -Path $RedisPid -Value $proc.Id -Encoding ASCII

    if (-not (Wait-Port "127.0.0.1" 6379 10)) {
        $err = ""
        if (Test-Path $RedisErrLog) { $err = Get-Content $RedisErrLog -Tail 20 | Out-String }
        throw "Mini Redis failed to start. $err"
    }

    Write-Step "Mini Redis is ready."
    Clear-StaleLeaderLocks
}

function Write-LocalConfigIfMissing {
    $config = Join-Path $Data "config.yaml"
    if (Test-Path $config) {
        Write-Step "Using existing config: $config"
        return
    }

    Write-Step "Writing initial local config: $config"
    $configText = @"
server:
    host: 0.0.0.0
    port: $BackendPort
    mode: release
database:
    host: $DatabaseHost
    port: $DatabasePort
    user: $DatabaseUser
    password: $DatabasePassword
    dbname: $($script:ResolvedDatabaseName)
    sslmode: disable
redis:
    host: 127.0.0.1
    port: 6379
    password: ""
    db: 0
    enable_tls: false
cors:
    allowed_origins:
        - "*"
    allow_credentials: false
jwt:
    secret: $($env:JWT_SECRET)
    expire_hour: 24
default:
    user_concurrency: 5
    user_balance: 0
    api_key_prefix: sk-
    rate_multiplier: 1
rate_limit:
    requests_per_minute: 60
    burst_size: 10
timezone: UTC
"@
    Set-Content -Path $config -Value $configText -Encoding UTF8
}

function Set-AppEnvironment {
    $env:DATA_DIR = $Data
    $env:AUTO_SETUP = "true"
    $env:TZ = "UTC"
    $env:RUN_MODE = "standard"
    $env:SERVER_HOST = "0.0.0.0"
    $env:SERVER_PORT = "$BackendPort"
    $env:SERVER_MODE = "release"
    $env:DATABASE_HOST = $DatabaseHost
    $env:DATABASE_PORT = "$DatabasePort"
    $env:DATABASE_USER = $DatabaseUser
    $env:DATABASE_PASSWORD = $DatabasePassword
    $env:DATABASE_DBNAME = $script:ResolvedDatabaseName
    $env:DATABASE_SSLMODE = "disable"
    $env:REDIS_HOST = "127.0.0.1"
    $env:REDIS_PORT = "6379"
    $env:REDIS_PASSWORD = ""
    $env:REDIS_DB = "0"
    $env:REDIS_ENABLE_TLS = "false"
    $env:CORS_ALLOWED_ORIGINS = "*"
    $env:CORS_ALLOW_CREDENTIALS = "false"
    $env:ADMIN_EMAIL = $AdminEmail
    $env:ADMIN_PASSWORD = $AdminPassword
    $env:JWT_EXPIRE_HOUR = "24"
}

function Start-AppOnce {
    Write-Step "Starting Sub2API background process..."
    Repair-ProcessPathEnvironment
    $proc = Start-Process -FilePath $Exe -WorkingDirectory $Runtime -PassThru -WindowStyle Hidden -RedirectStandardOutput $AppOutLog -RedirectStandardError $AppErrLog
    Hide-ProcessWindow $proc.Id
    Set-Content -Path $AppPid -Value $proc.Id -Encoding ASCII
    return $proc
}

function Ensure-AppStarted {
    $proc = Start-AppOnce

    $deadline = (Get-Date).AddSeconds(25)
    while ((Get-Date) -lt $deadline) {
        if (Test-Port "127.0.0.1" $BackendPort) {
            Write-Step "Sub2API is running. PID=$($proc.Id)"
            return
        }

        $proc.Refresh()
        if ($proc.HasExited) {
            Write-Step "Sub2API exited once, retrying after auto-setup..."
            Start-Sleep -Seconds 2
            $proc = Start-AppOnce
        }

        Start-Sleep -Milliseconds 500
    }

    $out = ""
    $err = ""
    if (Test-Path $AppOutLog) { $out = Get-Content $AppOutLog -Tail 80 | Out-String }
    if (Test-Path $AppErrLog) { $err = Get-Content $AppErrLog -Tail 80 | Out-String }
    throw "Sub2API did not open port $BackendPort. STDOUT: $out STDERR: $err"
}

function Start-AdminFrontend {
    if (-not (Test-Path $FrontendServer)) {
        throw "Missing admin frontend server: $FrontendServer"
    }
    if (-not (Test-Path (Join-Path $FrontendDir "index.html"))) {
        Write-Warning "Admin frontend static files were not found at $FrontendDir."
        Write-Warning "If your release package embeds the admin UI in sub2api.exe, you can open http://127.0.0.1:$BackendPort instead."
        return
    }

    $python = Find-Python
    if (-not $python) {
        throw "Python 3 was not found. It is required to serve the admin frontend on port $Port."
    }

    Write-Step "Starting admin frontend on port $Port, proxying API to $BackendPort..."
    $frontendArgs = @($python.Args) + @(
        $FrontendServer,
        "--host", "0.0.0.0",
        "--port", "$Port",
        "--upstream-host", "127.0.0.1",
        "--upstream-port", "$BackendPort",
        "--frontend-dir", $FrontendDir
    )
    $proc = Start-Process -FilePath $python.File -ArgumentList $frontendArgs -WorkingDirectory $Runtime -PassThru -WindowStyle Hidden -RedirectStandardOutput $FrontendOutLog -RedirectStandardError $FrontendErrLog
    Hide-ProcessWindow $proc.Id
    Set-Content -Path $FrontendPid -Value $proc.Id -Encoding ASCII

    if (-not (Wait-Port "127.0.0.1" $Port 10)) {
        $err = ""
        if (Test-Path $FrontendErrLog) { $err = Get-Content $FrontendErrLog -Tail 40 | Out-String }
        throw "Admin frontend did not open port $Port. $err"
    }

    Write-Step "Admin frontend is running. PID=$($proc.Id)"
}

Ensure-Dirs
Ensure-LocalSecrets
Hide-ExistingRuntimeWindows
Stop-OldRuntime
Ensure-Sub2API
Ensure-Postgres
Start-MiniRedis
Write-LocalConfigIfMissing
Set-AppEnvironment
Ensure-AppStarted
Start-AdminFrontend

Write-Host ""
Write-Host "Started successfully: http://localhost:$Port" -ForegroundColor Green
Write-Host "Admin email: $AdminEmail" -ForegroundColor Green
if ($script:GeneratedAdminPassword) {
    Write-Host "Generated admin password: $($script:GeneratedAdminPassword)" -ForegroundColor Yellow
    Write-Host "Password saved to: $SecretsFile" -ForegroundColor Yellow
}
else {
    Write-Host "Admin password: (from SUB2API_ADMIN_PASSWORD / secrets file)" -ForegroundColor Green
}
Write-Host "Logs: $AppOutLog, $AppErrLog, $FrontendOutLog and $FrontendErrLog" -ForegroundColor Yellow
Write-Host "Stop: powershell -NoProfile -ExecutionPolicy Bypass -File .\stop.ps1" -ForegroundColor Yellow
