ALTER TABLE prompt_records
    ADD COLUMN IF NOT EXISTS response_text TEXT NOT NULL DEFAULT '',
    ADD COLUMN IF NOT EXISTS response_length INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS response_truncated BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS response_captured_at TIMESTAMPTZ;

