// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountcodexidentitypolicy"
)

// AccountCodexIdentityPolicy is the model entity for the AccountCodexIdentityPolicy schema.
type AccountCodexIdentityPolicy struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// Mode holds the value of the "mode" field.
	Mode string `json:"mode,omitempty"`
	// BindingScope holds the value of the "binding_scope" field.
	BindingScope string `json:"binding_scope,omitempty"`
	// SessionPolicy holds the value of the "session_policy" field.
	SessionPolicy map[string]interface{} `json:"session_policy,omitempty"`
	// AffinityTTLSeconds holds the value of the "affinity_ttl_seconds" field.
	AffinityTTLSeconds int `json:"affinity_ttl_seconds,omitempty"`
	// UnsupportedPolicy holds the value of the "unsupported_policy" field.
	UnsupportedPolicy string `json:"unsupported_policy,omitempty"`
	// Version holds the value of the "version" field.
	Version int64 `json:"version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountCodexIdentityPolicy) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountcodexidentitypolicy.FieldSessionPolicy:
			values[i] = new([]byte)
		case accountcodexidentitypolicy.FieldID, accountcodexidentitypolicy.FieldAccountID, accountcodexidentitypolicy.FieldAffinityTTLSeconds, accountcodexidentitypolicy.FieldVersion:
			values[i] = new(sql.NullInt64)
		case accountcodexidentitypolicy.FieldMode, accountcodexidentitypolicy.FieldBindingScope, accountcodexidentitypolicy.FieldUnsupportedPolicy:
			values[i] = new(sql.NullString)
		case accountcodexidentitypolicy.FieldCreatedAt, accountcodexidentitypolicy.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountCodexIdentityPolicy fields.
func (_m *AccountCodexIdentityPolicy) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountcodexidentitypolicy.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountcodexidentitypolicy.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountcodexidentitypolicy.FieldMode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field mode", values[i])
			} else if value.Valid {
				_m.Mode = value.String
			}
		case accountcodexidentitypolicy.FieldBindingScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field binding_scope", values[i])
			} else if value.Valid {
				_m.BindingScope = value.String
			}
		case accountcodexidentitypolicy.FieldSessionPolicy:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field session_policy", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SessionPolicy); err != nil {
					return fmt.Errorf("unmarshal field session_policy: %w", err)
				}
			}
		case accountcodexidentitypolicy.FieldAffinityTTLSeconds:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field affinity_ttl_seconds", values[i])
			} else if value.Valid {
				_m.AffinityTTLSeconds = int(value.Int64)
			}
		case accountcodexidentitypolicy.FieldUnsupportedPolicy:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field unsupported_policy", values[i])
			} else if value.Valid {
				_m.UnsupportedPolicy = value.String
			}
		case accountcodexidentitypolicy.FieldVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field version", values[i])
			} else if value.Valid {
				_m.Version = value.Int64
			}
		case accountcodexidentitypolicy.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountcodexidentitypolicy.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountCodexIdentityPolicy.
// This includes values selected through modifiers, order, etc.
func (_m *AccountCodexIdentityPolicy) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountCodexIdentityPolicy.
// Note that you need to call AccountCodexIdentityPolicy.Unwrap() before calling this method if this AccountCodexIdentityPolicy
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountCodexIdentityPolicy) Update() *AccountCodexIdentityPolicyUpdateOne {
	return NewAccountCodexIdentityPolicyClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountCodexIdentityPolicy entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountCodexIdentityPolicy) Unwrap() *AccountCodexIdentityPolicy {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountCodexIdentityPolicy is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountCodexIdentityPolicy) String() string {
	var builder strings.Builder
	builder.WriteString("AccountCodexIdentityPolicy(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("mode=")
	builder.WriteString(_m.Mode)
	builder.WriteString(", ")
	builder.WriteString("binding_scope=")
	builder.WriteString(_m.BindingScope)
	builder.WriteString(", ")
	builder.WriteString("session_policy=")
	builder.WriteString(fmt.Sprintf("%v", _m.SessionPolicy))
	builder.WriteString(", ")
	builder.WriteString("affinity_ttl_seconds=")
	builder.WriteString(fmt.Sprintf("%v", _m.AffinityTTLSeconds))
	builder.WriteString(", ")
	builder.WriteString("unsupported_policy=")
	builder.WriteString(_m.UnsupportedPolicy)
	builder.WriteString(", ")
	builder.WriteString("version=")
	builder.WriteString(fmt.Sprintf("%v", _m.Version))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountCodexIdentityPolicies is a parsable slice of AccountCodexIdentityPolicy.
type AccountCodexIdentityPolicies []*AccountCodexIdentityPolicy
