// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/accountcodexidentitypolicy"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// AccountCodexIdentityPolicyUpdate is the builder for updating AccountCodexIdentityPolicy entities.
type AccountCodexIdentityPolicyUpdate struct {
	config
	hooks    []Hook
	mutation *AccountCodexIdentityPolicyMutation
}

// Where appends a list predicates to the AccountCodexIdentityPolicyUpdate builder.
func (_u *AccountCodexIdentityPolicyUpdate) Where(ps ...predicate.AccountCodexIdentityPolicy) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetAccountID(v int64) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableAccountID(v *int64) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCodexIdentityPolicyUpdate) AddAccountID(v int64) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetMode(v string) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableMode(v *string) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetBindingScope sets the "binding_scope" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetBindingScope(v string) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.SetBindingScope(v)
	return _u
}

// SetNillableBindingScope sets the "binding_scope" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableBindingScope(v *string) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetBindingScope(*v)
	}
	return _u
}

// SetSessionPolicy sets the "session_policy" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetSessionPolicy(v map[string]interface{}) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.SetSessionPolicy(v)
	return _u
}

// SetAffinityTTLSeconds sets the "affinity_ttl_seconds" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetAffinityTTLSeconds(v int) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.ResetAffinityTTLSeconds()
	_u.mutation.SetAffinityTTLSeconds(v)
	return _u
}

// SetNillableAffinityTTLSeconds sets the "affinity_ttl_seconds" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableAffinityTTLSeconds(v *int) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetAffinityTTLSeconds(*v)
	}
	return _u
}

// AddAffinityTTLSeconds adds value to the "affinity_ttl_seconds" field.
func (_u *AccountCodexIdentityPolicyUpdate) AddAffinityTTLSeconds(v int) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.AddAffinityTTLSeconds(v)
	return _u
}

// SetUnsupportedPolicy sets the "unsupported_policy" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetUnsupportedPolicy(v string) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.SetUnsupportedPolicy(v)
	return _u
}

// SetNillableUnsupportedPolicy sets the "unsupported_policy" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableUnsupportedPolicy(v *string) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetUnsupportedPolicy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetVersion(v int64) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdate) SetNillableVersion(v *int64) *AccountCodexIdentityPolicyUpdate {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountCodexIdentityPolicyUpdate) AddVersion(v int64) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCodexIdentityPolicyUpdate) SetUpdatedAt(v time.Time) *AccountCodexIdentityPolicyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountCodexIdentityPolicyMutation object of the builder.
func (_u *AccountCodexIdentityPolicyUpdate) Mutation() *AccountCodexIdentityPolicyMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AccountCodexIdentityPolicyUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCodexIdentityPolicyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AccountCodexIdentityPolicyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCodexIdentityPolicyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCodexIdentityPolicyUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcodexidentitypolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCodexIdentityPolicyUpdate) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := accountcodexidentitypolicy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingScope(); ok {
		if err := accountcodexidentitypolicy.BindingScopeValidator(v); err != nil {
			return &ValidationError{Name: "binding_scope", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.binding_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnsupportedPolicy(); ok {
		if err := accountcodexidentitypolicy.UnsupportedPolicyValidator(v); err != nil {
			return &ValidationError{Name: "unsupported_policy", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.unsupported_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCodexIdentityPolicyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcodexidentitypolicy.Table, accountcodexidentitypolicy.Columns, sqlgraph.NewFieldSpec(accountcodexidentitypolicy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingScope(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldBindingScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionPolicy(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldSessionPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AffinityTTLSeconds(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldAffinityTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffinityTTLSeconds(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldAffinityTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnsupportedPolicy(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldUnsupportedPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcodexidentitypolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AccountCodexIdentityPolicyUpdateOne is the builder for updating a single AccountCodexIdentityPolicy entity.
type AccountCodexIdentityPolicyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AccountCodexIdentityPolicyMutation
}

// SetAccountID sets the "account_id" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetAccountID(v int64) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.ResetAccountID()
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableAccountID(v *int64) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// AddAccountID adds value to the "account_id" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) AddAccountID(v int64) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.AddAccountID(v)
	return _u
}

// SetMode sets the "mode" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetMode(v string) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.SetMode(v)
	return _u
}

// SetNillableMode sets the "mode" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableMode(v *string) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetMode(*v)
	}
	return _u
}

// SetBindingScope sets the "binding_scope" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetBindingScope(v string) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.SetBindingScope(v)
	return _u
}

// SetNillableBindingScope sets the "binding_scope" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableBindingScope(v *string) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetBindingScope(*v)
	}
	return _u
}

// SetSessionPolicy sets the "session_policy" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetSessionPolicy(v map[string]interface{}) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.SetSessionPolicy(v)
	return _u
}

// SetAffinityTTLSeconds sets the "affinity_ttl_seconds" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetAffinityTTLSeconds(v int) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.ResetAffinityTTLSeconds()
	_u.mutation.SetAffinityTTLSeconds(v)
	return _u
}

// SetNillableAffinityTTLSeconds sets the "affinity_ttl_seconds" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableAffinityTTLSeconds(v *int) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetAffinityTTLSeconds(*v)
	}
	return _u
}

// AddAffinityTTLSeconds adds value to the "affinity_ttl_seconds" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) AddAffinityTTLSeconds(v int) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.AddAffinityTTLSeconds(v)
	return _u
}

// SetUnsupportedPolicy sets the "unsupported_policy" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetUnsupportedPolicy(v string) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.SetUnsupportedPolicy(v)
	return _u
}

// SetNillableUnsupportedPolicy sets the "unsupported_policy" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableUnsupportedPolicy(v *string) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetUnsupportedPolicy(*v)
	}
	return _u
}

// SetVersion sets the "version" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetVersion(v int64) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.ResetVersion()
	_u.mutation.SetVersion(v)
	return _u
}

// SetNillableVersion sets the "version" field if the given value is not nil.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetNillableVersion(v *int64) *AccountCodexIdentityPolicyUpdateOne {
	if v != nil {
		_u.SetVersion(*v)
	}
	return _u
}

// AddVersion adds value to the "version" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) AddVersion(v int64) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.AddVersion(v)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AccountCodexIdentityPolicyUpdateOne) SetUpdatedAt(v time.Time) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the AccountCodexIdentityPolicyMutation object of the builder.
func (_u *AccountCodexIdentityPolicyUpdateOne) Mutation() *AccountCodexIdentityPolicyMutation {
	return _u.mutation
}

// Where appends a list predicates to the AccountCodexIdentityPolicyUpdate builder.
func (_u *AccountCodexIdentityPolicyUpdateOne) Where(ps ...predicate.AccountCodexIdentityPolicy) *AccountCodexIdentityPolicyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AccountCodexIdentityPolicyUpdateOne) Select(field string, fields ...string) *AccountCodexIdentityPolicyUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AccountCodexIdentityPolicy entity.
func (_u *AccountCodexIdentityPolicyUpdateOne) Save(ctx context.Context) (*AccountCodexIdentityPolicy, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AccountCodexIdentityPolicyUpdateOne) SaveX(ctx context.Context) *AccountCodexIdentityPolicy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AccountCodexIdentityPolicyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AccountCodexIdentityPolicyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AccountCodexIdentityPolicyUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := accountcodexidentitypolicy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AccountCodexIdentityPolicyUpdateOne) check() error {
	if v, ok := _u.mutation.Mode(); ok {
		if err := accountcodexidentitypolicy.ModeValidator(v); err != nil {
			return &ValidationError{Name: "mode", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.mode": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BindingScope(); ok {
		if err := accountcodexidentitypolicy.BindingScopeValidator(v); err != nil {
			return &ValidationError{Name: "binding_scope", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.binding_scope": %w`, err)}
		}
	}
	if v, ok := _u.mutation.UnsupportedPolicy(); ok {
		if err := accountcodexidentitypolicy.UnsupportedPolicyValidator(v); err != nil {
			return &ValidationError{Name: "unsupported_policy", err: fmt.Errorf(`ent: validator failed for field "AccountCodexIdentityPolicy.unsupported_policy": %w`, err)}
		}
	}
	return nil
}

func (_u *AccountCodexIdentityPolicyUpdateOne) sqlSave(ctx context.Context) (_node *AccountCodexIdentityPolicy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(accountcodexidentitypolicy.Table, accountcodexidentitypolicy.Columns, sqlgraph.NewFieldSpec(accountcodexidentitypolicy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AccountCodexIdentityPolicy.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, accountcodexidentitypolicy.FieldID)
		for _, f := range fields {
			if !accountcodexidentitypolicy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != accountcodexidentitypolicy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.AccountID(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedAccountID(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldAccountID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Mode(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.BindingScope(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldBindingScope, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionPolicy(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldSessionPolicy, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AffinityTTLSeconds(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldAffinityTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffinityTTLSeconds(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldAffinityTTLSeconds, field.TypeInt, value)
	}
	if value, ok := _u.mutation.UnsupportedPolicy(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldUnsupportedPolicy, field.TypeString, value)
	}
	if value, ok := _u.mutation.Version(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedVersion(); ok {
		_spec.AddField(accountcodexidentitypolicy.FieldVersion, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(accountcodexidentitypolicy.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &AccountCodexIdentityPolicy{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{accountcodexidentitypolicy.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
