// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/accountcodexdevicebinding"
)

// AccountCodexDeviceBinding is the model entity for the AccountCodexDeviceBinding schema.
type AccountCodexDeviceBinding struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// AccountID holds the value of the "account_id" field.
	AccountID int64 `json:"account_id,omitempty"`
	// APIKeyID holds the value of the "api_key_id" field.
	APIKeyID int64 `json:"api_key_id,omitempty"`
	// OsClass holds the value of the "os_class" field.
	OsClass string `json:"os_class,omitempty"`
	// SlotID holds the value of the "slot_id" field.
	SlotID int64 `json:"slot_id,omitempty"`
	// PolicyVersion holds the value of the "policy_version" field.
	PolicyVersion int64 `json:"policy_version,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AccountCodexDeviceBinding) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case accountcodexdevicebinding.FieldID, accountcodexdevicebinding.FieldAccountID, accountcodexdevicebinding.FieldAPIKeyID, accountcodexdevicebinding.FieldSlotID, accountcodexdevicebinding.FieldPolicyVersion:
			values[i] = new(sql.NullInt64)
		case accountcodexdevicebinding.FieldOsClass:
			values[i] = new(sql.NullString)
		case accountcodexdevicebinding.FieldCreatedAt, accountcodexdevicebinding.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AccountCodexDeviceBinding fields.
func (_m *AccountCodexDeviceBinding) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case accountcodexdevicebinding.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case accountcodexdevicebinding.FieldAccountID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field account_id", values[i])
			} else if value.Valid {
				_m.AccountID = value.Int64
			}
		case accountcodexdevicebinding.FieldAPIKeyID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field api_key_id", values[i])
			} else if value.Valid {
				_m.APIKeyID = value.Int64
			}
		case accountcodexdevicebinding.FieldOsClass:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field os_class", values[i])
			} else if value.Valid {
				_m.OsClass = value.String
			}
		case accountcodexdevicebinding.FieldSlotID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field slot_id", values[i])
			} else if value.Valid {
				_m.SlotID = value.Int64
			}
		case accountcodexdevicebinding.FieldPolicyVersion:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field policy_version", values[i])
			} else if value.Valid {
				_m.PolicyVersion = value.Int64
			}
		case accountcodexdevicebinding.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case accountcodexdevicebinding.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AccountCodexDeviceBinding.
// This includes values selected through modifiers, order, etc.
func (_m *AccountCodexDeviceBinding) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this AccountCodexDeviceBinding.
// Note that you need to call AccountCodexDeviceBinding.Unwrap() before calling this method if this AccountCodexDeviceBinding
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AccountCodexDeviceBinding) Update() *AccountCodexDeviceBindingUpdateOne {
	return NewAccountCodexDeviceBindingClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AccountCodexDeviceBinding entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AccountCodexDeviceBinding) Unwrap() *AccountCodexDeviceBinding {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AccountCodexDeviceBinding is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AccountCodexDeviceBinding) String() string {
	var builder strings.Builder
	builder.WriteString("AccountCodexDeviceBinding(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("account_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.AccountID))
	builder.WriteString(", ")
	builder.WriteString("api_key_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.APIKeyID))
	builder.WriteString(", ")
	builder.WriteString("os_class=")
	builder.WriteString(_m.OsClass)
	builder.WriteString(", ")
	builder.WriteString("slot_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SlotID))
	builder.WriteString(", ")
	builder.WriteString("policy_version=")
	builder.WriteString(fmt.Sprintf("%v", _m.PolicyVersion))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// AccountCodexDeviceBindings is a parsable slice of AccountCodexDeviceBinding.
type AccountCodexDeviceBindings []*AccountCodexDeviceBinding
