// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/authidentity"
	"github.com/Wei-Shaw/sub2api/ent/authidentitychannel"
	"github.com/Wei-Shaw/sub2api/ent/identityadoptiondecision"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// AuthIdentityUpdate is the builder for updating AuthIdentity entities.
type AuthIdentityUpdate struct {
	config
	hooks    []Hook
	mutation *AuthIdentityMutation
REDACTED

// Where appends a list predicates to the AuthIdentityUpdate builder.
func (_u *AuthIdentityUpdate) Where(ps ...predicate.AuthIdentity) *AuthIdentityUpdate {
	_u.mutation.Where(ps...)
	return _u
REDACTED

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthIdentityUpdate) SetUpdatedAt(v time.Time) *AuthIdentityUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
REDACTED

// SetUserID sets the "user_id" field.
func (_u *AuthIdentityUpdate) SetUserID(v int64) *AuthIdentityUpdate {
	_u.mutation.SetUserID(v)
	return _u
REDACTED

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableUserID(v *int64) *AuthIdentityUpdate {
	if v != nil {
		_u.SetUserID(*v)
REDACTED
	return _u
REDACTED

// SetProviderType sets the "provider_type" field.
func (_u *AuthIdentityUpdate) SetProviderType(v string) *AuthIdentityUpdate {
	_u.mutation.SetProviderType(v)
	return _u
REDACTED

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableProviderType(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetProviderType(*v)
REDACTED
	return _u
REDACTED

// SetProviderKey sets the "provider_key" field.
func (_u *AuthIdentityUpdate) SetProviderKey(v string) *AuthIdentityUpdate {
	_u.mutation.SetProviderKey(v)
	return _u
REDACTED

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableProviderKey(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetProviderKey(*v)
REDACTED
	return _u
REDACTED

// SetProviderSubject sets the "provider_subject" field.
func (_u *AuthIdentityUpdate) SetProviderSubject(v string) *AuthIdentityUpdate {
	_u.mutation.SetProviderSubject(v)
	return _u
REDACTED

// SetNillableProviderSubject sets the "provider_subject" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableProviderSubject(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetProviderSubject(*v)
REDACTED
	return _u
REDACTED

// SetVerifiedAt sets the "verified_at" field.
func (_u *AuthIdentityUpdate) SetVerifiedAt(v time.Time) *AuthIdentityUpdate {
	_u.mutation.SetVerifiedAt(v)
	return _u
REDACTED

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableVerifiedAt(v *time.Time) *AuthIdentityUpdate {
	if v != nil {
		_u.SetVerifiedAt(*v)
REDACTED
	return _u
REDACTED

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *AuthIdentityUpdate) ClearVerifiedAt() *AuthIdentityUpdate {
	_u.mutation.ClearVerifiedAt()
	return _u
REDACTED

// SetIssuer sets the "issuer" field.
func (_u *AuthIdentityUpdate) SetIssuer(v string) *AuthIdentityUpdate {
	_u.mutation.SetIssuer(v)
	return _u
REDACTED

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *AuthIdentityUpdate) SetNillableIssuer(v *string) *AuthIdentityUpdate {
	if v != nil {
		_u.SetIssuer(*v)
REDACTED
	return _u
REDACTED

// ClearIssuer clears the value of the "issuer" field.
func (_u *AuthIdentityUpdate) ClearIssuer() *AuthIdentityUpdate {
	_u.mutation.ClearIssuer()
	return _u
REDACTED

// SetMetadata sets the "metadata" field.
func (_u *AuthIdentityUpdate) SetMetadata(v map[string]interface{REDACTED) *AuthIdentityUpdate {
	_u.mutation.SetMetadata(v)
	return _u
REDACTED

// SetUser sets the "user" edge to the User entity.
func (_u *AuthIdentityUpdate) SetUser(v *User) *AuthIdentityUpdate {
	return _u.SetUserID(v.ID)
REDACTED

// AddChannelIDs adds the "channels" edge to the AuthIdentityChannel entity by IDs.
func (_u *AuthIdentityUpdate) AddChannelIDs(ids ...int64) *AuthIdentityUpdate {
	_u.mutation.AddChannelIDs(ids...)
	return _u
REDACTED

// AddChannels adds the "channels" edges to the AuthIdentityChannel entity.
func (_u *AuthIdentityUpdate) AddChannels(v ...*AuthIdentityChannel) *AuthIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddChannelIDs(ids...)
REDACTED

// AddAdoptionDecisionIDs adds the "adoption_decisions" edge to the IdentityAdoptionDecision entity by IDs.
func (_u *AuthIdentityUpdate) AddAdoptionDecisionIDs(ids ...int64) *AuthIdentityUpdate {
	_u.mutation.AddAdoptionDecisionIDs(ids...)
	return _u
REDACTED

// AddAdoptionDecisions adds the "adoption_decisions" edges to the IdentityAdoptionDecision entity.
func (_u *AuthIdentityUpdate) AddAdoptionDecisions(v ...*IdentityAdoptionDecision) *AuthIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddAdoptionDecisionIDs(ids...)
REDACTED

// Mutation returns the AuthIdentityMutation object of the builder.
func (_u *AuthIdentityUpdate) Mutation() *AuthIdentityMutation {
	return _u.mutation
REDACTED

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthIdentityUpdate) ClearUser() *AuthIdentityUpdate {
	_u.mutation.ClearUser()
	return _u
REDACTED

// ClearChannels clears all "channels" edges to the AuthIdentityChannel entity.
func (_u *AuthIdentityUpdate) ClearChannels() *AuthIdentityUpdate {
	_u.mutation.ClearChannels()
	return _u
REDACTED

// RemoveChannelIDs removes the "channels" edge to AuthIdentityChannel entities by IDs.
func (_u *AuthIdentityUpdate) RemoveChannelIDs(ids ...int64) *AuthIdentityUpdate {
	_u.mutation.RemoveChannelIDs(ids...)
	return _u
REDACTED

// RemoveChannels removes "channels" edges to AuthIdentityChannel entities.
func (_u *AuthIdentityUpdate) RemoveChannels(v ...*AuthIdentityChannel) *AuthIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveChannelIDs(ids...)
REDACTED

// ClearAdoptionDecisions clears all "adoption_decisions" edges to the IdentityAdoptionDecision entity.
func (_u *AuthIdentityUpdate) ClearAdoptionDecisions() *AuthIdentityUpdate {
	_u.mutation.ClearAdoptionDecisions()
	return _u
REDACTED

// RemoveAdoptionDecisionIDs removes the "adoption_decisions" edge to IdentityAdoptionDecision entities by IDs.
func (_u *AuthIdentityUpdate) RemoveAdoptionDecisionIDs(ids ...int64) *AuthIdentityUpdate {
	_u.mutation.RemoveAdoptionDecisionIDs(ids...)
	return _u
REDACTED

// RemoveAdoptionDecisions removes "adoption_decisions" edges to IdentityAdoptionDecision entities.
func (_u *AuthIdentityUpdate) RemoveAdoptionDecisions(v ...*IdentityAdoptionDecision) *AuthIdentityUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveAdoptionDecisionIDs(ids...)
REDACTED

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AuthIdentityUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
REDACTED

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthIdentityUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
REDACTED
	return affected
REDACTED

// Exec executes the query.
func (_u *AuthIdentityUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
REDACTED

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthIdentityUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
REDACTED
REDACTED

// defaults sets the default values of the builder before save.
func (_u *AuthIdentityUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
REDACTED
REDACTED

// check runs all checks and user-defined validators on the builder.
func (_u *AuthIdentityUpdate) check() error {
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := authidentity.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_type": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := authidentity.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_key": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.ProviderSubject(); ok {
		if err := authidentity.ProviderSubjectValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_subject": %w`, err)REDACTED
	REDACTED
REDACTED
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthIdentity.user"`)
REDACTED
	return nil
REDACTED

func (_u *AuthIdentityUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
REDACTED
	_spec := sqlgraph.NewUpdateSpec(authidentity.Table, authidentity.Columns, sqlgraph.NewFieldSpec(authidentity.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		REDACTED
	REDACTED
REDACTED
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authidentity.FieldUpdatedAt, field.TypeTime, value)
REDACTED
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(authidentity.FieldProviderType, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(authidentity.FieldProviderKey, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ProviderSubject(); ok {
		_spec.SetField(authidentity.FieldProviderSubject, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(authidentity.FieldVerifiedAt, field.TypeTime, value)
REDACTED
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(authidentity.FieldVerifiedAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(authidentity.FieldIssuer, field.TypeString, value)
REDACTED
	if _u.mutation.IssuerCleared() {
		_spec.ClearField(authidentity.FieldIssuer, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authidentity.FieldMetadata, field.TypeJSON, value)
REDACTED
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authidentity.UserTable,
			Columns: []string{authidentity.UserColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authidentity.UserTable,
			Columns: []string{authidentity.UserColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedChannelsIDs(); len(nodes) > 0 && !_u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.AdoptionDecisionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedAdoptionDecisionsIDs(); len(nodes) > 0 && !_u.mutation.AdoptionDecisionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.AdoptionDecisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authidentity.LabelREDACTED
	REDACTED else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errREDACTED
	REDACTED
		return 0, err
REDACTED
	_u.mutation.done = true
	return _node, nil
REDACTED

// AuthIdentityUpdateOne is the builder for updating a single AuthIdentity entity.
type AuthIdentityUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AuthIdentityMutation
REDACTED

// SetUpdatedAt sets the "updated_at" field.
func (_u *AuthIdentityUpdateOne) SetUpdatedAt(v time.Time) *AuthIdentityUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
REDACTED

// SetUserID sets the "user_id" field.
func (_u *AuthIdentityUpdateOne) SetUserID(v int64) *AuthIdentityUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
REDACTED

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableUserID(v *int64) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
REDACTED
	return _u
REDACTED

// SetProviderType sets the "provider_type" field.
func (_u *AuthIdentityUpdateOne) SetProviderType(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetProviderType(v)
	return _u
REDACTED

// SetNillableProviderType sets the "provider_type" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableProviderType(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetProviderType(*v)
REDACTED
	return _u
REDACTED

// SetProviderKey sets the "provider_key" field.
func (_u *AuthIdentityUpdateOne) SetProviderKey(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetProviderKey(v)
	return _u
REDACTED

// SetNillableProviderKey sets the "provider_key" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableProviderKey(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetProviderKey(*v)
REDACTED
	return _u
REDACTED

// SetProviderSubject sets the "provider_subject" field.
func (_u *AuthIdentityUpdateOne) SetProviderSubject(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetProviderSubject(v)
	return _u
REDACTED

// SetNillableProviderSubject sets the "provider_subject" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableProviderSubject(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetProviderSubject(*v)
REDACTED
	return _u
REDACTED

// SetVerifiedAt sets the "verified_at" field.
func (_u *AuthIdentityUpdateOne) SetVerifiedAt(v time.Time) *AuthIdentityUpdateOne {
	_u.mutation.SetVerifiedAt(v)
	return _u
REDACTED

// SetNillableVerifiedAt sets the "verified_at" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableVerifiedAt(v *time.Time) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetVerifiedAt(*v)
REDACTED
	return _u
REDACTED

// ClearVerifiedAt clears the value of the "verified_at" field.
func (_u *AuthIdentityUpdateOne) ClearVerifiedAt() *AuthIdentityUpdateOne {
	_u.mutation.ClearVerifiedAt()
	return _u
REDACTED

// SetIssuer sets the "issuer" field.
func (_u *AuthIdentityUpdateOne) SetIssuer(v string) *AuthIdentityUpdateOne {
	_u.mutation.SetIssuer(v)
	return _u
REDACTED

// SetNillableIssuer sets the "issuer" field if the given value is not nil.
func (_u *AuthIdentityUpdateOne) SetNillableIssuer(v *string) *AuthIdentityUpdateOne {
	if v != nil {
		_u.SetIssuer(*v)
REDACTED
	return _u
REDACTED

// ClearIssuer clears the value of the "issuer" field.
func (_u *AuthIdentityUpdateOne) ClearIssuer() *AuthIdentityUpdateOne {
	_u.mutation.ClearIssuer()
	return _u
REDACTED

// SetMetadata sets the "metadata" field.
func (_u *AuthIdentityUpdateOne) SetMetadata(v map[string]interface{REDACTED) *AuthIdentityUpdateOne {
	_u.mutation.SetMetadata(v)
	return _u
REDACTED

// SetUser sets the "user" edge to the User entity.
func (_u *AuthIdentityUpdateOne) SetUser(v *User) *AuthIdentityUpdateOne {
	return _u.SetUserID(v.ID)
REDACTED

// AddChannelIDs adds the "channels" edge to the AuthIdentityChannel entity by IDs.
func (_u *AuthIdentityUpdateOne) AddChannelIDs(ids ...int64) *AuthIdentityUpdateOne {
	_u.mutation.AddChannelIDs(ids...)
	return _u
REDACTED

// AddChannels adds the "channels" edges to the AuthIdentityChannel entity.
func (_u *AuthIdentityUpdateOne) AddChannels(v ...*AuthIdentityChannel) *AuthIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddChannelIDs(ids...)
REDACTED

// AddAdoptionDecisionIDs adds the "adoption_decisions" edge to the IdentityAdoptionDecision entity by IDs.
func (_u *AuthIdentityUpdateOne) AddAdoptionDecisionIDs(ids ...int64) *AuthIdentityUpdateOne {
	_u.mutation.AddAdoptionDecisionIDs(ids...)
	return _u
REDACTED

// AddAdoptionDecisions adds the "adoption_decisions" edges to the IdentityAdoptionDecision entity.
func (_u *AuthIdentityUpdateOne) AddAdoptionDecisions(v ...*IdentityAdoptionDecision) *AuthIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddAdoptionDecisionIDs(ids...)
REDACTED

// Mutation returns the AuthIdentityMutation object of the builder.
func (_u *AuthIdentityUpdateOne) Mutation() *AuthIdentityMutation {
	return _u.mutation
REDACTED

// ClearUser clears the "user" edge to the User entity.
func (_u *AuthIdentityUpdateOne) ClearUser() *AuthIdentityUpdateOne {
	_u.mutation.ClearUser()
	return _u
REDACTED

// ClearChannels clears all "channels" edges to the AuthIdentityChannel entity.
func (_u *AuthIdentityUpdateOne) ClearChannels() *AuthIdentityUpdateOne {
	_u.mutation.ClearChannels()
	return _u
REDACTED

// RemoveChannelIDs removes the "channels" edge to AuthIdentityChannel entities by IDs.
func (_u *AuthIdentityUpdateOne) RemoveChannelIDs(ids ...int64) *AuthIdentityUpdateOne {
	_u.mutation.RemoveChannelIDs(ids...)
	return _u
REDACTED

// RemoveChannels removes "channels" edges to AuthIdentityChannel entities.
func (_u *AuthIdentityUpdateOne) RemoveChannels(v ...*AuthIdentityChannel) *AuthIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveChannelIDs(ids...)
REDACTED

// ClearAdoptionDecisions clears all "adoption_decisions" edges to the IdentityAdoptionDecision entity.
func (_u *AuthIdentityUpdateOne) ClearAdoptionDecisions() *AuthIdentityUpdateOne {
	_u.mutation.ClearAdoptionDecisions()
	return _u
REDACTED

// RemoveAdoptionDecisionIDs removes the "adoption_decisions" edge to IdentityAdoptionDecision entities by IDs.
func (_u *AuthIdentityUpdateOne) RemoveAdoptionDecisionIDs(ids ...int64) *AuthIdentityUpdateOne {
	_u.mutation.RemoveAdoptionDecisionIDs(ids...)
	return _u
REDACTED

// RemoveAdoptionDecisions removes "adoption_decisions" edges to IdentityAdoptionDecision entities.
func (_u *AuthIdentityUpdateOne) RemoveAdoptionDecisions(v ...*IdentityAdoptionDecision) *AuthIdentityUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveAdoptionDecisionIDs(ids...)
REDACTED

// Where appends a list predicates to the AuthIdentityUpdate builder.
func (_u *AuthIdentityUpdateOne) Where(ps ...predicate.AuthIdentity) *AuthIdentityUpdateOne {
	_u.mutation.Where(ps...)
	return _u
REDACTED

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AuthIdentityUpdateOne) Select(field string, fields ...string) *AuthIdentityUpdateOne {
	_u.fields = append([]string{fieldREDACTED, fields...)
	return _u
REDACTED

// Save executes the query and returns the updated AuthIdentity entity.
func (_u *AuthIdentityUpdateOne) Save(ctx context.Context) (*AuthIdentity, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
REDACTED

// SaveX is like Save, but panics if an error occurs.
func (_u *AuthIdentityUpdateOne) SaveX(ctx context.Context) *AuthIdentity {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
REDACTED
	return node
REDACTED

// Exec executes the query on the entity.
func (_u *AuthIdentityUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
REDACTED

// ExecX is like Exec, but panics if an error occurs.
func (_u *AuthIdentityUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
REDACTED
REDACTED

// defaults sets the default values of the builder before save.
func (_u *AuthIdentityUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := authidentity.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
REDACTED
REDACTED

// check runs all checks and user-defined validators on the builder.
func (_u *AuthIdentityUpdateOne) check() error {
	if v, ok := _u.mutation.ProviderType(); ok {
		if err := authidentity.ProviderTypeValidator(v); err != nil {
			return &ValidationError{Name: "provider_type", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_type": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.ProviderKey(); ok {
		if err := authidentity.ProviderKeyValidator(v); err != nil {
			return &ValidationError{Name: "provider_key", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_key": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.ProviderSubject(); ok {
		if err := authidentity.ProviderSubjectValidator(v); err != nil {
			return &ValidationError{Name: "provider_subject", err: fmt.Errorf(`ent: validator failed for field "AuthIdentity.provider_subject": %w`, err)REDACTED
	REDACTED
REDACTED
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AuthIdentity.user"`)
REDACTED
	return nil
REDACTED

func (_u *AuthIdentityUpdateOne) sqlSave(ctx context.Context) (_node *AuthIdentity, err error) {
	if err := _u.check(); err != nil {
		return _node, err
REDACTED
	_spec := sqlgraph.NewUpdateSpec(authidentity.Table, authidentity.Columns, sqlgraph.NewFieldSpec(authidentity.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AuthIdentity.id" for update`)REDACTED
REDACTED
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, authidentity.FieldID)
		for _, f := range fields {
			if !authidentity.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)REDACTED
		REDACTED
			if f != authidentity.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
		REDACTED
	REDACTED
REDACTED
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		REDACTED
	REDACTED
REDACTED
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(authidentity.FieldUpdatedAt, field.TypeTime, value)
REDACTED
	if value, ok := _u.mutation.ProviderType(); ok {
		_spec.SetField(authidentity.FieldProviderType, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ProviderKey(); ok {
		_spec.SetField(authidentity.FieldProviderKey, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ProviderSubject(); ok {
		_spec.SetField(authidentity.FieldProviderSubject, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.VerifiedAt(); ok {
		_spec.SetField(authidentity.FieldVerifiedAt, field.TypeTime, value)
REDACTED
	if _u.mutation.VerifiedAtCleared() {
		_spec.ClearField(authidentity.FieldVerifiedAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.Issuer(); ok {
		_spec.SetField(authidentity.FieldIssuer, field.TypeString, value)
REDACTED
	if _u.mutation.IssuerCleared() {
		_spec.ClearField(authidentity.FieldIssuer, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Metadata(); ok {
		_spec.SetField(authidentity.FieldMetadata, field.TypeJSON, value)
REDACTED
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authidentity.UserTable,
			Columns: []string{authidentity.UserColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   authidentity.UserTable,
			Columns: []string{authidentity.UserColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedChannelsIDs(); len(nodes) > 0 && !_u.mutation.ChannelsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.ChannelsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.ChannelsTable,
			Columns: []string{authidentity.ChannelsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(authidentitychannel.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.AdoptionDecisionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedAdoptionDecisionsIDs(); len(nodes) > 0 && !_u.mutation.AdoptionDecisionsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.AdoptionDecisionsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   authidentity.AdoptionDecisionsTable,
			Columns: []string{authidentity.AdoptionDecisionsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(identityadoptiondecision.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	_node = &AuthIdentity{config: _u.configREDACTED
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{authidentity.LabelREDACTED
	REDACTED else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errREDACTED
	REDACTED
		return nil, err
REDACTED
	_u.mutation.done = true
	return _node, nil
REDACTED
