// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/balanceledger"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// BalanceLedgerUpdate is the builder for updating BalanceLedger entities.
type BalanceLedgerUpdate struct {
	config
	hooks    []Hook
	mutation *BalanceLedgerMutation
}

// Where appends a list predicates to the BalanceLedgerUpdate builder.
func (_u *BalanceLedgerUpdate) Where(ps ...predicate.BalanceLedger) *BalanceLedgerUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLedgerUpdate) SetUpdatedAt(v time.Time) *BalanceLedgerUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *BalanceLedgerUpdate) SetRequestID(v string) *BalanceLedgerUpdate {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableRequestID(v *string) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *BalanceLedgerUpdate) SetAppID(v string) *BalanceLedgerUpdate {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableAppID(v *string) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLedgerUpdate) SetUserID(v int64) *BalanceLedgerUpdate {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableUserID(v *int64) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BalanceLedgerUpdate) AddUserID(v int64) *BalanceLedgerUpdate {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *BalanceLedgerUpdate) SetKind(v int8) *BalanceLedgerUpdate {
	_u.mutation.ResetKind()
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableKind(v *int8) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// AddKind adds value to the "kind" field.
func (_u *BalanceLedgerUpdate) AddKind(v int8) *BalanceLedgerUpdate {
	_u.mutation.AddKind(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceLedgerUpdate) SetAmount(v float64) *BalanceLedgerUpdate {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableAmount(v *float64) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceLedgerUpdate) AddAmount(v float64) *BalanceLedgerUpdate {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRefundedAmount sets the "refunded_amount" field.
func (_u *BalanceLedgerUpdate) SetRefundedAmount(v float64) *BalanceLedgerUpdate {
	_u.mutation.ResetRefundedAmount()
	_u.mutation.SetRefundedAmount(v)
	return _u
}

// SetNillableRefundedAmount sets the "refunded_amount" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableRefundedAmount(v *float64) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetRefundedAmount(*v)
	}
	return _u
}

// AddRefundedAmount adds value to the "refunded_amount" field.
func (_u *BalanceLedgerUpdate) AddRefundedAmount(v float64) *BalanceLedgerUpdate {
	_u.mutation.AddRefundedAmount(v)
	return _u
}

// SetRefundOf sets the "refund_of" field.
func (_u *BalanceLedgerUpdate) SetRefundOf(v string) *BalanceLedgerUpdate {
	_u.mutation.SetRefundOf(v)
	return _u
}

// SetNillableRefundOf sets the "refund_of" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableRefundOf(v *string) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetRefundOf(*v)
	}
	return _u
}

// ClearRefundOf clears the value of the "refund_of" field.
func (_u *BalanceLedgerUpdate) ClearRefundOf() *BalanceLedgerUpdate {
	_u.mutation.ClearRefundOf()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLedgerUpdate) SetDescription(v string) *BalanceLedgerUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableDescription(v *string) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *BalanceLedgerUpdate) SetExtra(v string) *BalanceLedgerUpdate {
	_u.mutation.SetExtra(v)
	return _u
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableExtra(v *string) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetExtra(*v)
	}
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceLedgerUpdate) SetBalanceAfter(v float64) *BalanceLedgerUpdate {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceLedgerUpdate) SetNillableBalanceAfter(v *float64) *BalanceLedgerUpdate {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceLedgerUpdate) AddBalanceAfter(v float64) *BalanceLedgerUpdate {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *BalanceLedgerUpdate) ClearBalanceAfter() *BalanceLedgerUpdate {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// Mutation returns the BalanceLedgerMutation object of the builder.
func (_u *BalanceLedgerUpdate) Mutation() *BalanceLedgerMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BalanceLedgerUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLedgerUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BalanceLedgerUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLedgerUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLedgerUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLedgerUpdate) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := balanceledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := balanceledger.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundOf(); ok {
		if err := balanceledger.RefundOfValidator(v); err != nil {
			return &ValidationError{Name: "refund_of", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.refund_of": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := balanceledger.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.description": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceLedgerUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balanceledger.Table, balanceledger.Columns, sqlgraph.NewFieldSpec(balanceledger.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(balanceledger.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(balanceledger.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(balanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(balanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(balanceledger.FieldKind, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedKind(); ok {
		_spec.AddField(balanceledger.FieldKind, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundedAmount(); ok {
		_spec.SetField(balanceledger.FieldRefundedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundedAmount(); ok {
		_spec.AddField(balanceledger.FieldRefundedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundOf(); ok {
		_spec.SetField(balanceledger.FieldRefundOf, field.TypeString, value)
	}
	if _u.mutation.RefundOfCleared() {
		_spec.ClearField(balanceledger.FieldRefundOf, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balanceledger.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(balanceledger.FieldExtra, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(balanceledger.FieldBalanceAfter, field.TypeFloat64)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BalanceLedgerUpdateOne is the builder for updating a single BalanceLedger entity.
type BalanceLedgerUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BalanceLedgerMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *BalanceLedgerUpdateOne) SetUpdatedAt(v time.Time) *BalanceLedgerUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetRequestID sets the "request_id" field.
func (_u *BalanceLedgerUpdateOne) SetRequestID(v string) *BalanceLedgerUpdateOne {
	_u.mutation.SetRequestID(v)
	return _u
}

// SetNillableRequestID sets the "request_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableRequestID(v *string) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetRequestID(*v)
	}
	return _u
}

// SetAppID sets the "app_id" field.
func (_u *BalanceLedgerUpdateOne) SetAppID(v string) *BalanceLedgerUpdateOne {
	_u.mutation.SetAppID(v)
	return _u
}

// SetNillableAppID sets the "app_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableAppID(v *string) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetAppID(*v)
	}
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *BalanceLedgerUpdateOne) SetUserID(v int64) *BalanceLedgerUpdateOne {
	_u.mutation.ResetUserID()
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableUserID(v *int64) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// AddUserID adds value to the "user_id" field.
func (_u *BalanceLedgerUpdateOne) AddUserID(v int64) *BalanceLedgerUpdateOne {
	_u.mutation.AddUserID(v)
	return _u
}

// SetKind sets the "kind" field.
func (_u *BalanceLedgerUpdateOne) SetKind(v int8) *BalanceLedgerUpdateOne {
	_u.mutation.ResetKind()
	_u.mutation.SetKind(v)
	return _u
}

// SetNillableKind sets the "kind" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableKind(v *int8) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetKind(*v)
	}
	return _u
}

// AddKind adds value to the "kind" field.
func (_u *BalanceLedgerUpdateOne) AddKind(v int8) *BalanceLedgerUpdateOne {
	_u.mutation.AddKind(v)
	return _u
}

// SetAmount sets the "amount" field.
func (_u *BalanceLedgerUpdateOne) SetAmount(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.ResetAmount()
	_u.mutation.SetAmount(v)
	return _u
}

// SetNillableAmount sets the "amount" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableAmount(v *float64) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetAmount(*v)
	}
	return _u
}

// AddAmount adds value to the "amount" field.
func (_u *BalanceLedgerUpdateOne) AddAmount(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.AddAmount(v)
	return _u
}

// SetRefundedAmount sets the "refunded_amount" field.
func (_u *BalanceLedgerUpdateOne) SetRefundedAmount(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.ResetRefundedAmount()
	_u.mutation.SetRefundedAmount(v)
	return _u
}

// SetNillableRefundedAmount sets the "refunded_amount" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableRefundedAmount(v *float64) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetRefundedAmount(*v)
	}
	return _u
}

// AddRefundedAmount adds value to the "refunded_amount" field.
func (_u *BalanceLedgerUpdateOne) AddRefundedAmount(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.AddRefundedAmount(v)
	return _u
}

// SetRefundOf sets the "refund_of" field.
func (_u *BalanceLedgerUpdateOne) SetRefundOf(v string) *BalanceLedgerUpdateOne {
	_u.mutation.SetRefundOf(v)
	return _u
}

// SetNillableRefundOf sets the "refund_of" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableRefundOf(v *string) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetRefundOf(*v)
	}
	return _u
}

// ClearRefundOf clears the value of the "refund_of" field.
func (_u *BalanceLedgerUpdateOne) ClearRefundOf() *BalanceLedgerUpdateOne {
	_u.mutation.ClearRefundOf()
	return _u
}

// SetDescription sets the "description" field.
func (_u *BalanceLedgerUpdateOne) SetDescription(v string) *BalanceLedgerUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableDescription(v *string) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetExtra sets the "extra" field.
func (_u *BalanceLedgerUpdateOne) SetExtra(v string) *BalanceLedgerUpdateOne {
	_u.mutation.SetExtra(v)
	return _u
}

// SetNillableExtra sets the "extra" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableExtra(v *string) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetExtra(*v)
	}
	return _u
}

// SetBalanceAfter sets the "balance_after" field.
func (_u *BalanceLedgerUpdateOne) SetBalanceAfter(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.ResetBalanceAfter()
	_u.mutation.SetBalanceAfter(v)
	return _u
}

// SetNillableBalanceAfter sets the "balance_after" field if the given value is not nil.
func (_u *BalanceLedgerUpdateOne) SetNillableBalanceAfter(v *float64) *BalanceLedgerUpdateOne {
	if v != nil {
		_u.SetBalanceAfter(*v)
	}
	return _u
}

// AddBalanceAfter adds value to the "balance_after" field.
func (_u *BalanceLedgerUpdateOne) AddBalanceAfter(v float64) *BalanceLedgerUpdateOne {
	_u.mutation.AddBalanceAfter(v)
	return _u
}

// ClearBalanceAfter clears the value of the "balance_after" field.
func (_u *BalanceLedgerUpdateOne) ClearBalanceAfter() *BalanceLedgerUpdateOne {
	_u.mutation.ClearBalanceAfter()
	return _u
}

// Mutation returns the BalanceLedgerMutation object of the builder.
func (_u *BalanceLedgerUpdateOne) Mutation() *BalanceLedgerMutation {
	return _u.mutation
}

// Where appends a list predicates to the BalanceLedgerUpdate builder.
func (_u *BalanceLedgerUpdateOne) Where(ps ...predicate.BalanceLedger) *BalanceLedgerUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BalanceLedgerUpdateOne) Select(field string, fields ...string) *BalanceLedgerUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated BalanceLedger entity.
func (_u *BalanceLedgerUpdateOne) Save(ctx context.Context) (*BalanceLedger, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BalanceLedgerUpdateOne) SaveX(ctx context.Context) *BalanceLedger {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BalanceLedgerUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BalanceLedgerUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *BalanceLedgerUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := balanceledger.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BalanceLedgerUpdateOne) check() error {
	if v, ok := _u.mutation.RequestID(); ok {
		if err := balanceledger.RequestIDValidator(v); err != nil {
			return &ValidationError{Name: "request_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.request_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AppID(); ok {
		if err := balanceledger.AppIDValidator(v); err != nil {
			return &ValidationError{Name: "app_id", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.app_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.RefundOf(); ok {
		if err := balanceledger.RefundOfValidator(v); err != nil {
			return &ValidationError{Name: "refund_of", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.refund_of": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := balanceledger.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "BalanceLedger.description": %w`, err)}
		}
	}
	return nil
}

func (_u *BalanceLedgerUpdateOne) sqlSave(ctx context.Context) (_node *BalanceLedger, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(balanceledger.Table, balanceledger.Columns, sqlgraph.NewFieldSpec(balanceledger.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "BalanceLedger.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, balanceledger.FieldID)
		for _, f := range fields {
			if !balanceledger.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != balanceledger.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(balanceledger.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.RequestID(); ok {
		_spec.SetField(balanceledger.FieldRequestID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AppID(); ok {
		_spec.SetField(balanceledger.FieldAppID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UserID(); ok {
		_spec.SetField(balanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedUserID(); ok {
		_spec.AddField(balanceledger.FieldUserID, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.Kind(); ok {
		_spec.SetField(balanceledger.FieldKind, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.AddedKind(); ok {
		_spec.AddField(balanceledger.FieldKind, field.TypeInt8, value)
	}
	if value, ok := _u.mutation.Amount(); ok {
		_spec.SetField(balanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedAmount(); ok {
		_spec.AddField(balanceledger.FieldAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundedAmount(); ok {
		_spec.SetField(balanceledger.FieldRefundedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedRefundedAmount(); ok {
		_spec.AddField(balanceledger.FieldRefundedAmount, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.RefundOf(); ok {
		_spec.SetField(balanceledger.FieldRefundOf, field.TypeString, value)
	}
	if _u.mutation.RefundOfCleared() {
		_spec.ClearField(balanceledger.FieldRefundOf, field.TypeString)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(balanceledger.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extra(); ok {
		_spec.SetField(balanceledger.FieldExtra, field.TypeString, value)
	}
	if value, ok := _u.mutation.BalanceAfter(); ok {
		_spec.SetField(balanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedBalanceAfter(); ok {
		_spec.AddField(balanceledger.FieldBalanceAfter, field.TypeFloat64, value)
	}
	if _u.mutation.BalanceAfterCleared() {
		_spec.ClearField(balanceledger.FieldBalanceAfter, field.TypeFloat64)
	}
	_node = &BalanceLedger{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{balanceledger.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
