// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/balanceledger"
)

// BalanceLedger is the model entity for the BalanceLedger schema.
type BalanceLedger struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// RequestID holds the value of the "request_id" field.
	RequestID string `json:"request_id,omitempty"`
	// AppID holds the value of the "app_id" field.
	AppID string `json:"app_id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// Kind holds the value of the "kind" field.
	Kind int8 `json:"kind,omitempty"`
	// Amount holds the value of the "amount" field.
	Amount float64 `json:"amount,omitempty"`
	// RefundedAmount holds the value of the "refunded_amount" field.
	RefundedAmount float64 `json:"refunded_amount,omitempty"`
	// RefundOf holds the value of the "refund_of" field.
	RefundOf *string `json:"refund_of,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Extra holds the value of the "extra" field.
	Extra string `json:"extra,omitempty"`
	// BalanceAfter holds the value of the "balance_after" field.
	BalanceAfter *float64 `json:"balance_after,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BalanceLedger) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case balanceledger.FieldAmount, balanceledger.FieldRefundedAmount, balanceledger.FieldBalanceAfter:
			values[i] = new(sql.NullFloat64)
		case balanceledger.FieldID, balanceledger.FieldUserID, balanceledger.FieldKind:
			values[i] = new(sql.NullInt64)
		case balanceledger.FieldRequestID, balanceledger.FieldAppID, balanceledger.FieldRefundOf, balanceledger.FieldDescription, balanceledger.FieldExtra:
			values[i] = new(sql.NullString)
		case balanceledger.FieldCreatedAt, balanceledger.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BalanceLedger fields.
func (_m *BalanceLedger) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case balanceledger.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case balanceledger.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case balanceledger.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case balanceledger.FieldRequestID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field request_id", values[i])
			} else if value.Valid {
				_m.RequestID = value.String
			}
		case balanceledger.FieldAppID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field app_id", values[i])
			} else if value.Valid {
				_m.AppID = value.String
			}
		case balanceledger.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case balanceledger.FieldKind:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field kind", values[i])
			} else if value.Valid {
				_m.Kind = int8(value.Int64)
			}
		case balanceledger.FieldAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field amount", values[i])
			} else if value.Valid {
				_m.Amount = value.Float64
			}
		case balanceledger.FieldRefundedAmount:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field refunded_amount", values[i])
			} else if value.Valid {
				_m.RefundedAmount = value.Float64
			}
		case balanceledger.FieldRefundOf:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field refund_of", values[i])
			} else if value.Valid {
				_m.RefundOf = new(string)
				*_m.RefundOf = value.String
			}
		case balanceledger.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case balanceledger.FieldExtra:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field extra", values[i])
			} else if value.Valid {
				_m.Extra = value.String
			}
		case balanceledger.FieldBalanceAfter:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field balance_after", values[i])
			} else if value.Valid {
				_m.BalanceAfter = new(float64)
				*_m.BalanceAfter = value.Float64
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BalanceLedger.
// This includes values selected through modifiers, order, etc.
func (_m *BalanceLedger) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this BalanceLedger.
// Note that you need to call BalanceLedger.Unwrap() before calling this method if this BalanceLedger
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BalanceLedger) Update() *BalanceLedgerUpdateOne {
	return NewBalanceLedgerClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BalanceLedger entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BalanceLedger) Unwrap() *BalanceLedger {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BalanceLedger is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BalanceLedger) String() string {
	var builder strings.Builder
	builder.WriteString("BalanceLedger(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("request_id=")
	builder.WriteString(_m.RequestID)
	builder.WriteString(", ")
	builder.WriteString("app_id=")
	builder.WriteString(_m.AppID)
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("kind=")
	builder.WriteString(fmt.Sprintf("%v", _m.Kind))
	builder.WriteString(", ")
	builder.WriteString("amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.Amount))
	builder.WriteString(", ")
	builder.WriteString("refunded_amount=")
	builder.WriteString(fmt.Sprintf("%v", _m.RefundedAmount))
	builder.WriteString(", ")
	if v := _m.RefundOf; v != nil {
		builder.WriteString("refund_of=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("extra=")
	builder.WriteString(_m.Extra)
	builder.WriteString(", ")
	if v := _m.BalanceAfter; v != nil {
		builder.WriteString("balance_after=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteByte(')')
	return builder.String()
}

// BalanceLedgers is a parsable slice of BalanceLedger.
type BalanceLedgers []*BalanceLedger
