// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/billingpool"
)

// BillingPool is the model entity for the BillingPool schema.
type BillingPool struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// DeletedAt holds the value of the "deleted_at" field.
	DeletedAt *time.Time `json:"deleted_at,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Code holds the value of the "code" field.
	Code string `json:"code,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// PlatformScope holds the value of the "platform_scope" field.
	PlatformScope string `json:"platform_scope,omitempty"`
	// AllowUserReorder holds the value of the "allow_user_reorder" field.
	AllowUserReorder bool `json:"allow_user_reorder,omitempty"`
	// RequirePrimarySubscription holds the value of the "require_primary_subscription" field.
	RequirePrimarySubscription bool `json:"require_primary_subscription,omitempty"`
	// AllowBalanceFallback holds the value of the "allow_balance_fallback" field.
	AllowBalanceFallback bool `json:"allow_balance_fallback,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the BillingPoolQuery when eager-loading is set.
	Edges        BillingPoolEdges `json:"edges"`
	selectValues sql.SelectValues
}

// BillingPoolEdges holds the relations/edges for other nodes in the graph.
type BillingPoolEdges struct {
	// Members holds the value of the members edge.
	Members []*BillingPoolGroup `json:"members,omitempty"`
	// APIKeys holds the value of the api_keys edge.
	APIKeys []*APIKey `json:"api_keys,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// MembersOrErr returns the Members value or an error if the edge
// was not loaded in eager-loading.
func (e BillingPoolEdges) MembersOrErr() ([]*BillingPoolGroup, error) {
	if e.loadedTypes[0] {
		return e.Members, nil
	}
	return nil, &NotLoadedError{edge: "members"}
}

// APIKeysOrErr returns the APIKeys value or an error if the edge
// was not loaded in eager-loading.
func (e BillingPoolEdges) APIKeysOrErr() ([]*APIKey, error) {
	if e.loadedTypes[1] {
		return e.APIKeys, nil
	}
	return nil, &NotLoadedError{edge: "api_keys"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BillingPool) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case billingpool.FieldAllowUserReorder, billingpool.FieldRequirePrimarySubscription, billingpool.FieldAllowBalanceFallback:
			values[i] = new(sql.NullBool)
		case billingpool.FieldID:
			values[i] = new(sql.NullInt64)
		case billingpool.FieldName, billingpool.FieldCode, billingpool.FieldDescription, billingpool.FieldStatus, billingpool.FieldPlatformScope:
			values[i] = new(sql.NullString)
		case billingpool.FieldCreatedAt, billingpool.FieldUpdatedAt, billingpool.FieldDeletedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BillingPool fields.
func (_m *BillingPool) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case billingpool.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case billingpool.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case billingpool.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case billingpool.FieldDeletedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field deleted_at", values[i])
			} else if value.Valid {
				_m.DeletedAt = new(time.Time)
				*_m.DeletedAt = value.Time
			}
		case billingpool.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case billingpool.FieldCode:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field code", values[i])
			} else if value.Valid {
				_m.Code = value.String
			}
		case billingpool.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case billingpool.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case billingpool.FieldPlatformScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field platform_scope", values[i])
			} else if value.Valid {
				_m.PlatformScope = value.String
			}
		case billingpool.FieldAllowUserReorder:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_user_reorder", values[i])
			} else if value.Valid {
				_m.AllowUserReorder = value.Bool
			}
		case billingpool.FieldRequirePrimarySubscription:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field require_primary_subscription", values[i])
			} else if value.Valid {
				_m.RequirePrimarySubscription = value.Bool
			}
		case billingpool.FieldAllowBalanceFallback:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field allow_balance_fallback", values[i])
			} else if value.Valid {
				_m.AllowBalanceFallback = value.Bool
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the BillingPool.
// This includes values selected through modifiers, order, etc.
func (_m *BillingPool) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryMembers queries the "members" edge of the BillingPool entity.
func (_m *BillingPool) QueryMembers() *BillingPoolGroupQuery {
	return NewBillingPoolClient(_m.config).QueryMembers(_m)
}

// QueryAPIKeys queries the "api_keys" edge of the BillingPool entity.
func (_m *BillingPool) QueryAPIKeys() *APIKeyQuery {
	return NewBillingPoolClient(_m.config).QueryAPIKeys(_m)
}

// Update returns a builder for updating this BillingPool.
// Note that you need to call BillingPool.Unwrap() before calling this method if this BillingPool
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *BillingPool) Update() *BillingPoolUpdateOne {
	return NewBillingPoolClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the BillingPool entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *BillingPool) Unwrap() *BillingPool {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: BillingPool is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *BillingPool) String() string {
	var builder strings.Builder
	builder.WriteString("BillingPool(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DeletedAt; v != nil {
		builder.WriteString("deleted_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	builder.WriteString("code=")
	builder.WriteString(_m.Code)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("platform_scope=")
	builder.WriteString(_m.PlatformScope)
	builder.WriteString(", ")
	builder.WriteString("allow_user_reorder=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowUserReorder))
	builder.WriteString(", ")
	builder.WriteString("require_primary_subscription=")
	builder.WriteString(fmt.Sprintf("%v", _m.RequirePrimarySubscription))
	builder.WriteString(", ")
	builder.WriteString("allow_balance_fallback=")
	builder.WriteString(fmt.Sprintf("%v", _m.AllowBalanceFallback))
	builder.WriteByte(')')
	return builder.String()
}

// BillingPools is a parsable slice of BillingPool.
type BillingPools []*BillingPool
