// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/developerkey"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// DeveloperKeyCreate is the builder for creating a DeveloperKey entity.
type DeveloperKeyCreate struct {
	config
	mutation *DeveloperKeyMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetCreatedAt sets the "created_at" field.
func (_c *DeveloperKeyCreate) SetCreatedAt(v time.Time) *DeveloperKeyCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *DeveloperKeyCreate) SetNillableCreatedAt(v *time.Time) *DeveloperKeyCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *DeveloperKeyCreate) SetUpdatedAt(v time.Time) *DeveloperKeyCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *DeveloperKeyCreate) SetNillableUpdatedAt(v *time.Time) *DeveloperKeyCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *DeveloperKeyCreate) SetUserID(v int64) *DeveloperKeyCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetName sets the "name" field.
func (_c *DeveloperKeyCreate) SetName(v string) *DeveloperKeyCreate {
	_c.mutation.SetName(v)
	return _c
}

// SetKeyPrefix sets the "key_prefix" field.
func (_c *DeveloperKeyCreate) SetKeyPrefix(v string) *DeveloperKeyCreate {
	_c.mutation.SetKeyPrefix(v)
	return _c
}

// SetKeyHash sets the "key_hash" field.
func (_c *DeveloperKeyCreate) SetKeyHash(v string) *DeveloperKeyCreate {
	_c.mutation.SetKeyHash(v)
	return _c
}

// SetLastUsedAt sets the "last_used_at" field.
func (_c *DeveloperKeyCreate) SetLastUsedAt(v time.Time) *DeveloperKeyCreate {
	_c.mutation.SetLastUsedAt(v)
	return _c
}

// SetNillableLastUsedAt sets the "last_used_at" field if the given value is not nil.
func (_c *DeveloperKeyCreate) SetNillableLastUsedAt(v *time.Time) *DeveloperKeyCreate {
	if v != nil {
		_c.SetLastUsedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *DeveloperKeyCreate) SetUser(v *User) *DeveloperKeyCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the DeveloperKeyMutation object of the builder.
func (_c *DeveloperKeyCreate) Mutation() *DeveloperKeyMutation {
	return _c.mutation
}

// Save creates the DeveloperKey in the database.
func (_c *DeveloperKeyCreate) Save(ctx context.Context) (*DeveloperKey, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *DeveloperKeyCreate) SaveX(ctx context.Context) *DeveloperKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeveloperKeyCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeveloperKeyCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *DeveloperKeyCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := developerkey.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := developerkey.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *DeveloperKeyCreate) check() error {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "DeveloperKey.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "DeveloperKey.updated_at"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "DeveloperKey.user_id"`)}
	}
	if _, ok := _c.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "DeveloperKey.name"`)}
	}
	if v, ok := _c.mutation.Name(); ok {
		if err := developerkey.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "DeveloperKey.name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyPrefix(); !ok {
		return &ValidationError{Name: "key_prefix", err: errors.New(`ent: missing required field "DeveloperKey.key_prefix"`)}
	}
	if v, ok := _c.mutation.KeyPrefix(); ok {
		if err := developerkey.KeyPrefixValidator(v); err != nil {
			return &ValidationError{Name: "key_prefix", err: fmt.Errorf(`ent: validator failed for field "DeveloperKey.key_prefix": %w`, err)}
		}
	}
	if _, ok := _c.mutation.KeyHash(); !ok {
		return &ValidationError{Name: "key_hash", err: errors.New(`ent: missing required field "DeveloperKey.key_hash"`)}
	}
	if v, ok := _c.mutation.KeyHash(); ok {
		if err := developerkey.KeyHashValidator(v); err != nil {
			return &ValidationError{Name: "key_hash", err: fmt.Errorf(`ent: validator failed for field "DeveloperKey.key_hash": %w`, err)}
		}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "DeveloperKey.user"`)}
	}
	return nil
}

func (_c *DeveloperKeyCreate) sqlSave(ctx context.Context) (*DeveloperKey, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *DeveloperKeyCreate) createSpec() (*DeveloperKey, *sqlgraph.CreateSpec) {
	var (
		_node = &DeveloperKey{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(developerkey.Table, sqlgraph.NewFieldSpec(developerkey.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(developerkey.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(developerkey.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if value, ok := _c.mutation.Name(); ok {
		_spec.SetField(developerkey.FieldName, field.TypeString, value)
		_node.Name = value
	}
	if value, ok := _c.mutation.KeyPrefix(); ok {
		_spec.SetField(developerkey.FieldKeyPrefix, field.TypeString, value)
		_node.KeyPrefix = value
	}
	if value, ok := _c.mutation.KeyHash(); ok {
		_spec.SetField(developerkey.FieldKeyHash, field.TypeString, value)
		_node.KeyHash = value
	}
	if value, ok := _c.mutation.LastUsedAt(); ok {
		_spec.SetField(developerkey.FieldLastUsedAt, field.TypeTime, value)
		_node.LastUsedAt = &value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   developerkey.UserTable,
			Columns: []string{developerkey.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeveloperKey.Create().
//		SetCreatedAt(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeveloperKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DeveloperKeyCreate) OnConflict(opts ...sql.ConflictOption) *DeveloperKeyUpsertOne {
	_c.conflict = opts
	return &DeveloperKeyUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeveloperKeyCreate) OnConflictColumns(columns ...string) *DeveloperKeyUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeveloperKeyUpsertOne{
		create: _c,
	}
}

type (
	// DeveloperKeyUpsertOne is the builder for "upsert"-ing
	//  one DeveloperKey node.
	DeveloperKeyUpsertOne struct {
		create *DeveloperKeyCreate
	}

	// DeveloperKeyUpsert is the "OnConflict" setter.
	DeveloperKeyUpsert struct {
		*sql.UpdateSet
	}
)

// SetUpdatedAt sets the "updated_at" field.
func (u *DeveloperKeyUpsert) SetUpdatedAt(v time.Time) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateUpdatedAt() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldUpdatedAt)
	return u
}

// SetUserID sets the "user_id" field.
func (u *DeveloperKeyUpsert) SetUserID(v int64) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateUserID() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldUserID)
	return u
}

// SetName sets the "name" field.
func (u *DeveloperKeyUpsert) SetName(v string) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldName, v)
	return u
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateName() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldName)
	return u
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *DeveloperKeyUpsert) SetKeyPrefix(v string) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldKeyPrefix, v)
	return u
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateKeyPrefix() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldKeyPrefix)
	return u
}

// SetKeyHash sets the "key_hash" field.
func (u *DeveloperKeyUpsert) SetKeyHash(v string) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldKeyHash, v)
	return u
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateKeyHash() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldKeyHash)
	return u
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *DeveloperKeyUpsert) SetLastUsedAt(v time.Time) *DeveloperKeyUpsert {
	u.Set(developerkey.FieldLastUsedAt, v)
	return u
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsert) UpdateLastUsedAt() *DeveloperKeyUpsert {
	u.SetExcluded(developerkey.FieldLastUsedAt)
	return u
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *DeveloperKeyUpsert) ClearLastUsedAt() *DeveloperKeyUpsert {
	u.SetNull(developerkey.FieldLastUsedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeveloperKeyUpsertOne) UpdateNewValues() *DeveloperKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(developerkey.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *DeveloperKeyUpsertOne) Ignore() *DeveloperKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeveloperKeyUpsertOne) DoNothing() *DeveloperKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeveloperKeyCreate.OnConflict
// documentation for more info.
func (u *DeveloperKeyUpsertOne) Update(set func(*DeveloperKeyUpsert)) *DeveloperKeyUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeveloperKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeveloperKeyUpsertOne) SetUpdatedAt(v time.Time) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateUpdatedAt() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DeveloperKeyUpsertOne) SetUserID(v int64) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateUserID() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *DeveloperKeyUpsertOne) SetName(v string) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateName() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateName()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *DeveloperKeyUpsertOne) SetKeyPrefix(v string) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateKeyPrefix() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *DeveloperKeyUpsertOne) SetKeyHash(v string) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateKeyHash() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *DeveloperKeyUpsertOne) SetLastUsedAt(v time.Time) *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsertOne) UpdateLastUsedAt() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *DeveloperKeyUpsertOne) ClearLastUsedAt() *DeveloperKeyUpsertOne {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *DeveloperKeyUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeveloperKeyCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeveloperKeyUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *DeveloperKeyUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *DeveloperKeyUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// DeveloperKeyCreateBulk is the builder for creating many DeveloperKey entities in bulk.
type DeveloperKeyCreateBulk struct {
	config
	err      error
	builders []*DeveloperKeyCreate
	conflict []sql.ConflictOption
}

// Save creates the DeveloperKey entities in the database.
func (_c *DeveloperKeyCreateBulk) Save(ctx context.Context) ([]*DeveloperKey, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*DeveloperKey, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*DeveloperKeyMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *DeveloperKeyCreateBulk) SaveX(ctx context.Context) []*DeveloperKey {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *DeveloperKeyCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *DeveloperKeyCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.DeveloperKey.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.DeveloperKeyUpsert) {
//			SetCreatedAt(v+v).
//		}).
//		Exec(ctx)
func (_c *DeveloperKeyCreateBulk) OnConflict(opts ...sql.ConflictOption) *DeveloperKeyUpsertBulk {
	_c.conflict = opts
	return &DeveloperKeyUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *DeveloperKeyCreateBulk) OnConflictColumns(columns ...string) *DeveloperKeyUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &DeveloperKeyUpsertBulk{
		create: _c,
	}
}

// DeveloperKeyUpsertBulk is the builder for "upsert"-ing
// a bulk of DeveloperKey nodes.
type DeveloperKeyUpsertBulk struct {
	create *DeveloperKeyCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *DeveloperKeyUpsertBulk) UpdateNewValues() *DeveloperKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(developerkey.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.DeveloperKey.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *DeveloperKeyUpsertBulk) Ignore() *DeveloperKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *DeveloperKeyUpsertBulk) DoNothing() *DeveloperKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the DeveloperKeyCreateBulk.OnConflict
// documentation for more info.
func (u *DeveloperKeyUpsertBulk) Update(set func(*DeveloperKeyUpsert)) *DeveloperKeyUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&DeveloperKeyUpsert{UpdateSet: update})
	}))
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *DeveloperKeyUpsertBulk) SetUpdatedAt(v time.Time) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateUpdatedAt() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateUpdatedAt()
	})
}

// SetUserID sets the "user_id" field.
func (u *DeveloperKeyUpsertBulk) SetUserID(v int64) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateUserID() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateUserID()
	})
}

// SetName sets the "name" field.
func (u *DeveloperKeyUpsertBulk) SetName(v string) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetName(v)
	})
}

// UpdateName sets the "name" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateName() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateName()
	})
}

// SetKeyPrefix sets the "key_prefix" field.
func (u *DeveloperKeyUpsertBulk) SetKeyPrefix(v string) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetKeyPrefix(v)
	})
}

// UpdateKeyPrefix sets the "key_prefix" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateKeyPrefix() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateKeyPrefix()
	})
}

// SetKeyHash sets the "key_hash" field.
func (u *DeveloperKeyUpsertBulk) SetKeyHash(v string) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetKeyHash(v)
	})
}

// UpdateKeyHash sets the "key_hash" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateKeyHash() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateKeyHash()
	})
}

// SetLastUsedAt sets the "last_used_at" field.
func (u *DeveloperKeyUpsertBulk) SetLastUsedAt(v time.Time) *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.SetLastUsedAt(v)
	})
}

// UpdateLastUsedAt sets the "last_used_at" field to the value that was provided on create.
func (u *DeveloperKeyUpsertBulk) UpdateLastUsedAt() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.UpdateLastUsedAt()
	})
}

// ClearLastUsedAt clears the value of the "last_used_at" field.
func (u *DeveloperKeyUpsertBulk) ClearLastUsedAt() *DeveloperKeyUpsertBulk {
	return u.Update(func(s *DeveloperKeyUpsert) {
		s.ClearLastUsedAt()
	})
}

// Exec executes the query.
func (u *DeveloperKeyUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the DeveloperKeyCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for DeveloperKeyCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *DeveloperKeyUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
