// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/managedpolicyaction"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ManagedPolicyActionUpdate is the builder for updating ManagedPolicyAction entities.
type ManagedPolicyActionUpdate struct {
	config
	hooks    []Hook
	mutation *ManagedPolicyActionMutation
}

// Where appends a list predicates to the ManagedPolicyActionUpdate builder.
func (_u *ManagedPolicyActionUpdate) Where(ps ...predicate.ManagedPolicyAction) *ManagedPolicyActionUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// Mutation returns the ManagedPolicyActionMutation object of the builder.
func (_u *ManagedPolicyActionUpdate) Mutation() *ManagedPolicyActionMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ManagedPolicyActionUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedPolicyActionUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ManagedPolicyActionUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedPolicyActionUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ManagedPolicyActionUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(managedpolicyaction.Table, managedpolicyaction.Columns, sqlgraph.NewFieldSpec(managedpolicyaction.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedpolicyaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ManagedPolicyActionUpdateOne is the builder for updating a single ManagedPolicyAction entity.
type ManagedPolicyActionUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ManagedPolicyActionMutation
}

// Mutation returns the ManagedPolicyActionMutation object of the builder.
func (_u *ManagedPolicyActionUpdateOne) Mutation() *ManagedPolicyActionMutation {
	return _u.mutation
}

// Where appends a list predicates to the ManagedPolicyActionUpdate builder.
func (_u *ManagedPolicyActionUpdateOne) Where(ps ...predicate.ManagedPolicyAction) *ManagedPolicyActionUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ManagedPolicyActionUpdateOne) Select(field string, fields ...string) *ManagedPolicyActionUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ManagedPolicyAction entity.
func (_u *ManagedPolicyActionUpdateOne) Save(ctx context.Context) (*ManagedPolicyAction, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ManagedPolicyActionUpdateOne) SaveX(ctx context.Context) *ManagedPolicyAction {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ManagedPolicyActionUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ManagedPolicyActionUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ManagedPolicyActionUpdateOne) sqlSave(ctx context.Context) (_node *ManagedPolicyAction, err error) {
	_spec := sqlgraph.NewUpdateSpec(managedpolicyaction.Table, managedpolicyaction.Columns, sqlgraph.NewFieldSpec(managedpolicyaction.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ManagedPolicyAction.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, managedpolicyaction.FieldID)
		for _, f := range fields {
			if !managedpolicyaction.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != managedpolicyaction.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	_node = &ManagedPolicyAction{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{managedpolicyaction.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
