// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/proxy"
)

// ProxyUpdate is the builder for updating Proxy entities.
type ProxyUpdate struct {
	config
	hooks    []Hook
	mutation *ProxyMutation
REDACTED

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdate) Where(ps ...predicate.Proxy) *ProxyUpdate {
	_u.mutation.Where(ps...)
	return _u
REDACTED

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdate) SetUpdatedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
REDACTED

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdate) SetDeletedAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetDeletedAt(v)
	return _u
REDACTED

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableDeletedAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetDeletedAt(*v)
REDACTED
	return _u
REDACTED

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdate) ClearDeletedAt() *ProxyUpdate {
	_u.mutation.ClearDeletedAt()
	return _u
REDACTED

// SetName sets the "name" field.
func (_u *ProxyUpdate) SetName(v string) *ProxyUpdate {
	_u.mutation.SetName(v)
	return _u
REDACTED

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableName(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetName(*v)
REDACTED
	return _u
REDACTED

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdate) SetProtocol(v string) *ProxyUpdate {
	_u.mutation.SetProtocol(v)
	return _u
REDACTED

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableProtocol(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetProtocol(*v)
REDACTED
	return _u
REDACTED

// SetHost sets the "host" field.
func (_u *ProxyUpdate) SetHost(v string) *ProxyUpdate {
	_u.mutation.SetHost(v)
	return _u
REDACTED

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableHost(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetHost(*v)
REDACTED
	return _u
REDACTED

// SetPort sets the "port" field.
func (_u *ProxyUpdate) SetPort(v int) *ProxyUpdate {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
REDACTED

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePort(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetPort(*v)
REDACTED
	return _u
REDACTED

// AddPort adds value to the "port" field.
func (_u *ProxyUpdate) AddPort(v int) *ProxyUpdate {
	_u.mutation.AddPort(v)
	return _u
REDACTED

// SetUsername sets the "username" field.
func (_u *ProxyUpdate) SetUsername(v string) *ProxyUpdate {
	_u.mutation.SetUsername(v)
	return _u
REDACTED

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableUsername(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetUsername(*v)
REDACTED
	return _u
REDACTED

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdate) ClearUsername() *ProxyUpdate {
	_u.mutation.ClearUsername()
	return _u
REDACTED

// SetPassword sets the "password" field.
func (_u *ProxyUpdate) SetPassword(v string) *ProxyUpdate {
	_u.mutation.SetPassword(v)
	return _u
REDACTED

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillablePassword(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetPassword(*v)
REDACTED
	return _u
REDACTED

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdate) ClearPassword() *ProxyUpdate {
	_u.mutation.ClearPassword()
	return _u
REDACTED

// SetStatus sets the "status" field.
func (_u *ProxyUpdate) SetStatus(v string) *ProxyUpdate {
	_u.mutation.SetStatus(v)
	return _u
REDACTED

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableStatus(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetStatus(*v)
REDACTED
	return _u
REDACTED

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyUpdate) SetExpiresAt(v time.Time) *ProxyUpdate {
	_u.mutation.SetExpiresAt(v)
	return _u
REDACTED

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExpiresAt(v *time.Time) *ProxyUpdate {
	if v != nil {
		_u.SetExpiresAt(*v)
REDACTED
	return _u
REDACTED

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyUpdate) ClearExpiresAt() *ProxyUpdate {
	_u.mutation.ClearExpiresAt()
	return _u
REDACTED

// SetFallbackMode sets the "fallback_mode" field.
func (_u *ProxyUpdate) SetFallbackMode(v string) *ProxyUpdate {
	_u.mutation.SetFallbackMode(v)
	return _u
REDACTED

// SetNillableFallbackMode sets the "fallback_mode" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableFallbackMode(v *string) *ProxyUpdate {
	if v != nil {
		_u.SetFallbackMode(*v)
REDACTED
	return _u
REDACTED

// SetBackupProxyID sets the "backup_proxy_id" field.
func (_u *ProxyUpdate) SetBackupProxyID(v int64) *ProxyUpdate {
	_u.mutation.SetBackupProxyID(v)
	return _u
REDACTED

// SetNillableBackupProxyID sets the "backup_proxy_id" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableBackupProxyID(v *int64) *ProxyUpdate {
	if v != nil {
		_u.SetBackupProxyID(*v)
REDACTED
	return _u
REDACTED

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (_u *ProxyUpdate) ClearBackupProxyID() *ProxyUpdate {
	_u.mutation.ClearBackupProxyID()
	return _u
REDACTED

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (_u *ProxyUpdate) SetExpiryWarnDays(v int) *ProxyUpdate {
	_u.mutation.ResetExpiryWarnDays()
	_u.mutation.SetExpiryWarnDays(v)
	return _u
REDACTED

// SetNillableExpiryWarnDays sets the "expiry_warn_days" field if the given value is not nil.
func (_u *ProxyUpdate) SetNillableExpiryWarnDays(v *int) *ProxyUpdate {
	if v != nil {
		_u.SetExpiryWarnDays(*v)
REDACTED
	return _u
REDACTED

// AddExpiryWarnDays adds value to the "expiry_warn_days" field.
func (_u *ProxyUpdate) AddExpiryWarnDays(v int) *ProxyUpdate {
	_u.mutation.AddExpiryWarnDays(v)
	return _u
REDACTED

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdate) AddAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
REDACTED

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdate) AddAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddAccountIDs(ids...)
REDACTED

// SetBackupProxy sets the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdate) SetBackupProxy(v *Proxy) *ProxyUpdate {
	return _u.SetBackupProxyID(v.ID)
REDACTED

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdate) Mutation() *ProxyMutation {
	return _u.mutation
REDACTED

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdate) ClearAccounts() *ProxyUpdate {
	_u.mutation.ClearAccounts()
	return _u
REDACTED

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdate) RemoveAccountIDs(ids ...int64) *ProxyUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
REDACTED

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdate) RemoveAccounts(v ...*Account) *ProxyUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveAccountIDs(ids...)
REDACTED

// ClearBackupProxy clears the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdate) ClearBackupProxy() *ProxyUpdate {
	_u.mutation.ClearBackupProxy()
	return _u
REDACTED

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ProxyUpdate) Save(ctx context.Context) (int, error) {
	if err := _u.defaults(); err != nil {
		return 0, err
REDACTED
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
REDACTED

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
REDACTED
	return affected
REDACTED

// Exec executes the query.
func (_u *ProxyUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
REDACTED

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
REDACTED
REDACTED

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdate) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
	REDACTED
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
REDACTED
	return nil
REDACTED

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.FallbackMode(); ok {
		if err := proxy.FallbackModeValidator(v); err != nil {
			return &ValidationError{Name: "fallback_mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.fallback_mode": %w`, err)REDACTED
	REDACTED
REDACTED
	return nil
REDACTED

func (_u *ProxyUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
REDACTED
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		REDACTED
	REDACTED
REDACTED
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
REDACTED
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
REDACTED
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
REDACTED
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
REDACTED
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxy.FieldExpiresAt, field.TypeTime, value)
REDACTED
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxy.FieldExpiresAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.FallbackMode(); ok {
		_spec.SetField(proxy.FieldFallbackMode, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ExpiryWarnDays(); ok {
		_spec.SetField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.AddedExpiryWarnDays(); ok {
		_spec.AddField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
REDACTED
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.BackupProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumnREDACTED,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.BackupProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumnREDACTED,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.LabelREDACTED
	REDACTED else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errREDACTED
	REDACTED
		return 0, err
REDACTED
	_u.mutation.done = true
	return _node, nil
REDACTED

// ProxyUpdateOne is the builder for updating a single Proxy entity.
type ProxyUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ProxyMutation
REDACTED

// SetUpdatedAt sets the "updated_at" field.
func (_u *ProxyUpdateOne) SetUpdatedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
REDACTED

// SetDeletedAt sets the "deleted_at" field.
func (_u *ProxyUpdateOne) SetDeletedAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetDeletedAt(v)
	return _u
REDACTED

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableDeletedAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetDeletedAt(*v)
REDACTED
	return _u
REDACTED

// ClearDeletedAt clears the value of the "deleted_at" field.
func (_u *ProxyUpdateOne) ClearDeletedAt() *ProxyUpdateOne {
	_u.mutation.ClearDeletedAt()
	return _u
REDACTED

// SetName sets the "name" field.
func (_u *ProxyUpdateOne) SetName(v string) *ProxyUpdateOne {
	_u.mutation.SetName(v)
	return _u
REDACTED

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableName(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetName(*v)
REDACTED
	return _u
REDACTED

// SetProtocol sets the "protocol" field.
func (_u *ProxyUpdateOne) SetProtocol(v string) *ProxyUpdateOne {
	_u.mutation.SetProtocol(v)
	return _u
REDACTED

// SetNillableProtocol sets the "protocol" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableProtocol(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetProtocol(*v)
REDACTED
	return _u
REDACTED

// SetHost sets the "host" field.
func (_u *ProxyUpdateOne) SetHost(v string) *ProxyUpdateOne {
	_u.mutation.SetHost(v)
	return _u
REDACTED

// SetNillableHost sets the "host" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableHost(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetHost(*v)
REDACTED
	return _u
REDACTED

// SetPort sets the "port" field.
func (_u *ProxyUpdateOne) SetPort(v int) *ProxyUpdateOne {
	_u.mutation.ResetPort()
	_u.mutation.SetPort(v)
	return _u
REDACTED

// SetNillablePort sets the "port" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePort(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetPort(*v)
REDACTED
	return _u
REDACTED

// AddPort adds value to the "port" field.
func (_u *ProxyUpdateOne) AddPort(v int) *ProxyUpdateOne {
	_u.mutation.AddPort(v)
	return _u
REDACTED

// SetUsername sets the "username" field.
func (_u *ProxyUpdateOne) SetUsername(v string) *ProxyUpdateOne {
	_u.mutation.SetUsername(v)
	return _u
REDACTED

// SetNillableUsername sets the "username" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableUsername(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetUsername(*v)
REDACTED
	return _u
REDACTED

// ClearUsername clears the value of the "username" field.
func (_u *ProxyUpdateOne) ClearUsername() *ProxyUpdateOne {
	_u.mutation.ClearUsername()
	return _u
REDACTED

// SetPassword sets the "password" field.
func (_u *ProxyUpdateOne) SetPassword(v string) *ProxyUpdateOne {
	_u.mutation.SetPassword(v)
	return _u
REDACTED

// SetNillablePassword sets the "password" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillablePassword(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetPassword(*v)
REDACTED
	return _u
REDACTED

// ClearPassword clears the value of the "password" field.
func (_u *ProxyUpdateOne) ClearPassword() *ProxyUpdateOne {
	_u.mutation.ClearPassword()
	return _u
REDACTED

// SetStatus sets the "status" field.
func (_u *ProxyUpdateOne) SetStatus(v string) *ProxyUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
REDACTED

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableStatus(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
REDACTED
	return _u
REDACTED

// SetExpiresAt sets the "expires_at" field.
func (_u *ProxyUpdateOne) SetExpiresAt(v time.Time) *ProxyUpdateOne {
	_u.mutation.SetExpiresAt(v)
	return _u
REDACTED

// SetNillableExpiresAt sets the "expires_at" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExpiresAt(v *time.Time) *ProxyUpdateOne {
	if v != nil {
		_u.SetExpiresAt(*v)
REDACTED
	return _u
REDACTED

// ClearExpiresAt clears the value of the "expires_at" field.
func (_u *ProxyUpdateOne) ClearExpiresAt() *ProxyUpdateOne {
	_u.mutation.ClearExpiresAt()
	return _u
REDACTED

// SetFallbackMode sets the "fallback_mode" field.
func (_u *ProxyUpdateOne) SetFallbackMode(v string) *ProxyUpdateOne {
	_u.mutation.SetFallbackMode(v)
	return _u
REDACTED

// SetNillableFallbackMode sets the "fallback_mode" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableFallbackMode(v *string) *ProxyUpdateOne {
	if v != nil {
		_u.SetFallbackMode(*v)
REDACTED
	return _u
REDACTED

// SetBackupProxyID sets the "backup_proxy_id" field.
func (_u *ProxyUpdateOne) SetBackupProxyID(v int64) *ProxyUpdateOne {
	_u.mutation.SetBackupProxyID(v)
	return _u
REDACTED

// SetNillableBackupProxyID sets the "backup_proxy_id" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableBackupProxyID(v *int64) *ProxyUpdateOne {
	if v != nil {
		_u.SetBackupProxyID(*v)
REDACTED
	return _u
REDACTED

// ClearBackupProxyID clears the value of the "backup_proxy_id" field.
func (_u *ProxyUpdateOne) ClearBackupProxyID() *ProxyUpdateOne {
	_u.mutation.ClearBackupProxyID()
	return _u
REDACTED

// SetExpiryWarnDays sets the "expiry_warn_days" field.
func (_u *ProxyUpdateOne) SetExpiryWarnDays(v int) *ProxyUpdateOne {
	_u.mutation.ResetExpiryWarnDays()
	_u.mutation.SetExpiryWarnDays(v)
	return _u
REDACTED

// SetNillableExpiryWarnDays sets the "expiry_warn_days" field if the given value is not nil.
func (_u *ProxyUpdateOne) SetNillableExpiryWarnDays(v *int) *ProxyUpdateOne {
	if v != nil {
		_u.SetExpiryWarnDays(*v)
REDACTED
	return _u
REDACTED

// AddExpiryWarnDays adds value to the "expiry_warn_days" field.
func (_u *ProxyUpdateOne) AddExpiryWarnDays(v int) *ProxyUpdateOne {
	_u.mutation.AddExpiryWarnDays(v)
	return _u
REDACTED

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *ProxyUpdateOne) AddAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
REDACTED

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) AddAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.AddAccountIDs(ids...)
REDACTED

// SetBackupProxy sets the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdateOne) SetBackupProxy(v *Proxy) *ProxyUpdateOne {
	return _u.SetBackupProxyID(v.ID)
REDACTED

// Mutation returns the ProxyMutation object of the builder.
func (_u *ProxyUpdateOne) Mutation() *ProxyMutation {
	return _u.mutation
REDACTED

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *ProxyUpdateOne) ClearAccounts() *ProxyUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
REDACTED

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *ProxyUpdateOne) RemoveAccountIDs(ids ...int64) *ProxyUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
REDACTED

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *ProxyUpdateOne) RemoveAccounts(v ...*Account) *ProxyUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
REDACTED
	return _u.RemoveAccountIDs(ids...)
REDACTED

// ClearBackupProxy clears the "backup_proxy" edge to the Proxy entity.
func (_u *ProxyUpdateOne) ClearBackupProxy() *ProxyUpdateOne {
	_u.mutation.ClearBackupProxy()
	return _u
REDACTED

// Where appends a list predicates to the ProxyUpdate builder.
func (_u *ProxyUpdateOne) Where(ps ...predicate.Proxy) *ProxyUpdateOne {
	_u.mutation.Where(ps...)
	return _u
REDACTED

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ProxyUpdateOne) Select(field string, fields ...string) *ProxyUpdateOne {
	_u.fields = append([]string{fieldREDACTED, fields...)
	return _u
REDACTED

// Save executes the query and returns the updated Proxy entity.
func (_u *ProxyUpdateOne) Save(ctx context.Context) (*Proxy, error) {
	if err := _u.defaults(); err != nil {
		return nil, err
REDACTED
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
REDACTED

// SaveX is like Save, but panics if an error occurs.
func (_u *ProxyUpdateOne) SaveX(ctx context.Context) *Proxy {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
REDACTED
	return node
REDACTED

// Exec executes the query on the entity.
func (_u *ProxyUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
REDACTED

// ExecX is like Exec, but panics if an error occurs.
func (_u *ProxyUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
REDACTED
REDACTED

// defaults sets the default values of the builder before save.
func (_u *ProxyUpdateOne) defaults() error {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		if proxy.UpdateDefaultUpdatedAt == nil {
			return fmt.Errorf("ent: uninitialized proxy.UpdateDefaultUpdatedAt (forgotten import ent/runtime?)")
	REDACTED
		v := proxy.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
REDACTED
	return nil
REDACTED

// check runs all checks and user-defined validators on the builder.
func (_u *ProxyUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := proxy.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Proxy.name": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Protocol(); ok {
		if err := proxy.ProtocolValidator(v); err != nil {
			return &ValidationError{Name: "protocol", err: fmt.Errorf(`ent: validator failed for field "Proxy.protocol": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Host(); ok {
		if err := proxy.HostValidator(v); err != nil {
			return &ValidationError{Name: "host", err: fmt.Errorf(`ent: validator failed for field "Proxy.host": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Username(); ok {
		if err := proxy.UsernameValidator(v); err != nil {
			return &ValidationError{Name: "username", err: fmt.Errorf(`ent: validator failed for field "Proxy.username": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Password(); ok {
		if err := proxy.PasswordValidator(v); err != nil {
			return &ValidationError{Name: "password", err: fmt.Errorf(`ent: validator failed for field "Proxy.password": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.Status(); ok {
		if err := proxy.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Proxy.status": %w`, err)REDACTED
	REDACTED
REDACTED
	if v, ok := _u.mutation.FallbackMode(); ok {
		if err := proxy.FallbackModeValidator(v); err != nil {
			return &ValidationError{Name: "fallback_mode", err: fmt.Errorf(`ent: validator failed for field "Proxy.fallback_mode": %w`, err)REDACTED
	REDACTED
REDACTED
	return nil
REDACTED

func (_u *ProxyUpdateOne) sqlSave(ctx context.Context) (_node *Proxy, err error) {
	if err := _u.check(); err != nil {
		return _node, err
REDACTED
	_spec := sqlgraph.NewUpdateSpec(proxy.Table, proxy.Columns, sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Proxy.id" for update`)REDACTED
REDACTED
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, proxy.FieldID)
		for _, f := range fields {
			if !proxy.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)REDACTED
		REDACTED
			if f != proxy.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
		REDACTED
	REDACTED
REDACTED
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
		REDACTED
	REDACTED
REDACTED
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(proxy.FieldUpdatedAt, field.TypeTime, value)
REDACTED
	if value, ok := _u.mutation.DeletedAt(); ok {
		_spec.SetField(proxy.FieldDeletedAt, field.TypeTime, value)
REDACTED
	if _u.mutation.DeletedAtCleared() {
		_spec.ClearField(proxy.FieldDeletedAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(proxy.FieldName, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Protocol(); ok {
		_spec.SetField(proxy.FieldProtocol, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Host(); ok {
		_spec.SetField(proxy.FieldHost, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.Port(); ok {
		_spec.SetField(proxy.FieldPort, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.AddedPort(); ok {
		_spec.AddField(proxy.FieldPort, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.Username(); ok {
		_spec.SetField(proxy.FieldUsername, field.TypeString, value)
REDACTED
	if _u.mutation.UsernameCleared() {
		_spec.ClearField(proxy.FieldUsername, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Password(); ok {
		_spec.SetField(proxy.FieldPassword, field.TypeString, value)
REDACTED
	if _u.mutation.PasswordCleared() {
		_spec.ClearField(proxy.FieldPassword, field.TypeString)
REDACTED
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(proxy.FieldStatus, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ExpiresAt(); ok {
		_spec.SetField(proxy.FieldExpiresAt, field.TypeTime, value)
REDACTED
	if _u.mutation.ExpiresAtCleared() {
		_spec.ClearField(proxy.FieldExpiresAt, field.TypeTime)
REDACTED
	if value, ok := _u.mutation.FallbackMode(); ok {
		_spec.SetField(proxy.FieldFallbackMode, field.TypeString, value)
REDACTED
	if value, ok := _u.mutation.ExpiryWarnDays(); ok {
		_spec.SetField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
REDACTED
	if value, ok := _u.mutation.AddedExpiryWarnDays(); ok {
		_spec.AddField(proxy.FieldExpiryWarnDays, field.TypeInt, value)
REDACTED
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: true,
			Table:   proxy.AccountsTable,
			Columns: []string{proxy.AccountsColumnREDACTED,
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	if _u.mutation.BackupProxyCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumnREDACTED,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
REDACTED
	if nodes := _u.mutation.BackupProxyIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: false,
			Table:   proxy.BackupProxyTable,
			Columns: []string{proxy.BackupProxyColumnREDACTED,
			Bidi:    true,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(proxy.FieldID, field.TypeInt64),
		REDACTED,
	REDACTED
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
	REDACTED
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
REDACTED
	_node = &Proxy{config: _u.configREDACTED
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{proxy.LabelREDACTED
	REDACTED else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: errREDACTED
	REDACTED
		return nil, err
REDACTED
	_u.mutation.done = true
	return _node, nil
REDACTED
