// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/user"
	"github.com/Wei-Shaw/sub2api/ent/userallowedaccount"
)

// UserAllowedAccountUpdate is the builder for updating UserAllowedAccount entities.
type UserAllowedAccountUpdate struct {
	config
	hooks    []Hook
	mutation *UserAllowedAccountMutation
}

// Where appends a list predicates to the UserAllowedAccountUpdate builder.
func (_u *UserAllowedAccountUpdate) Where(ps ...predicate.UserAllowedAccount) *UserAllowedAccountUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *UserAllowedAccountUpdate) SetUserID(v int64) *UserAllowedAccountUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAllowedAccountUpdate) SetNillableUserID(v *int64) *UserAllowedAccountUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserAllowedAccountUpdate) SetAccountID(v int64) *UserAllowedAccountUpdate {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserAllowedAccountUpdate) SetNillableAccountID(v *int64) *UserAllowedAccountUpdate {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAllowedAccountUpdate) SetUser(v *User) *UserAllowedAccountUpdate {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UserAllowedAccountUpdate) SetAccount(v *Account) *UserAllowedAccountUpdate {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UserAllowedAccountMutation object of the builder.
func (_u *UserAllowedAccountUpdate) Mutation() *UserAllowedAccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAllowedAccountUpdate) ClearUser() *UserAllowedAccountUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UserAllowedAccountUpdate) ClearAccount() *UserAllowedAccountUpdate {
	_u.mutation.ClearAccount()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *UserAllowedAccountUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAllowedAccountUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *UserAllowedAccountUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAllowedAccountUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAllowedAccountUpdate) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedAccount.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedAccount.account"`)
	}
	return nil
}

func (_u *UserAllowedAccountUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userallowedaccount.Table, userallowedaccount.Columns, sqlgraph.NewFieldSpec(userallowedaccount.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userallowedaccount.FieldAccountID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.UserTable,
			Columns: []string{userallowedaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.UserTable,
			Columns: []string{userallowedaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.AccountTable,
			Columns: []string{userallowedaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.AccountTable,
			Columns: []string{userallowedaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userallowedaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// UserAllowedAccountUpdateOne is the builder for updating a single UserAllowedAccount entity.
type UserAllowedAccountUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *UserAllowedAccountMutation
}

// SetUserID sets the "user_id" field.
func (_u *UserAllowedAccountUpdateOne) SetUserID(v int64) *UserAllowedAccountUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *UserAllowedAccountUpdateOne) SetNillableUserID(v *int64) *UserAllowedAccountUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetAccountID sets the "account_id" field.
func (_u *UserAllowedAccountUpdateOne) SetAccountID(v int64) *UserAllowedAccountUpdateOne {
	_u.mutation.SetAccountID(v)
	return _u
}

// SetNillableAccountID sets the "account_id" field if the given value is not nil.
func (_u *UserAllowedAccountUpdateOne) SetNillableAccountID(v *int64) *UserAllowedAccountUpdateOne {
	if v != nil {
		_u.SetAccountID(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *UserAllowedAccountUpdateOne) SetUser(v *User) *UserAllowedAccountUpdateOne {
	return _u.SetUserID(v.ID)
}

// SetAccount sets the "account" edge to the Account entity.
func (_u *UserAllowedAccountUpdateOne) SetAccount(v *Account) *UserAllowedAccountUpdateOne {
	return _u.SetAccountID(v.ID)
}

// Mutation returns the UserAllowedAccountMutation object of the builder.
func (_u *UserAllowedAccountUpdateOne) Mutation() *UserAllowedAccountMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *UserAllowedAccountUpdateOne) ClearUser() *UserAllowedAccountUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccount clears the "account" edge to the Account entity.
func (_u *UserAllowedAccountUpdateOne) ClearAccount() *UserAllowedAccountUpdateOne {
	_u.mutation.ClearAccount()
	return _u
}

// Where appends a list predicates to the UserAllowedAccountUpdate builder.
func (_u *UserAllowedAccountUpdateOne) Where(ps ...predicate.UserAllowedAccount) *UserAllowedAccountUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *UserAllowedAccountUpdateOne) Select(field string, fields ...string) *UserAllowedAccountUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated UserAllowedAccount entity.
func (_u *UserAllowedAccountUpdateOne) Save(ctx context.Context) (*UserAllowedAccount, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *UserAllowedAccountUpdateOne) SaveX(ctx context.Context) *UserAllowedAccount {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *UserAllowedAccountUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *UserAllowedAccountUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *UserAllowedAccountUpdateOne) check() error {
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedAccount.user"`)
	}
	if _u.mutation.AccountCleared() && len(_u.mutation.AccountIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "UserAllowedAccount.account"`)
	}
	return nil
}

func (_u *UserAllowedAccountUpdateOne) sqlSave(ctx context.Context) (_node *UserAllowedAccount, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(userallowedaccount.Table, userallowedaccount.Columns, sqlgraph.NewFieldSpec(userallowedaccount.FieldUserID, field.TypeInt64), sqlgraph.NewFieldSpec(userallowedaccount.FieldAccountID, field.TypeInt64))
	if id, ok := _u.mutation.UserID(); !ok {
		return nil, &ValidationError{Name: "user_id", err: errors.New(`ent: missing "UserAllowedAccount.user_id" for update`)}
	} else {
		_spec.Node.CompositeID[0].Value = id
	}
	if id, ok := _u.mutation.AccountID(); !ok {
		return nil, &ValidationError{Name: "account_id", err: errors.New(`ent: missing "UserAllowedAccount.account_id" for update`)}
	} else {
		_spec.Node.CompositeID[1].Value = id
	}
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, len(fields))
		for i, f := range fields {
			if !userallowedaccount.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			_spec.Node.Columns[i] = f
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.UserTable,
			Columns: []string{userallowedaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.UserTable,
			Columns: []string{userallowedaccount.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.AccountTable,
			Columns: []string{userallowedaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   userallowedaccount.AccountTable,
			Columns: []string{userallowedaccount.AccountColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &UserAllowedAccount{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{userallowedaccount.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
