// Code generated by ent, DO NOT EDIT.

package identityadoptiondecision

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldID, id))
REDACTED

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldID, id))
REDACTED

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldID, id))
REDACTED

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldID, ids...))
REDACTED

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldID, ids...))
REDACTED

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldID, id))
REDACTED

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldID, id))
REDACTED

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldID, id))
REDACTED

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldID, id))
REDACTED

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldCreatedAt, v))
REDACTED

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldUpdatedAt, v))
REDACTED

// PendingAuthSessionID applies equality check predicate on the "pending_auth_session_id" field. It's identical to PendingAuthSessionIDEQ.
func PendingAuthSessionID(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldPendingAuthSessionID, v))
REDACTED

// IdentityID applies equality check predicate on the "identity_id" field. It's identical to IdentityIDEQ.
func IdentityID(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldIdentityID, v))
REDACTED

// AdoptDisplayName applies equality check predicate on the "adopt_display_name" field. It's identical to AdoptDisplayNameEQ.
func AdoptDisplayName(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptDisplayName, v))
REDACTED

// AdoptAvatar applies equality check predicate on the "adopt_avatar" field. It's identical to AdoptAvatarEQ.
func AdoptAvatar(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptAvatar, v))
REDACTED

// DecidedAt applies equality check predicate on the "decided_at" field. It's identical to DecidedAtEQ.
func DecidedAt(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldDecidedAt, v))
REDACTED

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldCreatedAt, v))
REDACTED

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldCreatedAt, v))
REDACTED

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldCreatedAt, vs...))
REDACTED

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldCreatedAt, vs...))
REDACTED

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldCreatedAt, v))
REDACTED

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldCreatedAt, v))
REDACTED

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldCreatedAt, v))
REDACTED

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldCreatedAt, v))
REDACTED

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldUpdatedAt, v))
REDACTED

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldUpdatedAt, v))
REDACTED

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldUpdatedAt, vs...))
REDACTED

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldUpdatedAt, vs...))
REDACTED

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldUpdatedAt, v))
REDACTED

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldUpdatedAt, v))
REDACTED

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldUpdatedAt, v))
REDACTED

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldUpdatedAt, v))
REDACTED

// PendingAuthSessionIDEQ applies the EQ predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDEQ(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldPendingAuthSessionID, v))
REDACTED

// PendingAuthSessionIDNEQ applies the NEQ predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDNEQ(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldPendingAuthSessionID, v))
REDACTED

// PendingAuthSessionIDIn applies the In predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDIn(vs ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldPendingAuthSessionID, vs...))
REDACTED

// PendingAuthSessionIDNotIn applies the NotIn predicate on the "pending_auth_session_id" field.
func PendingAuthSessionIDNotIn(vs ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldPendingAuthSessionID, vs...))
REDACTED

// IdentityIDEQ applies the EQ predicate on the "identity_id" field.
func IdentityIDEQ(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldIdentityID, v))
REDACTED

// IdentityIDNEQ applies the NEQ predicate on the "identity_id" field.
func IdentityIDNEQ(v int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldIdentityID, v))
REDACTED

// IdentityIDIn applies the In predicate on the "identity_id" field.
func IdentityIDIn(vs ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldIdentityID, vs...))
REDACTED

// IdentityIDNotIn applies the NotIn predicate on the "identity_id" field.
func IdentityIDNotIn(vs ...int64) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldIdentityID, vs...))
REDACTED

// IdentityIDIsNil applies the IsNil predicate on the "identity_id" field.
func IdentityIDIsNil() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIsNull(FieldIdentityID))
REDACTED

// IdentityIDNotNil applies the NotNil predicate on the "identity_id" field.
func IdentityIDNotNil() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotNull(FieldIdentityID))
REDACTED

// AdoptDisplayNameEQ applies the EQ predicate on the "adopt_display_name" field.
func AdoptDisplayNameEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptDisplayName, v))
REDACTED

// AdoptDisplayNameNEQ applies the NEQ predicate on the "adopt_display_name" field.
func AdoptDisplayNameNEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldAdoptDisplayName, v))
REDACTED

// AdoptAvatarEQ applies the EQ predicate on the "adopt_avatar" field.
func AdoptAvatarEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldAdoptAvatar, v))
REDACTED

// AdoptAvatarNEQ applies the NEQ predicate on the "adopt_avatar" field.
func AdoptAvatarNEQ(v bool) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldAdoptAvatar, v))
REDACTED

// DecidedAtEQ applies the EQ predicate on the "decided_at" field.
func DecidedAtEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldEQ(FieldDecidedAt, v))
REDACTED

// DecidedAtNEQ applies the NEQ predicate on the "decided_at" field.
func DecidedAtNEQ(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNEQ(FieldDecidedAt, v))
REDACTED

// DecidedAtIn applies the In predicate on the "decided_at" field.
func DecidedAtIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldIn(FieldDecidedAt, vs...))
REDACTED

// DecidedAtNotIn applies the NotIn predicate on the "decided_at" field.
func DecidedAtNotIn(vs ...time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldNotIn(FieldDecidedAt, vs...))
REDACTED

// DecidedAtGT applies the GT predicate on the "decided_at" field.
func DecidedAtGT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGT(FieldDecidedAt, v))
REDACTED

// DecidedAtGTE applies the GTE predicate on the "decided_at" field.
func DecidedAtGTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldGTE(FieldDecidedAt, v))
REDACTED

// DecidedAtLT applies the LT predicate on the "decided_at" field.
func DecidedAtLT(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLT(FieldDecidedAt, v))
REDACTED

// DecidedAtLTE applies the LTE predicate on the "decided_at" field.
func DecidedAtLTE(v time.Time) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.FieldLTE(FieldDecidedAt, v))
REDACTED

// HasPendingAuthSession applies the HasEdge predicate on the "pending_auth_session" edge.
func HasPendingAuthSession() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, PendingAuthSessionTable, PendingAuthSessionColumn),
		)
		sqlgraph.HasNeighbors(s, step)
REDACTED)
REDACTED

// HasPendingAuthSessionWith applies the HasEdge predicate on the "pending_auth_session" edge with a given conditions (other predicates).
func HasPendingAuthSessionWith(preds ...predicate.PendingAuthSession) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := newPendingAuthSessionStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		REDACTED
	REDACTED)
REDACTED)
REDACTED

// HasIdentity applies the HasEdge predicate on the "identity" edge.
func HasIdentity() predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, IdentityTable, IdentityColumn),
		)
		sqlgraph.HasNeighbors(s, step)
REDACTED)
REDACTED

// HasIdentityWith applies the HasEdge predicate on the "identity" edge with a given conditions (other predicates).
func HasIdentityWith(preds ...predicate.AuthIdentity) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(func(s *sql.Selector) {
		step := newIdentityStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
		REDACTED
	REDACTED)
REDACTED)
REDACTED

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.AndPredicates(predicates...))
REDACTED

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.OrPredicates(predicates...))
REDACTED

// Not applies the not operator on the given predicate.
func Not(p predicate.IdentityAdoptionDecision) predicate.IdentityAdoptionDecision {
	return predicate.IdentityAdoptionDecision(sql.NotPredicates(p))
REDACTED
