package service

import (
	"math/rand/v2"
	"strings"
)

// naturalAccountTestPrompts contains short, harmless prompts used by text-based
// account connectivity tests. Keeping the answers brief limits probe cost while
// avoiding a single, easily distinguishable "hi" payload on every run.
var naturalAccountTestPrompts = [...]string{
	"Hello! How are you today? Reply briefly.",
	"What color is the sky on a clear day? Reply briefly.",
	"Name one fruit you enjoy. Reply briefly.",
	"What is a pleasant morning drink? Reply briefly.",
	"Name one common household pet. Reply briefly.",
	"What season comes after spring? Reply briefly.",
	"Name one thing people read. Reply briefly.",
	"What is a simple way to relax? Reply briefly.",
	"Name one warm color. Reply briefly.",
	"What do people use an umbrella for? Reply briefly.",
	"Name one musical instrument. Reply briefly.",
	"What is a common breakfast food? Reply briefly.",
	"Name one animal that can swim. Reply briefly.",
	"What is a friendly greeting? Reply briefly.",
	"Name one thing found in a garden. Reply briefly.",
	"What is a common mode of transport? Reply briefly.",
	"Name one cold drink. Reply briefly.",
	"What do people use a calendar for? Reply briefly.",
	"Name one type of weather. Reply briefly.",
	"What is a simple healthy habit? Reply briefly.",
	"Name one item found on a desk. Reply briefly.",
	"What sound does a clock make? Reply briefly.",
	"Name one place people visit on weekends. Reply briefly.",
	"What is a common indoor plant? Reply briefly.",
	"Name one food that is usually sweet. Reply briefly.",
	"What do people use a notebook for? Reply briefly.",
	"Name one outdoor activity. Reply briefly.",
	"What is a calm way to spend an evening? Reply briefly.",
	"Name one item used for cooking. Reply briefly.",
	"What is a common hot beverage? Reply briefly.",
	"Name one bird you might see in a park. Reply briefly.",
	"What do people use headphones for? Reply briefly.",
	"Name one shape with four sides. Reply briefly.",
	"What is a useful thing to carry while traveling? Reply briefly.",
	"Name one vegetable. Reply briefly.",
	"What do people use a lamp for? Reply briefly.",
	"Name one sport played with a ball. Reply briefly.",
	"What is a simple way to stay organized? Reply briefly.",
	"Name one thing found at a beach. Reply briefly.",
	"What do people use a map for? Reply briefly.",
	"Name one quiet indoor activity. Reply briefly.",
	"What is a common kitchen appliance? Reply briefly.",
	"Name one flower. Reply briefly.",
	"What do people use a backpack for? Reply briefly.",
	"Name one natural source of light. Reply briefly.",
	"What is a good way to keep hydrated? Reply briefly.",
	"Name one item of winter clothing. Reply briefly.",
	"What do people use a camera for? Reply briefly.",
	"Name one month of the year. Reply briefly.",
	"What is a common way to say thanks? Reply briefly.",
	"Name one tree fruit. Reply briefly.",
	"What do people use a key for? Reply briefly.",
	"Name one room in a home. Reply briefly.",
	"What is a simple way to exercise? Reply briefly.",
	"Name one object that can float. Reply briefly.",
	"What do people use a mirror for? Reply briefly.",
	"Name one sound heard in nature. Reply briefly.",
	"What is a common lunchtime meal? Reply briefly.",
	"Name one tool used for writing. Reply briefly.",
	"What do people use a pillow for? Reply briefly.",
	"Name one place where books are kept. Reply briefly.",
	"What is a simple way to be helpful? Reply briefly.",
	"Name one thing that grows on trees. Reply briefly.",
	"What do people use a phone for? Reply briefly.",
	"Name one color found in a rainbow. Reply briefly.",
	"What is a common weekend activity? Reply briefly.",
	"Name one item used in the rain. Reply briefly.",
	"What do people use a clock for? Reply briefly.",
	"Name one animal found on a farm. Reply briefly.",
	"What is a simple way to learn something new? Reply briefly.",
	"Name one food often served warm. Reply briefly.",
	"What do people use a chair for? Reply briefly.",
	"Name one thing seen in the night sky. Reply briefly.",
	"What is a common way to travel locally? Reply briefly.",
	"Name one item found in a classroom. Reply briefly.",
	"What do people use soap for? Reply briefly.",
	"Name one animal with four legs. Reply briefly.",
	"What is a simple way to save time? Reply briefly.",
	"Name one food made from grains. Reply briefly.",
	"What do people use a refrigerator for? Reply briefly.",
	"Name one thing that makes a room comfortable. Reply briefly.",
	"What is a friendly way to welcome someone? Reply briefly.",
	"Name one item used while traveling. Reply briefly.",
	"What do people use a cup for? Reply briefly.",
	"Name one activity people do in a park. Reply briefly.",
	"What is a simple way to get fresh air? Reply briefly.",
	"Name one object made of paper. Reply briefly.",
	"What do people use a towel for? Reply briefly.",
	"Name one food commonly eaten for breakfast. Reply briefly.",
	"What is a relaxing sound? Reply briefly.",
	"Name one item people wear on their feet. Reply briefly.",
	"What do people use a bookmark for? Reply briefly.",
	"Name one place where people exercise. Reply briefly.",
	"What is a simple way to show kindness? Reply briefly.",
	"Name one thing commonly found in an office. Reply briefly.",
	"What do people use a water bottle for? Reply briefly.",
	"Name one activity that uses a pencil. Reply briefly.",
	"What is a common way to greet a friend? Reply briefly.",
	"Name one thing that helps people stay dry. Reply briefly.",
	"What do people use a window for? Reply briefly.",
}

func resolveAccountTestTextPrompt(prompt string) string {
	if trimmed := strings.TrimSpace(prompt); trimmed != "" {
		return trimmed
	}
	return naturalAccountTestPrompts[rand.IntN(len(naturalAccountTestPrompts))]
}
