// Code generated by ent, DO NOT EDIT.

package companyupgradeapplication

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the companyupgradeapplication type in the database.
	Label = "company_upgrade_application"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldApplicantUserID holds the string denoting the applicant_user_id field in the database.
	FieldApplicantUserID = "applicant_user_id"
	// FieldRequestedName holds the string denoting the requested_name field in the database.
	FieldRequestedName = "requested_name"
	// FieldNormalizedName holds the string denoting the normalized_name field in the database.
	FieldNormalizedName = "normalized_name"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldFeeAmount holds the string denoting the fee_amount field in the database.
	FieldFeeAmount = "fee_amount"
	// FieldFeeCurrency holds the string denoting the fee_currency field in the database.
	FieldFeeCurrency = "fee_currency"
	// FieldIdempotencyKey holds the string denoting the idempotency_key field in the database.
	FieldIdempotencyKey = "idempotency_key"
	// FieldReviewerUserID holds the string denoting the reviewer_user_id field in the database.
	FieldReviewerUserID = "reviewer_user_id"
	// FieldReviewReason holds the string denoting the review_reason field in the database.
	FieldReviewReason = "review_reason"
	// FieldOrganizationID holds the string denoting the organization_id field in the database.
	FieldOrganizationID = "organization_id"
	// FieldDecidedAt holds the string denoting the decided_at field in the database.
	FieldDecidedAt = "decided_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the companyupgradeapplication in the database.
	Table = "company_upgrade_applications"
)

// Columns holds all SQL columns for companyupgradeapplication fields.
var Columns = []string{
	FieldID,
	FieldApplicantUserID,
	FieldRequestedName,
	FieldNormalizedName,
	FieldStatus,
	FieldFeeAmount,
	FieldFeeCurrency,
	FieldIdempotencyKey,
	FieldReviewerUserID,
	FieldReviewReason,
	FieldOrganizationID,
	FieldDecidedAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// RequestedNameValidator is a validator for the "requested_name" field. It is called by the builders before save.
	RequestedNameValidator func(string) error
	// NormalizedNameValidator is a validator for the "normalized_name" field. It is called by the builders before save.
	NormalizedNameValidator func(string) error
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// StatusValidator is a validator for the "status" field. It is called by the builders before save.
	StatusValidator func(string) error
	// DefaultFeeCurrency holds the default value on creation for the "fee_currency" field.
	DefaultFeeCurrency string
	// FeeCurrencyValidator is a validator for the "fee_currency" field. It is called by the builders before save.
	FeeCurrencyValidator func(string) error
	// IdempotencyKeyValidator is a validator for the "idempotency_key" field. It is called by the builders before save.
	IdempotencyKeyValidator func(string) error
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the CompanyUpgradeApplication queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByApplicantUserID orders the results by the applicant_user_id field.
func ByApplicantUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldApplicantUserID, opts...).ToFunc()
}

// ByRequestedName orders the results by the requested_name field.
func ByRequestedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRequestedName, opts...).ToFunc()
}

// ByNormalizedName orders the results by the normalized_name field.
func ByNormalizedName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNormalizedName, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByFeeAmount orders the results by the fee_amount field.
func ByFeeAmount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeAmount, opts...).ToFunc()
}

// ByFeeCurrency orders the results by the fee_currency field.
func ByFeeCurrency(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFeeCurrency, opts...).ToFunc()
}

// ByIdempotencyKey orders the results by the idempotency_key field.
func ByIdempotencyKey(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIdempotencyKey, opts...).ToFunc()
}

// ByReviewerUserID orders the results by the reviewer_user_id field.
func ByReviewerUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewerUserID, opts...).ToFunc()
}

// ByReviewReason orders the results by the review_reason field.
func ByReviewReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewReason, opts...).ToFunc()
}

// ByOrganizationID orders the results by the organization_id field.
func ByOrganizationID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOrganizationID, opts...).ToFunc()
}

// ByDecidedAt orders the results by the decided_at field.
func ByDecidedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDecidedAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
