// Code generated by ent, DO NOT EDIT.

package accountcodexprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the accountcodexprofile type in the database.
	Label = "account_codex_profile"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldOsClass holds the string denoting the os_class field in the database.
	FieldOsClass = "os_class"
	// FieldCanonicalSurface holds the string denoting the canonical_surface field in the database.
	FieldCanonicalSurface = "canonical_surface"
	// FieldArchitecture holds the string denoting the architecture field in the database.
	FieldArchitecture = "architecture"
	// FieldProxyMode holds the string denoting the proxy_mode field in the database.
	FieldProxyMode = "proxy_mode"
	// FieldProxyID holds the string denoting the proxy_id field in the database.
	FieldProxyID = "proxy_id"
	// FieldSlotCount holds the string denoting the slot_count field in the database.
	FieldSlotCount = "slot_count"
	// FieldEpoch holds the string denoting the epoch field in the database.
	FieldEpoch = "epoch"
	// FieldCatalogVersion holds the string denoting the catalog_version field in the database.
	FieldCatalogVersion = "catalog_version"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the accountcodexprofile in the database.
	Table = "account_codex_profiles"
)

// Columns holds all SQL columns for accountcodexprofile fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldOsClass,
	FieldCanonicalSurface,
	FieldArchitecture,
	FieldProxyMode,
	FieldProxyID,
	FieldSlotCount,
	FieldEpoch,
	FieldCatalogVersion,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// OsClassValidator is a validator for the "os_class" field. It is called by the builders before save.
	OsClassValidator func(string) error
	// CanonicalSurfaceValidator is a validator for the "canonical_surface" field. It is called by the builders before save.
	CanonicalSurfaceValidator func(string) error
	// ArchitectureValidator is a validator for the "architecture" field. It is called by the builders before save.
	ArchitectureValidator func(string) error
	// DefaultProxyMode holds the default value on creation for the "proxy_mode" field.
	DefaultProxyMode string
	// ProxyModeValidator is a validator for the "proxy_mode" field. It is called by the builders before save.
	ProxyModeValidator func(string) error
	// DefaultCatalogVersion holds the default value on creation for the "catalog_version" field.
	DefaultCatalogVersion int64
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
)

// OrderOption defines the ordering options for the AccountCodexProfile queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByAccountID orders the results by the account_id field.
func ByAccountID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAccountID, opts...).ToFunc()
}

// ByOsClass orders the results by the os_class field.
func ByOsClass(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOsClass, opts...).ToFunc()
}

// ByCanonicalSurface orders the results by the canonical_surface field.
func ByCanonicalSurface(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCanonicalSurface, opts...).ToFunc()
}

// ByArchitecture orders the results by the architecture field.
func ByArchitecture(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldArchitecture, opts...).ToFunc()
}

// ByProxyMode orders the results by the proxy_mode field.
func ByProxyMode(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyMode, opts...).ToFunc()
}

// ByProxyID orders the results by the proxy_id field.
func ByProxyID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldProxyID, opts...).ToFunc()
}

// BySlotCount orders the results by the slot_count field.
func BySlotCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlotCount, opts...).ToFunc()
}

// ByEpoch orders the results by the epoch field.
func ByEpoch(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEpoch, opts...).ToFunc()
}

// ByCatalogVersion orders the results by the catalog_version field.
func ByCatalogVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCatalogVersion, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
