<template>
  <AppLayout>
    <div class="mx-auto max-w-7xl space-y-6">
      <header class="flex flex-col justify-between gap-4 sm:flex-row sm:items-center"><div><p class="text-sm font-medium text-primary-600">{{ t('nav.tickets') }}</p><h1 class="mt-1 text-2xl font-bold text-gray-900 dark:text-white">帮助与支持</h1><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">提交问题、查看回复，并随时跟进工单进度。</p></div><button class="btn btn-primary" @click="showCreate = true"><Icon name="plus" size="sm" class="mr-1.5" />新建工单</button></header>
      <div v-if="error" class="rounded-xl border border-red-200 bg-red-50 px-4 py-3 text-sm text-red-700">{{ error }}</div>
      <div class="grid gap-6 lg:grid-cols-[20rem_minmax(0,1fr)]"><section class="rounded-2xl border border-gray-200/80 bg-white/80 p-3 shadow-sm dark:border-dark-700 dark:bg-dark-900/80"><div class="mb-3 flex justify-between px-2"><h2 class="font-semibold text-gray-900 dark:text-white">我的工单</h2><span class="text-xs text-gray-400">{{ tickets.length }}</span></div><div class="space-y-2"><button v-for="ticket in tickets" :key="ticket.id" class="w-full rounded-xl border p-3 text-left" :class="selected?.id === ticket.id ? 'border-primary-400 bg-primary-50 dark:bg-primary-950/40' : 'border-transparent bg-gray-50 dark:bg-dark-800/70'" @click="select(ticket.id)"><div class="flex items-start justify-between gap-2"><span class="truncate font-medium text-gray-900 dark:text-white">{{ ticket.title }}</span><span class="rounded-full px-2 py-0.5 text-[10px] font-semibold" :class="statusClass(ticket.status)">{{ statusLabel(ticket.status) }}</span></div><div class="mt-2 text-xs text-gray-500">#{{ ticket.id }} · {{ formatDate(ticket.updated_at) }}</div></button><div v-if="!tickets.length" class="rounded-xl border border-dashed p-10 text-center text-sm text-gray-500">还没有工单</div></div></section>
        <section v-if="selected" class="rounded-2xl border border-gray-200/80 bg-white/80 shadow-sm dark:border-dark-700 dark:bg-dark-900/80"><div class="flex items-start justify-between gap-4 border-b border-gray-100 p-5 dark:border-dark-700"><div><div class="flex flex-wrap items-center gap-3"><h2 class="text-xl font-bold text-gray-900 dark:text-white">{{ selected.title }}</h2><span class="rounded-full px-2 py-0.5 text-[10px] font-semibold" :class="statusClass(selected.status)">{{ statusLabel(selected.status) }}</span></div><p class="mt-1 text-xs text-gray-500">工单 #{{ selected.id }} · {{ formatDate(selected.created_at) }}</p></div><button v-if="selected.status !== 'closed'" class="btn btn-secondary text-red-600" :disabled="busy" @click="closeTicket"><Icon name="close" size="sm" class="mr-1" />关闭工单</button></div><div class="space-y-4 p-5"><div v-for="message in selected.messages" :key="message.id" class="rounded-2xl p-4" :class="message.sender_type === 'user' ? 'ml-8 bg-primary-50 dark:bg-primary-950/30' : 'mr-8 bg-gray-50 dark:bg-dark-800'"><div class="mb-2 text-xs text-gray-500">{{ message.sender_type === 'user' ? '我' : '管理员' }} · {{ formatDate(message.created_at) }}</div><div class="whitespace-pre-wrap text-sm">{{ message.content }}</div><TicketImageAttachments class="mt-3" :images="message.images || []" @preview="previewImage" /></div></div><form v-if="selected.status !== 'closed'" class="border-t border-gray-100 p-5 dark:border-dark-700" @submit.prevent="reply"><textarea v-model="replyText" class="input min-h-28 w-full resize-y" placeholder="继续描述你的问题或回复管理员…" required @paste="handlePaste($event, replyImages)" /><div class="mt-3 flex items-center justify-between gap-3"><div><label class="btn btn-secondary btn-sm cursor-pointer"><input type="file" accept="image/*" multiple class="hidden" @change="pickFiles($event, replyImages)" /><Icon name="upload" size="sm" class="mr-1.5" />添加图片</label><span class="ml-2 text-xs text-gray-500">{{ replyImages.length }}/9</span><TicketImageAttachments class="mt-2" :images="replyImages" removable @preview="previewImage" @remove="replyImages.splice($event, 1)" /></div><button class="btn btn-primary" :disabled="busy || !replyText.trim()">发送回复</button></div></form><div v-else class="border-t border-gray-100 px-5 py-4 text-sm text-gray-500">此工单已关闭，如需继续协助，请新建工单。</div></section><section v-else class="flex min-h-[28rem] items-center justify-center rounded-2xl border border-dashed border-gray-300 text-center"><div><Icon name="message" size="xl" class="mx-auto text-gray-400" /><h2 class="mt-4 font-semibold">选择一个工单</h2><p class="mt-1 text-sm text-gray-500">或点击“新建工单”提交新的问题。</p></div></section></div>
      <div v-if="showCreate" class="fixed inset-0 z-50 flex items-center justify-center bg-gray-950/50 p-4 backdrop-blur-sm" @click.self="showCreate = false"><form class="max-h-[90vh] w-full max-w-2xl overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl dark:bg-dark-900" @submit.prevent="create"><div class="flex items-start justify-between"><div><h2 class="text-xl font-bold">新建工单</h2><p class="mt-1 text-sm text-gray-500">可以直接将截图粘贴到问题描述框中。</p></div><button type="button" class="btn btn-ghost btn-sm" @click="showCreate = false"><Icon name="close" /></button></div><div class="mt-6 space-y-4"><label class="block"><span class="label">标题</span><input v-model="form.title" class="input mt-1 w-full" required maxlength="200" /></label><label class="block"><span class="label">问题描述</span><textarea v-model="form.description" class="input mt-1 min-h-40 w-full resize-y" placeholder="请描述复现步骤、时间和错误信息…" required maxlength="10000" @paste="handlePaste($event, form.images)" /></label><div><div class="flex items-center gap-3"><label class="btn btn-secondary btn-sm cursor-pointer"><input type="file" accept="image/*" multiple class="hidden" @change="pickFiles($event, form.images)" /><Icon name="upload" size="sm" class="mr-1.5" />添加图片</label><span class="text-xs text-gray-500">{{ form.images.length }}/9</span></div><TicketImageAttachments class="mt-3" :images="form.images" removable @preview="previewImage" @remove="form.images.splice($event, 1)" /></div></div><div class="mt-6 flex justify-end gap-3"><button type="button" class="btn btn-secondary" @click="showCreate = false">取消</button><button class="btn btn-primary" :disabled="busy || !form.title.trim() || !form.description.trim()">{{ busy ? '提交中…' : '提交工单' }}</button></div></form></div>
      <button v-if="newMessageCount" class="fixed bottom-6 left-1/2 z-30 -translate-x-1/2 rounded-full bg-primary-600 px-4 py-2 text-sm font-medium text-white shadow-lg" @click="scrollMessagesToBottom">有 {{ newMessageCount }} 条新消息，点击查看</button>
      <TicketImageLightbox v-model="lightboxImage" />
    </div>
  </AppLayout>
</template>
<script setup lang="ts">
import { nextTick, onBeforeUnmount, onMounted, ref } from 'vue'; import { useI18n } from 'vue-i18n'; import AppLayout from '@/components/layout/AppLayout.vue'; import Icon from '@/components/icons/Icon.vue'; import TicketImageAttachments from '@/components/common/TicketImageAttachments.vue'; import TicketImageLightbox from '@/components/common/TicketImageLightbox.vue'; import ticketsAPI, { type Ticket } from '@/api/tickets'
const { t } = useI18n(); const tickets = ref<Ticket[]>([]); const selected = ref<Ticket | null>(null); const showCreate = ref(false); const busy = ref(false); const error = ref(''); const replyText = ref(''); const replyImages = ref<string[]>([]); const lightboxImage = ref(''); const newMessageCount = ref(0); const form = ref({ title: '', description: '', images: [] as string[] }); const formatDate = (v: string) => new Date(v).toLocaleString(); const statusLabel = (s: string) => s === 'closed' ? '已关闭' : s === 'processing' ? '处理中' : '待处理'; const statusClass = (s: string) => s === 'closed' ? 'bg-gray-100 text-gray-500' : s === 'processing' ? 'bg-blue-100 text-blue-700' : 'bg-amber-100 text-amber-700'; const previewImage = (image: string) => { lightboxImage.value = image }
const messageList = () => document.querySelector<HTMLElement>('section > div.space-y-4')
const isAtMessageBottom = () => { const element = messageList(); return !element || element.scrollHeight - element.scrollTop - element.clientHeight < 24 }
async function scrollMessagesToBottom() { await nextTick(); const element = messageList(); if (element) element.scrollTop = element.scrollHeight; newMessageCount.value = 0 }
function handleWindowScroll(event: Event) { const target = event.target; if (target instanceof HTMLElement && target.matches('section > div.space-y-4') && isAtMessageBottom()) newMessageCount.value = 0 }
async function readFiles(files: File[]) { return Promise.all(files.filter(f => f.type.startsWith('image/')).map(file => new Promise<string>((resolve, reject) => { const reader = new FileReader(); reader.onload = () => resolve(String(reader.result)); reader.onerror = reject; reader.readAsDataURL(file) }))) }
async function pickFiles(event: Event, target: string[]) { const input = event.target as HTMLInputElement; target.push(...await readFiles(Array.from(input.files || []).slice(0, 9 - target.length))); input.value = '' }
async function handlePaste(event: ClipboardEvent, target: string[]) { const images = Array.from(event.clipboardData?.items || []).filter(item => item.type.startsWith('image/')).map(item => item.getAsFile()).filter((file): file is File => !!file); if (images.length) { event.preventDefault(); target.push(...await readFiles(images.slice(0, 9 - target.length))) } }
async function load(silent = false) { try { tickets.value = await ticketsAPI.list(); if (selected.value && tickets.value.some(ticket => ticket.id === selected.value?.id)) await select(selected.value.id, true); else if (tickets.value.length && !selected.value) await select(tickets.value[0].id) } catch (e) { if (!silent) error.value = String(e) } }
async function select(id: number, preserveScroll = false) { const previous = selected.value?.id === id ? selected.value.messages?.at(-1)?.id : undefined; const wasAtBottom = isAtMessageBottom(); try { selected.value = await ticketsAPI.get(id); const latest = selected.value.messages?.at(-1)?.id; if (preserveScroll && previous && latest && previous !== latest && !wasAtBottom) newMessageCount.value += 1; else { newMessageCount.value = 0; await scrollMessagesToBottom() } } catch (e) { error.value = String(e) } }
async function create() { busy.value = true; try { const ticket = await ticketsAPI.create(form.value); tickets.value.unshift(ticket); form.value = { title: '', description: '', images: [] }; showCreate.value = false; await select(ticket.id) } catch (e) { error.value = String(e) } finally { busy.value = false } }
async function reply() { if (!selected.value || !replyText.value.trim()) return; busy.value = true; try { await ticketsAPI.reply(selected.value.id, { content: replyText.value, images: replyImages.value }); replyText.value = ''; replyImages.value = []; await select(selected.value.id); await scrollMessagesToBottom() } catch (e) { error.value = String(e) } finally { busy.value = false } }
async function closeTicket() { if (!selected.value) return; busy.value = true; try { await ticketsAPI.close(selected.value.id); await load() } catch (e) { error.value = String(e) } finally { busy.value = false } }
let refreshTimer: ReturnType<typeof setInterval> | undefined
onMounted(() => { window.addEventListener('scroll', handleWindowScroll, true); void load(); refreshTimer = setInterval(() => { if (!busy.value) void load(true) }, 15000) })
onBeforeUnmount(() => { window.removeEventListener('scroll', handleWindowScroll, true); if (refreshTimer) clearInterval(refreshTimer) })
</script>
<style scoped>
section > div.space-y-4 {
  max-height: min(24rem, calc(100vh - 16rem));
  overflow-y: auto;
  overscroll-behavior: contain;
}

div.grid {
  align-items: start;
}
</style>
