export default {
  organization: {
    console: 'Company console', accountId: 'Account ID', accountType: { label: 'Account type', personal: 'Personal account', company: 'Company account' }, accountIdentity: { label: 'Account identity', root: 'Main account', iam: 'Sub-account' }, iamUserId: 'IAM user ID', principal: 'Principal', companyName: 'Company name', role: 'Role', policies: 'Policies', reviewReason: 'Review reason',
    roleValue: { owner: 'Organization owner', member: 'IAM user' },
    status: { pending: 'Pending', approved: 'Approved', rejected: 'Rejected', withdrawn: 'Withdrawn', active: 'Active', disabled: 'Disabled', archived: 'Archived', suspended: 'Suspended' },
    tabs: { members: 'Members', allocation: 'Allocation', finance: 'Finance', usage: 'Usage' },
    authorization: { title: 'Authorize {name}', subtitle: 'Select the policies to grant this user', empty: 'No policies available' },
    policyMeta: {
      CompanyFinanceReadOnly: { name: 'Company finance read only', description: 'View the root account available, frozen, and total balance.' },
      CompanySharedBalanceUse: { name: 'Company shared balance use', description: 'Use the root account balance for API consumption without viewing its amount.' }
    },
    login: { personal: 'Personal account', iam: 'IAM login', title: 'IAM user login', subtitle: 'Sign in with your full login account and password', loginName: 'Login name', principal: 'Login account', genericError: 'The login account or password is incorrect' },
    upgrade: { title: 'Upgrade to company account', backToProfile: 'Back to profile', feeLabel: 'Upgrade fee', feeNotice: 'The fee is frozen from your available balance when you submit. It is charged only after the upgrade is approved. If the upgrade is rejected or withdrawn, the frozen amount is returned to your balance.', chargedFee: 'Fee snapshot', submit: 'Submit for review', withdraw: 'Cancel application', insufficientBalance: 'Your balance cannot cover the upgrade fee', ineligible: { not_personal_root: 'This identity cannot request a company upgrade.', already_company_account: 'This account is already a company account.', application_pending: 'An upgrade application is already pending.', unknown: 'This account is not eligible for a company upgrade.' } },
	nameChange: { action: 'Request rename', title: 'Request company rename', submit: 'Submit for review', pending: 'The rename request is pending. The current company name remains active until approval.' },
    password: { title: 'Change initial password', new: 'New password', confirm: 'Confirm password', mismatch: 'The passwords do not match' },
	recovery: { title: 'IAM recovery email', code: 'Verification code', send: 'Send code', verify: 'Verify email', change: 'Change email', sent: 'Verification code sent.', verified: 'Recovery email verified.' },
	members: { slots: 'IAM users {used}/{limit}', create: 'Create IAM user', password: 'Password', generatePassword: 'Generate password', showPassword: 'Show password', hidePassword: 'Hide password', mustChangePassword: 'Require this user to change the password at first sign-in', recoveryEmail: 'Recovery email (optional)', allocateFunds: 'Allocate funds', resetPassword: 'Reset password', disable: 'Disable', enable: 'Enable', archive: 'Archive', archiveConfirm: 'Archive IAM user {name}? This cannot be undone.', authorize: 'Authorize', oneTimeCredential: 'One-time credentials', oneTimeWarning: 'This password cannot be displayed again after closing.', copied: 'Credentials copied' },
    allocation: { amount: 'Amount', allocate: 'Allocate', reclaim: 'Reclaim', rootAvailable: 'Root balance available to allocate: {amount}', targetAvailable: 'Target account available balance' },
    finance: { available: 'Available', frozen: 'Frozen', total: 'Total' },
    balanceSource: { label: 'Balance source', self: 'Root balance', allocated: 'Allocated member balance', shared: 'Shared root balance' },
    usage: { member: 'Member', allMembers: 'All members', apiKey: 'API key', apiKeyId: 'API key ID', model: 'Model', endpoint: 'Endpoint', tokens: 'Tokens', charge: 'Charge', duration: 'Duration (ms)', time: 'Request time', start: 'Start time', end: 'End time', charged: 'Charged', refunded: 'Refunded', total: '{total} records', previous: 'Previous', next: 'Next', statRequests: 'Total requests', statInputTokens: 'Input tokens', statOutputTokens: 'Output tokens', statCost: 'Total cost', trendTitle: 'Daily usage trend', trendEmpty: 'No trend data' },
    admin: { title: 'Company account reviews', applicant: 'Applicant', similar: 'Similar names', approve: 'Approve', reject: 'Reject', upgrades: 'Account upgrades', nameChanges: 'Name changes', organizations: 'Organizations', currentName: 'Current name', requestedName: 'Requested name', audit: 'Audit history', members: 'IAM members', suspend: 'Suspend', reactivate: 'Reactivate' }
  }
}
