//go:build embed

package web

import (
	"bytes"
	"context"
	"crypto/sha256"
	"embed"
	"encoding/hex"
	"encoding/json"
	"io"
	"io/fs"
	"net/http"
	"os"
	"path/filepath"
	"strings"
	"time"

	"github.com/Wei-Shaw/sub2api/internal/server/middleware"
	"github.com/gin-gonic/gin"
)

const (
	// NonceHTMLPlaceholder is the placeholder for nonce in HTML script tags
	NonceHTMLPlaceholder = "__CSP_NONCE_VALUE__"
)

//go:embed all:dist
var frontendFS embed.FS

// PublicSettingsProvider is an interface to fetch public settings
type PublicSettingsProvider interface {
	GetPublicSettingsForInjection(ctx context.Context) (any, error)
}

// PluginManifestProvider provides plugin manifests for frontend injection
type PluginManifestProvider interface {
	GetPluginManifestsJSON() []byte
}

// FrontendServer serves the embedded frontend with settings injection
type FrontendServer struct {
	distFS          fs.FS
	fileServer      http.Handler
	baseHTML        []byte
	cache           *HTMLCache
	settings        PublicSettingsProvider
	pluginManifests PluginManifestProvider
	overrideDir     string // local file override directory
}

// NewFrontendServer creates a new frontend server with settings injection
func NewFrontendServer(settingsProvider PublicSettingsProvider) (*FrontendServer, error) {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		return nil, err
	}

	// Read base HTML once
	file, err := distFS.Open("index.html")
	if err != nil {
		return nil, err
	}
	defer func() { _ = file.Close() }()

	baseHTML, err := io.ReadAll(file)
	if err != nil {
		return nil, err
	}

	cache := NewHTMLCache()
	cache.SetBaseHTML(baseHTML)

	return &FrontendServer{
		distFS:      distFS,
		fileServer:  http.FileServer(http.FS(distFS)),
		baseHTML:    baseHTML,
		cache:       cache,
		settings:    settingsProvider,
		overrideDir: filepath.Join("data", "public"),
	}, nil
}

// SetPluginManifestProvider sets the provider for plugin manifests.
// Called after FrontendServer construction when PluginManager is available.
func (s *FrontendServer) SetPluginManifestProvider(p PluginManifestProvider) {
	s.pluginManifests = p
	s.InvalidateCache()
}

// InvalidateCache invalidates the HTML cache (call when settings change)
func (s *FrontendServer) InvalidateCache() {
	if s != nil && s.cache != nil {
		s.cache.Invalidate()
	}
}

// Middleware returns the Gin middleware handler
func (s *FrontendServer) Middleware() gin.HandlerFunc {
	return func(c *gin.Context) {
		path := c.Request.URL.Path

		// Skip API routes
		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		// For index.html or SPA routes, serve with injected settings
		if cleanPath == "index.html" || !s.fileExists(cleanPath) {
			s.serveIndexHTML(c)
			return
		}

		// Try local override first
		if s.tryServeOverride(c, cleanPath) {
			return
		}

		// Serve static files normally
		s.fileServer.ServeHTTP(c.Writer, c.Request)
		c.Abort()
	}
}

func (s *FrontendServer) fileExists(path string) bool {
	file, err := s.distFS.Open(path)
	if err != nil {
		return false
	}
	_ = file.Close()
	return true
}

// tryServeOverride checks if a local override file exists and serves it.
// Files in overrideDir take precedence over embedded files.
func (s *FrontendServer) tryServeOverride(c *gin.Context, cleanPath string) bool {
	if s.overrideDir == "" {
		return false
	}
	filePath := filepath.Join(s.overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func (s *FrontendServer) serveIndexHTML(c *gin.Context) {
	// Get nonce from context (generated by SecurityHeaders middleware)
	nonce := middleware.GetNonceFromContext(c)

	// 不发送 ETag / 不接受 If-None-Match 协商, 也不发送 304:
	// SecurityHeaders 每个请求会生成新 nonce 写入 CSP header, 但 ETag 仅
	// 基于 baseHTML + settingsJSON, 不含 nonce. 一旦命中 304, 浏览器复用
	// 旧 body (含旧 nonce) 与新 CSP (含新 nonce) 不匹配, importmap 与
	// __APP_CONFIG__ / __PLUGIN_MANIFESTS__ 等所有内联 script 都会被
	// 浏览器以 CSP 违规阻止 — plugin 端 `import 'vue'` 因 importmap 失效
	// 而无法解析, plugin UI 不渲染. 因此放弃 304 协商, 总是返回 200 + 当前
	// nonce 的完整 body. 后端缓存 (rendered HTML 复用) 仍在生效.
	c.Header("Cache-Control", "no-store")

	// Check cache first
	cached := s.cache.Get()
	if cached != nil {
		content := replaceNoncePlaceholder(cached.Content, nonce)
		c.Data(http.StatusOK, "text/html; charset=utf-8", content)
		c.Abort()
		return
	}

	// Cache miss - fetch settings and render
	ctx, cancel := context.WithTimeout(c.Request.Context(), 2*time.Second)
	defer cancel()

	settings, err := s.settings.GetPublicSettingsForInjection(ctx)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	settingsJSON, err := json.Marshal(settings)
	if err != nil {
		// Fallback: serve without injection
		c.Data(http.StatusOK, "text/html; charset=utf-8", s.baseHTML)
		c.Abort()
		return
	}

	rendered := s.injectSettings(settingsJSON)
	s.cache.Set(rendered, settingsJSON)

	// Replace nonce placeholder with actual nonce before serving
	content := replaceNoncePlaceholder(rendered, nonce)

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

// pluginImportMap maps bare specifiers (vue / pinia / 等) to host-served ESM
// proxy modules under /api/v1/plugin-assets/__shared__/<name>.js. The proxy
// modules re-export the host's already-loaded singletons via window globals
// (see frontend/src/plugins/sdk/expose-runtime.ts), so plugin bundles 与
// host 共享同一份 vue / pinia / vue-router / vue-i18n / axios 实例.
//
// 浏览器原生 importmap 支持: 主流浏览器自 2023 起均支持; 旧 Edge / 老 webview
// 没有 polyfill, 此时 plugin entry 的 `import { ... } from 'vue'` 会失败,
// loader-runtime.ts 把错误捕获并显示 PluginView error state.
// sharedRuntimeVersion is a cache-busting token for importmap URLs.
// Changes whenever the binary is recompiled, ensuring browsers refetch
// shared runtime proxies after a deployment with updated exports.
var sharedRuntimeVersion = func() string {
	h := sha256.Sum256([]byte("v8-account-test-panel-sdk"))
	return hex.EncodeToString(h[:])[:12]
}()

func pluginImportMap() string {
	v := sharedRuntimeVersion
	return `<script type="importmap" nonce="__CSP_NONCE_VALUE__">{"imports":{` +
		`"vue":"/api/v1/plugin-assets/__shared__/vue.js?v=` + v + `",` +
		`"vue-router":"/api/v1/plugin-assets/__shared__/vue-router.js?v=` + v + `",` +
		`"vue-i18n":"/api/v1/plugin-assets/__shared__/vue-i18n.js?v=` + v + `",` +
		`"pinia":"/api/v1/plugin-assets/__shared__/pinia.js?v=` + v + `",` +
		`"axios":"/api/v1/plugin-assets/__shared__/axios.js?v=` + v + `",` +
		`"@sub2api/plugin-sdk":"/api/v1/plugin-assets/__shared__/plugin-sdk.js?v=` + v + `"` +
		`}}</script>`
}

// V2 (Shadow DOM) 协议下不再向 host head 注入 plugin-sdk.css —
// 改由 frontend/src/plugins/mount-plugin.ts 在每个 plugin 的独立 ShadowRoot 内
// 通过 <link> 注入. 这样 SDK 共享样式只作用于 plugin shadow tree, 不污染 host UI.
// 端点 /api/v1/plugin-assets/__shared__/plugin-sdk.css 仍然保留, 由 plugin 端按需拉取.

func (s *FrontendServer) injectSettings(settingsJSON []byte) []byte {
	safeSettings := bytes.ReplaceAll(settingsJSON, []byte("</"), []byte(`<\/`))
	script := []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__APP_CONFIG__=` + string(safeSettings) + `;</script>`)

	// Plugin-related injections only fire when a plugin manifest provider is
	// wired AND has at least one plugin to expose. Without active plugins:
	//   - importmap: pointing at /api/v1/plugin-assets/__shared__/* would 404
	//     because RegisterPluginAssetRoutes early-returns when pm == nil.
	//   - plugin-sdk.css: same 404 path.
	//   - manifests script: nothing to expose.
	// Conditional injection keeps a host with no plugins serving a clean HTML
	// shell that does not trigger spurious 404s on first load.
	var pluginScript []byte
	hasPlugins := false
	if s.pluginManifests != nil {
		if manifestJSON := s.pluginManifests.GetPluginManifestsJSON(); len(manifestJSON) > 0 {
			safeManifest := bytes.ReplaceAll(manifestJSON, []byte("</"), []byte(`<\/`))
			pluginScript = []byte(`<script nonce="` + NonceHTMLPlaceholder + `">window.__PLUGIN_MANIFESTS__=` + string(safeManifest) + `;</script>`)
			hasPlugins = true
		}
	}

	// 1) importmap 必须出现在第一个 <script type="module"> 之前 (W3C importmap spec).
	//    Vite 生产构建会把 host 主 bundle 的 <script type="module"> 放在 <head> 内部,
	//    位置早于 </head>. 之前我们把 importmap 也注入到 </head> 之前, 结果浏览器
	//    在解析到 importmap 时 host module script 已经开始 fetch, importmap 失效,
	//    plugin entry 里的 `import 'vue'` 因找不到 specifier 而抛 Failed to resolve.
	//    修复: 把 importmap 提前到 <head> 标签之后立刻插入, 保证早于任何 module script.
	//    (importmap script 同样受 CSP script-src 约束, 浏览器无 unsafe-inline 时必须有 nonce, 否则被静默丢弃 → bare specifier 解析失败.)
	afterHeadOpen := s.baseHTML
	if hasPlugins {
		headOpen := []byte("<head>")
		headOpenIdx := bytes.Index(s.baseHTML, headOpen)
		if headOpenIdx >= 0 {
			importMapHTML := pluginImportMap()
			afterHeadOpen = make([]byte, 0, len(s.baseHTML)+len(importMapHTML))
			afterHeadOpen = append(afterHeadOpen, s.baseHTML[:headOpenIdx+len(headOpen)]...)
			afterHeadOpen = append(afterHeadOpen, []byte(importMapHTML)...)
			afterHeadOpen = append(afterHeadOpen, s.baseHTML[headOpenIdx+len(headOpen):]...)
		}
	}

	// 2) 其他注入物 (app config script / plugin manifests script).
	//    plugin-sdk.css 在 V2 不再注入 host head, 改由 mount-plugin 在 ShadowRoot 内注入.
	headClose := []byte("</head>")
	var injection []byte
	injection = append(injection, script...)
	if len(pluginScript) > 0 {
		injection = append(injection, pluginScript...)
	}
	injection = append(injection, headClose...)
	result := bytes.Replace(afterHeadOpen, headClose, injection, 1)

	result = injectSiteTitle(result, settingsJSON)

	return result
}

// injectSiteTitle replaces the static <title> in HTML with the configured site name.
// This ensures the browser tab shows the correct title before JS executes.
func injectSiteTitle(html, settingsJSON []byte) []byte {
	var cfg struct {
		SiteName string `json:"site_name"`
	}
	if err := json.Unmarshal(settingsJSON, &cfg); err != nil || cfg.SiteName == "" {
		return html
	}

	// Find and replace the existing <title>...</title>
	titleStart := bytes.Index(html, []byte("<title>"))
	titleEnd := bytes.Index(html, []byte("</title>"))
	if titleStart == -1 || titleEnd == -1 || titleEnd <= titleStart {
		return html
	}

	newTitle := []byte("<title>" + cfg.SiteName + " - AI API Gateway</title>")
	var buf bytes.Buffer
	buf.Write(html[:titleStart])
	buf.Write(newTitle)
	buf.Write(html[titleEnd+len("</title>"):])
	return buf.Bytes()
}

// replaceNoncePlaceholder replaces the nonce placeholder with actual nonce value
func replaceNoncePlaceholder(html []byte, nonce string) []byte {
	return bytes.ReplaceAll(html, []byte(NonceHTMLPlaceholder), []byte(nonce))
}

// ServeEmbeddedFrontend returns a middleware for serving embedded frontend
// This is the legacy function for backward compatibility when no settings provider is available
func ServeEmbeddedFrontend() gin.HandlerFunc {
	distFS, err := fs.Sub(frontendFS, "dist")
	if err != nil {
		panic("failed to get dist subdirectory: " + err.Error())
	}
	fileServer := http.FileServer(http.FS(distFS))
	overrideDir := filepath.Join("data", "public")

	return func(c *gin.Context) {
		path := c.Request.URL.Path

		if shouldBypassEmbeddedFrontend(path) {
			c.Next()
			return
		}

		cleanPath := strings.TrimPrefix(path, "/")
		if cleanPath == "" {
			cleanPath = "index.html"
		}

		if file, err := distFS.Open(cleanPath); err == nil {
			_ = file.Close()
			// Try local override first
			if tryServeOverrideFile(c, overrideDir, cleanPath) {
				return
			}
			fileServer.ServeHTTP(c.Writer, c.Request)
			c.Abort()
			return
		}

		serveIndexHTML(c, distFS)
	}
}

// tryServeOverrideFile is a standalone version of tryServeOverride for legacy usage.
func tryServeOverrideFile(c *gin.Context, overrideDir, cleanPath string) bool {
	if overrideDir == "" {
		return false
	}
	filePath := filepath.Join(overrideDir, filepath.Clean("/"+cleanPath))
	info, err := os.Stat(filePath)
	if err != nil || info.IsDir() {
		return false
	}
	c.File(filePath)
	c.Abort()
	return true
}

func shouldBypassEmbeddedFrontend(path string) bool {
	trimmed := strings.TrimSpace(path)
	return strings.HasPrefix(trimmed, "/api/") ||
		strings.HasPrefix(trimmed, "/v1/") ||
		strings.HasPrefix(trimmed, "/v1beta/") ||
		strings.HasPrefix(trimmed, "/backend-api/") ||
		strings.HasPrefix(trimmed, "/antigravity/") ||
		strings.HasPrefix(trimmed, "/setup/") ||
		trimmed == "/health" ||
		trimmed == "/responses" ||
		strings.HasPrefix(trimmed, "/responses/") ||
		strings.HasPrefix(trimmed, "/images/")
}

func serveIndexHTML(c *gin.Context, fsys fs.FS) {
	file, err := fsys.Open("index.html")
	if err != nil {
		c.String(http.StatusNotFound, "Frontend not found")
		c.Abort()
		return
	}
	defer func() { _ = file.Close() }()

	content, err := io.ReadAll(file)
	if err != nil {
		c.String(http.StatusInternalServerError, "Failed to read index.html")
		c.Abort()
		return
	}

	c.Data(http.StatusOK, "text/html; charset=utf-8", content)
	c.Abort()
}

func HasEmbeddedFrontend() bool {
	_, err := frontendFS.ReadFile("dist/index.html")
	return err == nil
}

// ReadEmbeddedAsset reads a file from the embedded frontend dist directory.
// 用于 plugin assets 端点 (servePluginSharedAsset) 读取 host frontend 编译产物
// (例如 plugin-sdk.js / plugin-sdk.css), 让 plugin frontend 通过 importmap
// 共享 host 编译好的 SDK bundle.
//
// 参数 name 是 dist/ 下的相对路径 (如 "plugin-sdk.js"). 不允许 .. 越权,
// 调用方需自行限制.
func ReadEmbeddedAsset(name string) ([]byte, error) {
	return frontendFS.ReadFile("dist/" + name)
}
